#!/usr/bin/env python3
"""L05 WITHOUT an unrolling -- the same obligation, a RANK function instead of a depth.

`cdt_wohlgeformt` is *"every slot reaches WURZEL via parent"*, and `V1.lean` renders it as
`reachesIn`, a chain of `ite` unrolled to the table's own `count`. That is what makes the
formula grow with the bound, and it is the only reason the bound is in the file at all.

**The same predicate has a bound-free characterisation.** For a FUNCTIONAL parent edge, a
slot reaches the root within `N` steps exactly when there is a rank

    rank(WURZEL) = 0,   and   for x != WURZEL:  parent(x) = some p,
                                                rank(x) = rank(p) + 1,
                                                1 <= rank(x) < N

The forward direction is what this file needs: a rank witnesses reachability, so a model of
the rank form is a model of the reaches form. **A refutation therefore transfers.**

And the negated goal needs no unrolling either. `unlink` sets `parent[s] := None`; if
`s != WURZEL`, then `reachesIn(parent1, s, n)` is `false` at EVERY depth n, because depth 0
compares `s` with `WURZEL` and every deeper level falls to the `| _ => false` arm at once.
So the two outermost levels decide it, and they are written out below.

    ./gen-rank.py <N> [--wurzel]     `--wurzel` pins s = WURZEL: the control that must say no.
"""
import sys
N = sys.argv[1]
control = "--wurzel" in sys.argv
print(f""";; L05, rank encoding, N = {N}. Generated by gen-rank.py.
(set-option :timeout 60000)
(set-option :produce-models true)
(declare-datatypes ((Opt 0)) (((none) (some (idx Int)))))
(declare-const N Int)
(declare-const s Int)
(declare-const WURZEL Int)
(assert (= WURZEL 0))
(assert (= N {N}))
(assert (and (>= s 0) (< s N)))
(declare-fun parent0 (Int) Opt)
(declare-fun rank0 (Int) Int)

;; M1's range fact -- plumbing, GABBROV.md §9 point 4.
(assert (forall ((x Int)) (=> (and (>= x 0) (< x N))
  (=> ((_ is some) (parent0 x)) (and (>= (idx (parent0 x)) 0) (< (idx (parent0 x)) N))))))

;; THE PREMISE: `cdt_wohlgeformt` holds before -- as a rank, not as an unrolling.
(assert (= (rank0 WURZEL) 0))
(assert (forall ((x Int)) (=> (and (>= x 0) (< x N) (distinct x WURZEL))
  (and ((_ is some) (parent0 x))
       (>= (rank0 x) 1)
       (<  (rank0 x) N)
       (= (rank0 x) (+ 1 (rank0 (idx (parent0 x)))))))))

;; The body of `unlink`, in the one field the invariant reads.
(define-fun parent1 ((x Int)) Opt (ite (= x s) none (parent0 x)))
""")
if control:
    print(""";; CONTROL: the unlinked slot IS the root. Then the post-state reachability of `s`
;; is `true` at depth 0, the witness below cannot be built, and the run MUST say `unsat`.
;; Without this line the file could be `sat` because it says nothing.
(assert (= s WURZEL))""")
print(""";; THE GOAL, negated, at the witness slot `s`. The two outermost levels of `reachesIn`
;; over the POST state -- if this is false, `reachesIn` is false at every depth.
(define-fun reaches_post_s () Bool
  (ite (= s WURZEL) true (ite ((_ is some) (parent1 s)) true false)))
(assert (not reaches_post_s))
(check-sat)
(get-model)""")
