/-
  File:      Grammatik/CText108.lean
  Subject:   **A2 DISCHARGED for `beispiele/108-disjoint-start-locks.gab`**:
             the emitted C text, pinned line by line, parses in Lean to the
             C unit the correspondence certificate elaborates to -- and the
             closing theorem's binary hypothesis is stated about THAT text.

  CTEXT-PIN beispiele/108-disjoint-start-locks.gab zeilen108

  The second closed chain, and the one whose C touches a NAMED TABLE
  OBJECT: `T_speicher.slots[0].v` is `.ld (.slotA (.addr (.tab 0)) …)`,
  so the pin checks that the parser reads the table's block number off
  the declarations (`static T T_speicher;` at the first table typedef)
  and its geometry (`4 4 0`) off `T_slot slots[4]`.

  The header of `CText104.lean` explains the shape (a list of lines, not
  one string literal) and the cost behind it.
-/
import Grammatik.Kette108
import Grammatik.CParser.Bruecke

namespace Gabbro.Grammatik.CText108

open Gabbro.Grammatik Gabbro.Grammatik.CParser Gabbro.Grammatik.Kette108

/-! ## 1. The emitted text, line by line -/

-- CTEXT-BEGIN zeilen108
/-- The emitted C of `beispiele/108-disjoint-start-locks.gab`, one entry
    per line (41 lines, 1462 bytes), byte-identical to `gabbro emit`. -/
def zeilen108 : List (List Char) :=
  ["/* Generated by Gabbro -- https://github.com/SimonVitzethum/Gabbro\n".toList,
   " *\n".toList,
   " * This file was generated. Edit the .gab source, not this file.\n".toList,
   " *\n".toList,
   " * Gabbro is AGPL-3.0 with an additional permission: this generated file and the program it\n".toList,
   " * belongs to are NOT a derived work of Gabbro. You may remove this notice -- keeping it is a\n".toList,
   " * condition only where the result is presented as formally verified or secure, because a proof\n".toList,
   " * claim whose origin cannot be looked up is a claim nobody can check. See LIZENZ-ZUSATZ.md.\n".toList,
   " */\n".toList,
   "#include <stdint.h>\n".toList,
   "#include <stdbool.h>\n".toList,
   "#include <stdatomic.h>\n".toList,
   "#include <math.h>\n".toList,
   "/* The shift and conversion this generator relies on are implementation-defined in C11 --\n".toList,
   " * so the prelude pins them (PLAN-BITS.md section 5b), on EVERY unit, float or not.\n".toList,
   " * Two's complement itself is the language's own rule and needs no probe. */\n".toList,
   "_Static_assert((-1 >> 1) == -1, \"arithmetic right shift\");\n".toList,
   "_Static_assert((int)0xFFFFFFFFu == -1, \"modular conversion\");\n".toList,
   "\n".toList,
   "typedef struct {\n".toList,
   "    uint32_t v;\n".toList,
   "} T_slot;\n".toList,
   "\n".toList,
   "typedef struct {\n".toList,
   "    T_slot slots[4];\n".toList,
   "} T;\n".toList,
   "/* `T` is addressed by NAME: the table IS the storage (beispiele/09). */\n".toList,
   "static T T_speicher;\n".toList,
   "#define T_NONE (4)\n".toList,
   "\n".toList,
   "static uint32_t read_a(void) __attribute__((pure)) __attribute__((unused));\n".toList,
   "\n".toList,
   "static uint32_t read_c(void) __attribute__((pure)) __attribute__((unused));\n".toList,
   "\n".toList,
   "static uint32_t read_a(void) {\n".toList,
   "    return T_speicher.slots[0].v;\n".toList,
   "}\n".toList,
   "\n".toList,
   "static uint32_t read_c(void) {\n".toList,
   "    return T_speicher.slots[1].v;\n".toList,
   "}\n".toList]
-- CTEXT-END zeilen108

/-- The emitted text. -/
def ctext108 : List Char := zusammen zeilen108

/-! ## 2. A2, discharged -/

set_option maxRecDepth 100000
set_option maxHeartbeats 4000000

/-- **A2 FOR 108.** -/
theorem a2_108 : A2 ctext108 zert108 := rfl

/-- ... hence the C unit READ FROM THE TEXT is the one the closing
    theorem speaks about. -/
theorem cprog_108 : cProgC ctext108 = kProg zert108 := a2_kProg a2_108

/-! ## 3. Negative witnesses: one token changed -/

/-- Line 34, the read in `read_a`, at slot `2` instead of slot `0`. -/
def ctext108_index : List Char :=
  zusammen (zeilen108.set 35 "    return T_speicher.slots[2].v;\n".toList)

/-- Line 23, the slot count, `4` changed to `5`. -/
def ctext108_anzahl : List Char :=
  zusammen (zeilen108.set 24 "    T_slot slots[5];\n".toList)

/-- Line 26, the named table object, deleted: the read
    `T_speicher.slots[0].v` then names nothing the text declares. -/
def ctext108_ohneObjekt : List Char := zusammen (zeilen108.set 27 [])

/-- The certificate of `ctext108_index`: slot `2` in `read_a`. -/
def zert108_index : KCert D8 :=
  [{ params := [], locals := [],
     rows := [GRow.ret (some ((.int false .w32),
       (.ld (.slotA (.addr (.tab 0)) (.lit 2) 4 4 0) (.int false .w32))))],
     vm := [], pp := [], ks := [] },
   { params := [], locals := [],
     rows := [GRow.ret (some ((.int false .w32),
       (.ld (.slotA (.addr (.tab 0)) (.lit 1) 4 4 0) (.int false .w32))))],
     vm := [], pp := [], ks := [] }]

/-- The certificate of `ctext108_anzahl`: a table of FIVE slots. -/
def zert108_anzahl : KCert D8 :=
  [{ params := [], locals := [],
     rows := [GRow.ret (some ((.int false .w32),
       (.ld (.slotA (.addr (.tab 0)) (.lit 0) 5 4 0) (.int false .w32))))],
     vm := [], pp := [], ks := [] },
   { params := [], locals := [],
     rows := [GRow.ret (some ((.int false .w32),
       (.ld (.slotA (.addr (.tab 0)) (.lit 1) 5 4 0) (.int false .w32))))],
     vm := [], pp := [], ks := [] }]

/-- **THE PIN IS NOT SATISFIED BY A PARSER THAT ACCEPTS ANYTHING**: with
    one token changed the answer is a different program -- which `korrOk`
    then refuses against the parsed Gabbro program -- or `none`. -/
theorem a2_108_gegenprobe :
    parseC ctext108_index = some (kFuns zert108_index) ∧
    parseC ctext108_anzahl = some (kFuns zert108_anzahl) ∧
    parseC ctext108_ohneObjekt = none :=
  ⟨rfl, rfl, rfl⟩

theorem a2_108_gegenprobe_korr :
    korrOk EL8 fnNr zert108_index P8 fsA.1 = false ∧
    korrOk EL8 fnNr zert108_anzahl P8 fsA.1 = false := by
  constructor <;> decide

/-! ## 4. The closing theorem on 108, with the C side read from the text -/

/-- **A2 DISCHARGED on 108, part 6 of the closing theorem**: every run of
    the compiled binary of a function `f` ends related to the Gabbro
    call -- under A1 about the C unit of the EMITTED TEXT, with no hand
    transcription between the text and the theorem. -/
theorem kette_108_binaer_text
    (orc : DevOrc) (XR : CCallR) (hXR : XR.Funktional)
    (bin : D8.Fn → CSt → List CVal → CSt → Option CVal → Prop) (tief : D8.Fn → Nat)
    (hA1 : ∀ f st vs st' rv, bin f st vs st' rv →
      CallAt EL8.lay orc XR (cProgC ctext108) (tief f) (fnNr f) st vs st' rv)
    (sp : Speicher D8.mitRuhe)
    (init : Faden → Σ f : D8.mitRuhe.Fn, Env D8.mitRuhe (D8.mitRuhe.params f))
    (hA4 : EinFadenStart E8 sp init) :
    ∀ (passes : Nat) (f : D8.Fn) (k : KFun D8), zert108[fnNr f]? = some k →
      ∀ (σ : World D8) (st : CSt) (ρG : Env D8 (D8.params f)) (vs : List CVal) (ρ0 : CLok),
        corrW EL8 σ st → bindParams k.params vs = some ρ0 → EnvRel EL8 k.lay ρG ρ0 →
        (rufAt P8 O8 passes (tief f) f σ ρG).istFehler = false →
        ∀ st' rv, bin f st vs st' rv → RufOut EL8 (rufAt P8 O8 passes (tief f) f σ ρG) st' rv :=
  (schlusssatz_text kette_108 a2_108 O8 hw8 orc XR hXR bin tief hA1 sp init hA4).2.2.2.2.2.2.2.2.2

/-- **WITNESS**: `kette_108_zeuge` again, with the C side READ FROM THE
    TEXT -- `read_a()` on a memory holding `42` returns `42` in Gabbro,
    and every C run of the emitted text's `read_a` returns the C value
    `42`. -/
theorem kette_108_zeuge_text :
    ∃ (σ' : World D8) (v : ErgVal D8 (D8.erg a8)),
      rufAt P8 O8 0 1 a8 w42 .nil = .ok σ' v ∧ (show Zahl 0 4294967295 from v).n = 42 ∧
      (∃ st' rv, CallAt EL8.lay tvOrc tvXR (cProgC ctext108) 1 0 st42 [] st' rv) ∧
      ∀ st' rv, CallAt EL8.lay tvOrc tvXR (cProgC ctext108) 1 0 st42 [] st' rv →
        rv = some (.int 42) := by
  rw [cprog_108]
  exact kette_108_zeuge

#print axioms Gabbro.Grammatik.CText108.a2_108
#print axioms Gabbro.Grammatik.CText108.cprog_108
#print axioms Gabbro.Grammatik.CText108.a2_108_gegenprobe
#print axioms Gabbro.Grammatik.CText108.a2_108_gegenprobe_korr
#print axioms Gabbro.Grammatik.CText108.kette_108_binaer_text
#print axioms Gabbro.Grammatik.CText108.kette_108_zeuge_text

end Gabbro.Grammatik.CText108
