/-
  File:      Grammatik/CText104.lean
  Subject:   **A2 DISCHARGED for `beispiele/104-referenz.gab`**: the EMITTED
             C TEXT, pinned line by line, parses in Lean to the very C unit
             the correspondence certificate elaborates to.

  CTEXT-PIN beispiele/104-referenz.gab zeilen104

  Until now the chain said "the emitted TEXT means `kProg zert104`" -- a
  hand transcription, named as assumption A2 (plan
  `dokumente/PLAN-UEBERSETZUNGSVALIDIERUNG.md` §6.4). Here the text is
  DATA, the way `src104real` pins the Gabbro source, and

      a2_104 : parseC ctext104 = some (kFuns zert104)

  is one kernel reduction. What stays of A2 is "the C compiler's front
  end reads this subset as `parseC` does" -- part of A1, not an
  assumption of its own.

  `zeilen104` is the byte-identical output of `gabbro emit
  beispiele/104-referenz.gab`, one list entry per line, newline included
  (2026-09-15, binary built from this tree). `instrumente/pruefe-ctext.py`
  re-emits and compares, so a stale paste is a red guardian and not a
  silent lie. WHY A LIST OF LINES and not one string literal: the cost
  note at `CParser/CLexer.lean`'s `lexC` -- one 1419-byte literal costs
  the kernel 33,7 GB, the lines cost 3,3 GB.

  THE NEGATIVE WITNESSES (§3) are the reason the pin means anything: a
  parser that accepted anything would satisfy it too. Each mutated text
  is `zeilen104` with ONE line replaced.
-/
import Grammatik.Kette104
import Grammatik.CParser.Bruecke

namespace Gabbro.Grammatik.CText104

open Gabbro.Grammatik Gabbro.Grammatik.CParser Gabbro.Grammatik.Kette104

/-! ## 1. The emitted text, line by line -/

-- CTEXT-BEGIN zeilen104
/-- The emitted C of `beispiele/104-referenz.gab`, one entry per line
    (45 lines, 1419 bytes), byte-identical to `gabbro emit`. -/
def zeilen104 : List (List Char) :=
  ["/* Generated by Gabbro -- https://github.com/SimonVitzethum/Gabbro\n".toList,
   " *\n".toList,
   " * This file was generated. Edit the .gab source, not this file.\n".toList,
   " *\n".toList,
   " * Gabbro is AGPL-3.0 with an additional permission: this generated file and the program it\n".toList,
   " * belongs to are NOT a derived work of Gabbro. The permission is conditional on this notice\n".toList,
   " * being preserved. See LIZENZ-ZUSATZ.md.\n".toList,
   " */\n".toList,
   "#include <stdint.h>\n".toList,
   "#include <stdbool.h>\n".toList,
   "#include <stdatomic.h>\n".toList,
   "#include <math.h>\n".toList,
   "/* The shift and conversion this generator relies on are implementation-defined in C11 --\n".toList,
   " * so the prelude pins them (PLAN-BITS.md section 5b), on EVERY unit, float or not.\n".toList,
   " * Two's complement itself is the language's own rule and needs no probe. */\n".toList,
   "_Static_assert((-1 >> 1) == -1, \"arithmetic right shift\");\n".toList,
   "_Static_assert((int)0xFFFFFFFFu == -1, \"modular conversion\");\n".toList,
   "\n".toList,
   "#define NKONTO 2u\n".toList,
   "\n".toList,
   "typedef struct {\n".toList,
   "    uint32_t stand;\n".toList,
   "} Konto_slot;\n".toList,
   "\n".toList,
   "typedef struct {\n".toList,
   "    Konto_slot slots[NKONTO];\n".toList,
   "} Konto;\n".toList,
   "#define Konto_NONE (NKONTO)\n".toList,
   "\n".toList,
   "void M_nimm(void);\n".toList,
   "void M_gib(void);\n".toList,
   "\n".toList,
   "static void einzahlen(Konto *restrict k, uint32_t i, uint32_t b) __attribute__((unused));\n".toList,
   "\n".toList,
   "static uint32_t lies(const Konto *restrict k, uint32_t i) __attribute__((unused));\n".toList,
   "\n".toList,
   "static void einzahlen(Konto *restrict k, uint32_t i, uint32_t b) {\n".toList,
   "    (void)b;\n".toList,
   "    k->slots[i].stand = 100;\n".toList,
   "    (void)lies(k, i);\n".toList,
   "}\n".toList,
   "\n".toList,
   "static uint32_t lies(const Konto *restrict k, uint32_t i) {\n".toList,
   "    return k->slots[i].stand;\n".toList,
   "}\n".toList]
-- CTEXT-END zeilen104

/-- The emitted text. -/
def ctext104 : List Char := zusammen zeilen104

/-! ## 2. A2, discharged -/

set_option maxRecDepth 100000
-- The kernel reads 1419 bytes of C. Measured (2026-09-15,
-- `ki-pc-fisch-101`): this file 11 s, 2,7 GB peak.
set_option maxHeartbeats 4000000

/-- **A2 FOR 104.** The emitted TEXT parses, in the Lean kernel, to the C
    unit the correspondence certificate `zert104` elaborates to -- the
    table geometry (`2 4 0`: two slots, a four-byte record, the field at
    offset `0`) COMPUTED from `#define NKONTO 2u` and the two `typedef
    struct`s, the C function numbers from the order of the `static`
    declarations, the C locals from the parameter lists. -/
theorem a2_104 : A2 ctext104 zert104 := rfl

/-- ... hence the C unit READ FROM THE TEXT is the one the closing
    theorem speaks about. -/
theorem cprog_104 : cProgC ctext104 = kProg zert104 := a2_kProg a2_104

#print axioms Gabbro.Grammatik.CText104.a2_104
#print axioms Gabbro.Grammatik.CText104.cprog_104

end Gabbro.Grammatik.CText104
