-- GENERATED by `gabbro obligations --g beispiele/104-referenz.gab` (lean-g export plus the stated obligation) -- do not edit.
-- A mechanical export of the checked unit as a G program term
-- (`Programm gD`, the syntax `RufMaschineG.lean` runs).
--
-- NO FORM in G (accepted and dropped, each named): the module
-- wrapper; named constants (inlined at every use); bare carrier
-- widths (a bare word travels as its full range); pointer address
-- spaces; lock hold budgets;
-- the `reads` effects; `costs`; `concurrent` (all functions travel
-- in `gFs`; which of them start threads is not a G notion).
--
-- table 0: Konto (count 2), stand : 0..100
-- lock 0: M (rank 0) guards Konto
-- fn einzahlen (holds M; writes Konto)
-- fn lies (holds M; writes)
import Grammatik.ZielOrtGeraetSem
import Grammatik.SperreSem
import Grammatik.ZielOrtStart

namespace Gabbro.Grammatik

namespace G104_referenz_oblig

inductive GTab where
  | Konto
  deriving DecidableEq

inductive GLock where
  | M
  deriving DecidableEq

inductive GKontoFeld where
  | stand
  deriving DecidableEq

inductive GFn where
  | einzahlen
  | lies
  deriving DecidableEq

def gSig_einzahlen : Signatur GTab Empty GLock Empty where
  params := [.ptr 0 true, .index 2, .int 0 10]
  erg := none
  gruende := 0
  haelt := [GLock.M]
  schreibt := fun _ => true
  gschreibt := fun e => nomatch e
  konsumiert := []
  produziert := []

def gSig_lies : Signatur GTab Empty GLock Empty where
  params := [.ptr 0 false, .index 2]
  erg := some (.int 0 100)
  gruende := 0
  haelt := [GLock.M]
  schreibt := fun _ => false
  gschreibt := fun e => nomatch e
  konsumiert := []
  produziert := []

abbrev gD : Deklaration where
  Tab := GTab
  decTab := inferInstance
  count := fun | .Konto => 2
  Feld := fun | .Konto => GKontoFeld
  decFeld := fun | .Konto => inferInstance
  typ := fun | .Konto, .stand => .int 0 100
  erlaubt := fun _ _ _ _ => false
  tabNr := fun | 0 => some GTab.Konto | _ => none
  Glob := Empty
  decGlob := inferInstance
  gtyp := fun e => nomatch e
  nutzlast := fun e => nomatch e
  atomar := fun e => nomatch e
  geteilt := fun | .Konto => true
  ggeteilt := fun e => nomatch e
  Lock := GLock
  decLock := inferInstance
  rang := fun | .M => 0
  maskiert := fun _ => false
  Marke := Empty
  decMarke := inferInstance
  stufen := fun e => nomatch e
  braucht := fun | .Konto => [.inl GLock.M]
  gbraucht := fun e => nomatch e
  eigner := fun _ => []
  Fn := GFn
  sig := fun | .einzahlen => 0 | .lies => 1
  sigNr := fun | 0 => gSig_einzahlen | 1 => gSig_lies | _ => gSig_lies
  eigner_nie_erzeugt := fun _ _ _ _ h => by simp at h
  Inv := Empty
  traeger := fun e => nomatch e
  invs := []
  Ax := Empty
  aparams := fun e => nomatch e
  aerg := fun e => nomatch e
  aschreibt := fun e => nomatch e
  agschreibt := fun e => nomatch e
  Reg := Empty
  rtyp := fun e => nomatch e
  rklasse := fun e => nomatch e
  spiegel := fun e => nomatch e
  rzusage := fun e => nomatch e
  Annahme := Unit
  a10 := ()
  geteilt_bewacht := fun t => by cases t <;> decide
  invarianten_gehalten := fun _ i => nomatch i
  ggeteilt_bewacht := fun e => nomatch e

abbrev gCtx_einzahlen : Ctx := [.ptr 0 true, .index 2, .int 0 10]
abbrev gL_einzahlen : List (Res gD) := [Res.held (D := gD) GLock.M]
def g_einzahlen : gD.Fn := GFn.einzahlen
theorem gDarf_einzahlen_Konto : darf gD GTab.Konto gL_einzahlen := by unfold darf; decide

abbrev gCtx_lies : Ctx := [.ptr 0 false, .index 2]
abbrev gL_lies : List (Res gD) := [Res.held (D := gD) GLock.M]
def g_lies : gD.Fn := GFn.lies
theorem gDarf_lies_Konto : darf gD GTab.Konto gL_lies := by unfold darf; decide

theorem gHp_einzahlen_lies : RufPasst gD (vertragVon gD g_einzahlen) (gD.signatur g_lies) gL_einzahlen where
  hw := fun t => by cases t <;> decide
  hg := fun g => nomatch g
  hk := ⟨[], List.Perm.refl [], by simp⟩
  hh := RufPasst.hh_von (fun L => by cases L <;> decide)
  hx := RufPasst.hx_von (fun L => by cases L <;> decide)

def gEns_einzahlen : Expr gD (ErgCtx (gD.params g_einzahlen) (gD.erg g_einzahlen)) (vertragVon gD g_einzahlen).ende .bool :=
  (.le (Expr.altSlot (D := gD) GTab.Konto GKontoFeld.stand ((.var (.dort .hier))) gDarf_einzahlen_Konto) (Expr.durch (D := gD) (.var .hier) GTab.Konto rfl GKontoFeld.stand ((.var (.dort .hier))) gDarf_einzahlen_Konto))

def gEns_lies : Expr gD (ErgCtx (gD.params g_lies) (gD.erg g_lies)) (vertragVon gD g_lies).ende .bool :=
  (.eq (.var .hier) (Expr.durch (D := gD) (.var (.dort .hier)) GTab.Konto rfl GKontoFeld.stand ((.var (.dort (.dort .hier)))) gDarf_lies_Konto))

def gBody_einzahlen : Endblock gD (vertragVon gD g_einzahlen) false gCtx_einzahlen gL_einzahlen :=
  (.cons (.assignDurch (.var .hier) GTab.Konto rfl GKontoFeld.stand ((.var (.dort .hier))) (.weiter (by decide) (by decide) (.lit 100)) (by decide) gDarf_einzahlen_Konto) (.cons (.call g_lies (.cons (.ptrOf GTab.Konto 0 rfl false) (.cons (.var (.dort .hier)) .nil)) gHp_einzahlen_lies rfl) (.ret .keine (List.Perm.refl _))))

def gBody_lies : Endblock gD (vertragVon gD g_lies) false gCtx_lies gL_lies :=
  (.ret (.wert (Expr.durch (D := gD) (.var .hier) GTab.Konto rfl GKontoFeld.stand ((.var (.dort .hier))) gDarf_lies_Konto)) (List.Perm.refl _))

def gP : Programm gD where
  invariante := fun i => nomatch i
  requires := fun _ => .wahr
  ensures
    | .einzahlen => gEns_einzahlen
    | .lies => gEns_lies
  rumpf
    | .einzahlen => gBody_einzahlen
    | .lies => gBody_lies

def gFs : List gD.Fn := [g_einzahlen, g_lies]

example : programmImFragmentG gP gFs = true := by decide

example : fussOrtGB gP gFs = true := by decide

-- The lock invariant family `gS` (`SperrInv`, `SperreSem.lean`):
-- lock M: no invariant (arm `fun _ => true`)
def gS : SperrInv gD where
  orte := fun | .M => [.inl GTab.Konto]
  inv := fun | .M => fun _ => true

example : ((gS.orte GLock.M).elem (.inl GTab.Konto) = true) := by decide
example : ((gD.braucht GTab.Konto).elem (Sum.inl GLock.M) = true) := by decide

-- THE USER'S OBLIGATION (stated, not discharged).
--
-- Per function, `KoerperGutS` (the sequential triple against handlers,
-- the caller duty and no `logik` outcome, over `execEndH`) and `InvGutS`
-- (the owed table invariants at a normal return), at EVERY `forever`
-- budget -- a duty at one budget says nothing about a `forever` body --
-- over the lock-invariant family `gS` above and the trivial axiom
-- ensures. Each is a `def` with no proof: the proof is the user's job.
-- The definitions name `KoerperGutS`/`InvGutS` through their imports;
-- their bodies are never copied here.
def einzahlen_pflicht : Prop :=
  ∀ passes, KoerperGutS gP passes (axWahr gD) gS g_einzahlen

def einzahlen_invPflicht : Prop :=
  ∀ passes, InvGutS gP passes (axWahr gD) gS g_einzahlen

def lies_pflicht : Prop :=
  ∀ passes, KoerperGutS gP passes (axWahr gD) gS g_lies

def lies_invPflicht : Prop :=
  ∀ passes, InvGutS gP passes (axWahr gD) gS g_lies

-- The two duties as families, so the closing theorem takes them as one
-- hypothesis each (`∀ f, ...`).
def pflicht : GFn → Prop
  | .einzahlen => einzahlen_pflicht
  | .lies => lies_pflicht

def pflichtInv : GFn → Prop
  | .einzahlen => einzahlen_invPflicht
  | .lies => lies_invPflicht

-- The lock invariants at the start memory (the boot duty).
def startPflicht (sp : Speicher gD) : Prop :=
  ∀ L, gS.inv L sp = true

-- The decidable premises, discharged here so the closing theorem below
-- needs no program fact beyond the user's obligations.
theorem gP_voll : ∀ g : gD.Fn, g ∈ gFs := by
  intro g
  cases g <;> decide

theorem gP_fragment : programmImFragmentG gP gFs = true := by decide

theorem gP_fussS : fussSperreB gP gS gFs = true := by decide

-- THE CLOSING THEOREM: the flagship's conclusion for this program from
-- the user's obligations. The obligations stay open as hypotheses -- that
-- is the point. Apply it once the `..._pflicht` duties above are proved.
theorem gP_ziel (O : Orakel gD) (sp : Speicher gD)
    (init : Faden → Σ f : gD.Fn, Env gD (gD.params f)) (e0 : Ereignis gD)
    (hO : GutO O) (hRL : RegLokal O) (hQ : AxVertragO (axWahr gD) O)
    (hK : ∀ f, pflicht f) (hI : ∀ f, pflichtInv f)
    (hStart : StartGut gP sp init) (hSstart : startPflicht sp)
    (hex : StartExklusiv init) (hS : SperrInvOk gS)
    (hGrund : StartOhneGrund init)
    (passes : Nat) (M : RufMaschineG gD)
    (hr : RufErreichbarG gP O passes (RufStartG gP sp init) M) :
    ((VertragAmOrtG gP M ∧ SperrInvG gS M ∧ KeinLogikHaltG O passes M ∧
      ∀ t : Faden, HeldGenau (M.faeden t).kopf.rest.2.2.1 (offen (M.faeden t).spur) →
        AnPruefungG M t → ∃ M', RufSchrittG gP O passes M t M') ∧
    InvAmOrtG gP M) ∧ StartEndeG gP M ∧ KeinStartGrundG M := by
  have hK' : ∀ (passes : Nat) (f : gD.Fn), KoerperGutS gP passes (axWahr gD) gS f := by
    intro passes f
    cases f
    · exact hK .einzahlen passes
    · exact hK .lies passes
  have hI' : ∀ (passes : Nat) (f : gD.Fn), InvGutS gP passes (axWahr gD) gS f := by
    intro passes f
    cases f
    · exact hI .einzahlen passes
    · exact hI .lies passes
  exact ziel_ort_sperre_ende gP O (axWahr gD) gS gFs sp init e0 hO hRL hQ
    axEnsLokal_wahr hS gP_voll gP_fragment gP_fussS hK' hStart hSstart hex hI' hGrund passes M hr
end G104_referenz_oblig

end Gabbro.Grammatik
