-- GENERATED by `gabbro obligations --g beispiele/108-disjoint-start-locks.gab` (lean-g export plus the stated obligation) -- do not edit.
-- A mechanical export of the checked unit as a G program term
-- (`Programm gD`, the syntax `RufMaschineG.lean` runs).
--
-- NO FORM in G (accepted and dropped, each named): the module
-- wrapper; named constants (inlined at every use); bare carrier
-- widths (a bare word travels as its full range); pointer address
-- spaces; lock hold budgets;
-- the `reads` effects; `costs`; the `by unvisited`/`by consuming`
-- run form, the `decreases` witness and the `touches` clause of a
-- `traverse` (static annotations, like `costs`); `by ops` on a field
-- (a writer discipline the checker holds); `mut` on a `let`;
-- `pub` and `opaque` (both are unit-boundary rules, and
-- `Deklaration` has no boundary -- `pub` added 2026-09-15 after
-- being dropped here and named nowhere, which is the one thing
-- this ledger exists to prevent; `opaque` the same day, when its
-- alias started to travel as its range);
-- `concurrent` (its members travel as the declared starts
-- `gE.starts`; every start is parameterless, its argument list
-- `.nil`); `entry`/`boot` (the vector, the registers, the steps:
-- NO FORM; only the dispatch root travels, as a declared start
-- where exportable).
--
-- table 0: T (count 4), v : 0..4294967295
-- fn read_a (holds; writes)
-- fn read_c (holds; writes)
-- start 0: read_a
-- start 1: read_c
import Grammatik.ZielOrtGeraetSem
import Grammatik.SperreSem
import Grammatik.Zielsatz.Akzeptiert
import Grammatik.Zielsatz.Beweis
import Grammatik.Zielsatz.Spec

namespace Gabbro.Grammatik

namespace G108_disjoint_start_locks_oblig

inductive GTab where
  | T
  deriving DecidableEq

abbrev GLock := Empty

inductive GTFeld where
  | v
  deriving DecidableEq

inductive GFn where
  | read_a
  | read_c
  deriving DecidableEq

def gSig_read_a : Signatur GTab Empty GLock Empty where
  params := []
  erg := some ((.int 0 4294967295))
  gruende := 0
  haelt := []
  boden := none
  schreibt := fun _ => false
  gschreibt := fun e => nomatch e
  konsumiert := []
  produziert := []

def gSig_read_c : Signatur GTab Empty GLock Empty where
  params := []
  erg := some ((.int 0 4294967295))
  gruende := 0
  haelt := []
  boden := none
  schreibt := fun _ => false
  gschreibt := fun e => nomatch e
  konsumiert := []
  produziert := []

abbrev gD : Deklaration where
  Tab := GTab
  decTab := inferInstance
  count := fun | .T => 4
  Feld := fun | .T => GTFeld
  decFeld := fun | .T => inferInstance
  typ := fun | .T, .v => ((.int 0 4294967295))
  erlaubt := fun _ _ _ _ => false
  tabNr := fun | 0 => some GTab.T | _ => none
  Glob := Empty
  decGlob := inferInstance
  gtyp := fun e => nomatch e
  nutzlast := fun e => nomatch e
  atomar := fun e => nomatch e
  geteilt := fun | .T => false
  ggeteilt := fun e => nomatch e
  Lock := GLock
  decLock := inferInstance
  rang := fun L => nomatch L
  maskiert := fun _ => false
  Marke := Empty
  decMarke := inferInstance
  stufen := fun e => nomatch e
  braucht := fun | .T => []
  gbraucht := fun e => nomatch e
  eigner := fun _ => []
  Fn := GFn
  sig := fun | .read_a => 0 | .read_c => 1
  sigNr := fun | 0 => gSig_read_a | 1 => gSig_read_c | _ => gSig_read_c
  eigner_nie_erzeugt := fun _ _ _ _ h => by simp at h
  Inv := Empty
  traeger := fun e => nomatch e
  invs := []
  Ax := Empty
  aparams := fun e => nomatch e
  aerg := fun e => nomatch e
  aschreibt := fun e => nomatch e
  agschreibt := fun e => nomatch e
  Reg := Empty
  rtyp := fun e => nomatch e
  rklasse := fun e => nomatch e
  spiegel := fun e => nomatch e
  rzusage := fun e => nomatch e
  Annahme := Unit
  a10 := ()
  geteilt_bewacht := fun t => by cases t <;> decide
  invarianten_gehalten := fun _ i => nomatch i
  ggeteilt_bewacht := fun e => nomatch e

abbrev gCtx_read_a : Ctx := []
def g_read_a : gD.Fn := GFn.read_a
abbrev gCtx_read_c : Ctx := []
def g_read_c : gD.Fn := GFn.read_c

abbrev gL_read_a : List (Res gD) := []
abbrev gL_read_c : List (Res gD) := []

theorem gDarf_read_a_T : darf gD GTab.T gL_read_a := by unfold darf; decide
theorem gDarf_read_c_T : darf gD GTab.T gL_read_c := by unfold darf; decide

def gBody_read_a : Endblock gD (vertragVon gD g_read_a) false gCtx_read_a gL_read_a :=
  (.ret (.wert (Expr.slot (D := gD) GTab.T GTFeld.v (((.weiter (by decide) (by decide) (.lit 0) : Expr gD gCtx_read_a gL_read_a (.index (gD.count GTab.T))))) gDarf_read_a_T)) (List.Perm.refl _))

def gBody_read_c : Endblock gD (vertragVon gD g_read_c) false gCtx_read_c gL_read_c :=
  (.ret (.wert (Expr.slot (D := gD) GTab.T GTFeld.v (((.weiter (by decide) (by decide) (.lit 1) : Expr gD gCtx_read_c gL_read_c (.index (gD.count GTab.T))))) gDarf_read_c_T)) (List.Perm.refl _))

def gP : Programm gD where
  invariante := fun i => nomatch i
  requires
    | .read_a => .wahr
    | .read_c => .wahr
  ensures
    | .read_a => .wahr
    | .read_c => .wahr
  rumpf
    | .read_a => gBody_read_a
    | .read_c => gBody_read_c

def gFs : List gD.Fn := [g_read_a, g_read_c]

def gLs : List gD.Lock := []

def gCs : List (gD.Tab ⊕ gD.Glob) := [(.inl GTab.T)]

example : programmImFragmentG gP gFs = true := by decide

example : fussOrtGB gP gFs = true := by decide

-- The lock invariant family `gS` (`SperrInv`, `SperreSem.lean`):
def gS : SperrInv gD where
  orte := fun _ => []
  inv := fun _ _ => true


-- The declared initial memory (`Speicher gD`): every slot at zero,
-- every global at its DECLARED initialiser (a `static` names one).
def gSp0 : Speicher gD :=
  ⟨(fun t _ f => match t, f with | .T, .v => ⟨0, by decide, by decide⟩), (fun g => nomatch g)⟩

def gE : Zielsatz.Einheit gD where
  P := gP
  S := gS
  Q := fun _ _ _ => true
  starts := [⟨g_read_a, .nil⟩, ⟨g_read_c, .nil⟩]
  sp0 := gSp0

-- THE USER'S OBLIGATION (stated, not discharged).
--
-- `NutzerPflicht gE`: the bodies' logic (`LogikPflicht` -- per function
-- and at EVERY `forever` budget the body triple with caller duty and no
-- `logik` outcome, owed invariants at value AND reason exits) and the
-- start obligation (`StartPflicht` -- every lock invariant at `gE.sp0`,
-- every declared start's `requires` there with its declared arguments).
-- A `def` with no proof: the proof is the user's job. Stated through the
-- IMPORTED definition `NutzerPflicht`; its body is never copied here.
def nutzerPflicht : Prop := Zielsatz.NutzerPflicht gE

-- The member lists are complete (the `Aufzaehlung`s the goal theorem
-- quantifies over), decided here so the closing theorem below needs no
-- program fact beyond the user's obligation.
theorem gFs_voll : ∀ g : gD.Fn, g ∈ gFs := by
  intro g
  cases g <;> decide

theorem gLs_voll : ∀ L : gD.Lock, L ∈ gLs := by
  intro L
  cases L <;> decide

-- Carriers are tables or globals; the export declares no global
-- (`Glob := Empty`), so the right arm closes by cases. `simp [gCs]`
-- and not `decide`: `DecidableEq (gD.Tab ⊕ gD.Glob)` does not unfold
-- the `gD` declaration during instance search (measured on 104/108:
-- `failed to synthesize Decidable (Sum.inl … ∈ gCs)`), while `simp`
-- rewrites membership over the literal list to constructor equalities.
theorem gCs_voll : ∀ c : gD.Tab ⊕ gD.Glob, c ∈ gCs := by
  intro c
  cases c with
  | inl t => cases t <;> simp [gCs]
  | inr g => cases g <;> simp [gCs]

-- The checker premise, discharged here: the concrete checker of the
-- goal theorem (`akzeptiert_pruefer`) accepts this program on these
-- lists. Where it does not, this `decide` fails -- loudly, not wrongly.
theorem gCheck : akzeptiert_pruefer.akzeptiert gE gFs gLs gCs = true := by decide

-- THE CLOSING THEOREM: the conclusion of `GabbroZiel` for this program,
-- derived from `gabbro_ziel`. The checker premise travels discharged
-- (`gCheck`); the user's obligation stays open as a hypothesis -- that
-- is the point. Apply it once `nutzerPflicht` is proved.
theorem gP_gabbro (hN : Zielsatz.NutzerPflicht gE) (O : Orakel gD)
    (hH : Zielsatz.HardwareAnnahmen O gE.Q) (passes : Nat)
    (sp : Speicher gD.mitRuhe)
    (init : Faden → Σ f : gD.mitRuhe.Fn, Env gD.mitRuhe (gD.mitRuhe.params f))
    (hL : Zielsatz.Laufzeit gE sp init)
    (hK : CloneAssume gD.mitRuhe gE.P.mitRuhe gD.mitRuhe.klon O.mitRuhe passes
      (RufStartG gE.P.mitRuhe sp init)) (M : RufMaschineG gD.mitRuhe)
    (hr : RufErreichbarG gE.P.mitRuhe O.mitRuhe passes (RufStartG gE.P.mitRuhe sp init) M) :
    Zielsatz.Ziel gE.P.mitRuhe gE.S.mitRuhe O.mitRuhe passes (RufStartG gE.P.mitRuhe sp init) M :=
  Zielsatz.gabbro_ziel akzeptiert_pruefer gD gE ⟨gFs, gFs_voll⟩ ⟨gLs, gLs_voll⟩ ⟨gCs, gCs_voll⟩
    gCheck hN O hH passes sp init hL hK M hr
end G108_disjoint_start_locks_oblig

end Gabbro.Grammatik
