/-
  File:    Grammatik/Zertifikate.lean -- GENERATED by `crates/gabbro-check/tests/zertifikate.rs`
           (do not edit; `GABBRO_ZERTIFIKATE=schreiben cargo test --test zertifikate`).
  Content: one import per CERTIFIED corpus program of `Zertifikat/REGISTER.txt`. Each imported
           module is the byte-exact output of `gabbro obligations --g <program>`: the exported
           unit `gE`, the checker premise decided (`gCheck`, `by decide`) and the goal theorem
           instantiated (`gP_gabbro`). Importing them here puts every one into `lake build`, so
           an exported program the Lean Bool `Akzeptiert` refuses turns the build RED.
-/
import Grammatik.GenOblig104
import Grammatik.GenOblig108
import Grammatik.Zertifikat.G109_lockfree_entry_roots
import Grammatik.Zertifikat.G118_sperrinvariante_erhaltung
import Grammatik.Zertifikat.G119_sperrinvariante_bloecke
import Grammatik.Zertifikat.G120_tagged_construction
import Grammatik.Zertifikat.G121_tagged_static_init
import Grammatik.Zertifikat.G124_two_threads_private
import Grammatik.Zertifikat.G130_derived_contract_pure
import Grammatik.Zertifikat.G157_worker_pool
import Grammatik.Zertifikat.G15_own_traegt_beide_rechte
import Grammatik.Zertifikat.G16_by_ops_am_feld
import Grammatik.Zertifikat.G219_unaeres_minus
import Grammatik.Zertifikat.G34_markierter_wert
import Grammatik.Zertifikat.G414_tabellenspeicher_heisst_so
import Grammatik.Zertifikat.G59_eintritt_nimmt_maskierte_sperre
import Grammatik.Zertifikat.G62_grenzwort_im_ausdruck
import Grammatik.Zertifikat.G69_integer_conversion
import Grammatik.Zertifikat.G700_lesen_ohne_klausel
import Grammatik.Zertifikat.G701_rein_ohne_klausel
import Grammatik.Zertifikat.G719_lock_taken_nowhere
import Grammatik.Zertifikat.G73_sugar_widths
