#check @Int.tdiv_nonneg
#check @Int.tdiv_le_self
#check @Int.tdiv_eq_ediv_of_nonneg
#check @Int.ediv_le_self
#check @Int.tmod_nonneg
#check @Int.tmod_lt_of_pos
#check @Int.ediv_nonneg
#check @Int.emod_nonneg
#check @Int.emod_lt_of_pos
#check @Int.tdiv_eq_ediv
#check @Int.tmod_eq_emod
#check @Int.lt_tdiv_add_one_mul_self
#check @Int.tdiv_le_of_le_mul
#check @Int.ediv_le_of_le_mul
#check @Int.le_ediv_of_mul_le
