#!/usr/bin/env bash
# **Der Differenztest -- die erste JA-Aussage dieses Ordners.**
#
# Bis zum 2026-08-17 war die Emissionsflaeche die groesste unbeschaedigbare Flaeche des
# Projekts: `mutiere-pruefer.py` wies sie mit 0 Mutationen aus, und *was 0 Mutationen hat,
# ist nicht gedeckt, sondern unbeschaedigbar*.
#
# Dieser Waechter schliesst sie fuer EIN Fragment, nicht fuer zehn:
#
#     .gab  ->  gabbro emit  ->  C  ->  cc -Werror  ->  ausgefuehrt  ->  Ergebnis verglichen
#
# **Jede Stufe muss halten, und die letzte ist die, auf die es ankommt.** Ein Erzeuger, der
# uebersetzbares C liefert, das etwas anderes rechnet, ist schlimmer als einer, der nichts
# liefert -- er sieht aus wie ein Ergebnis.
set -euo pipefail
W="$(cd "$(dirname "$0")" && pwd)"
QUELLE="$W/beispiele/16-by-ops-am-feld.gab"
ARB="$(mktemp -d)"
trap 'rm -rf "$ARB"' EXIT

# **W1: eine uebersprungene Probe senkt die Zahl, sie laesst sie nicht unberuehrt.**
# Kein `cc` heisst NICHT „bestanden, uebersprungen" -- es heisst, dass dieser Waechter
# nichts gemessen hat, und das ist ein Rot.
if ! command -v cc > /dev/null; then
    echo "== EMISSION: KEIN CC -- der Differenztest hat NICHTS gemessen =="
    echo "  Ein fehlendes Werkzeug ist kein bestandener Test. W1: der Ausfall senkt die"
    echo "  Zahl, er laesst sie nicht unberuehrt."
    exit 1
fi

echo "== Differenztest: $(basename "$QUELLE") =="

# 1. Erzeugen. Der Pruefer laeuft davor -- C aus einem Baum zu erzeugen, den die Paesse
#    nicht angenommen haben, waere C fuer ein Programm, das Gabbro ablehnt.
if ! cargo run -q --manifest-path "$W/Cargo.toml" --bin gabbro -- emit "$QUELLE" > "$ARB/erzeugt.c" 2> "$ARB/fehler"; then
    echo "  1. erzeugen:   GESCHEITERT"
    cat "$ARB/fehler"
    exit 1
fi
echo "  1. erzeugen:   ok ($(grep -c '' "$ARB/erzeugt.c") Zeilen C)"

# 2. Der Lizenzhinweis. `LIZENZ-ZUSATZ.md` knuepft die zusaetzliche Erlaubnis an ihn --
#    eine Bedingung, die niemand prueft, ist eine Bitte.
if ! grep -q "Generated by Gabbro" "$ARB/erzeugt.c"; then
    echo "  2. Lizenz:     FEHLT -- die Bedingung aus LIZENZ-ZUSATZ.md steht nicht im C"
    exit 1
fi
echo "  2. Lizenz:     ok (Hinweis im Kopf)"

# 3. Uebersetzen, und zwar streng. Eine Warnung im erzeugten C ist ein Befund ueber den
#    Erzeuger, nicht ueber den Anwender -- er hat die Zeile nicht geschrieben.
cat > "$ARB/treiber.c" <<'ENDE'
#include <stdio.h>
#include "erzeugt.c"
int main(void) {
    Objekte o = {0};
    o.slots[3].zaehler = 42;
    belegen(&o, 3);
    printf("%u %d %d %d\n",
           stand(&o, 3),
           (int)o.slots[3].benutzt,
           (int)(sizeof(o.slots) / sizeof(o.slots[0])),
           (int)o.slots[0].benutzt);
    return 0;
}
ENDE
if ! cc -std=c11 -Wall -Wextra -Werror -I"$ARB" -o "$ARB/probe" "$ARB/treiber.c" 2> "$ARB/ccfehler"; then
    echo "  3. cc -Werror: GESCHEITERT"
    head -20 "$ARB/ccfehler"
    exit 1
fi
echo "  3. cc -Werror: ok (keine Warnung)"

# 4. Ausfuehren und VERGLEICHEN. Das ist die Stufe, die die anderen drei erst zu einer
#    Aussage macht.
#
#    Erwartet:  42  -- `stand` liefert, was geschrieben wurde
#                1  -- `belegen` setzt `benutzt`
#                8  -- das Feld hat die Slots aus `count N`, N = 8
#                0  -- und Slot 0 ist unberuehrt: die Operation trifft EINEN Slot
ERWARTET="42 1 8 0"
IST="$("$ARB/probe")"
if [ "$IST" != "$ERWARTET" ]; then
    echo "  4. Ergebnis:   FALSCH"
    echo "     erwartet:   $ERWARTET"
    echo "     bekommen:   $IST"
    exit 1
fi
echo "  4. Ergebnis:   ok ($IST)"

# **Die Sprechprobe in die andere Richtung.** Ein Differenztest, der nicht rot werden kann,
# misst nichts -- dieselbe Regel, mit der jede Messung dieses Ordners anfaengt (R14).
sed 's/\.benutzt = true/.benutzt = false/' "$ARB/erzeugt.c" > "$ARB/gift.c"
cp "$ARB/treiber.c" "$ARB/gifttreiber.c"
sed -i 's/erzeugt\.c/gift.c/' "$ARB/gifttreiber.c"
cc -std=c11 -w -I"$ARB" -o "$ARB/giftprobe" "$ARB/gifttreiber.c"
if [ "$("$ARB/giftprobe")" = "$ERWARTET" ]; then
    echo "  5. Sprechprobe: UEBERSEHEN -- ein veraendertes Erzeugnis liefert dasselbe?"
    exit 1
fi
echo "  5. Sprechprobe: ok (verfaelschtes C faellt)"

echo "== EMISSION: ALL PASS -- 1 Fragment durchgestochen =="
echo "  Und was das NICHT heisst: neun weitere Fragmente sind ungeprueft, der Erzeuger"
echo '  deckt genau die Formen dieser einen Datei, und C001 weigert sich fuer jede'
echo "  andere. Eine Ja-Aussage ueber ein Fragment ist keine ueber die Sprache."
