#!/usr/bin/env bash
# **Der Differenztest -- die JA-Aussagen dieses Ordners.**
#
# Bis zum 2026-08-17 war die Emissionsflaeche die groesste unbeschaedigbare Flaeche des
# Projekts: `mutiere-pruefer.py` wies sie mit 0 Mutationen aus, und *was 0 Mutationen hat,
# ist nicht gedeckt, sondern unbeschaedigbar*.
#
# Dieser Waechter schliesst sie fuer SIEBEN Uebersetzungseinheiten, nicht fuer zehn:
#
#     .gab  ->  gabbro emit  ->  C  ->  cc -Werror  ->  ausgefuehrt  ->  Ergebnis verglichen
#
# **Jede Stufe muss halten, und die letzte ist die, auf die es ankommt.** Ein Erzeuger, der
# uebersetzbares C liefert, das etwas anderes rechnet, ist schlimmer als einer, der nichts
# liefert -- er sieht aus wie ein Ergebnis.
#
#   1. `beispiele/16-by-ops-am-feld.gab` -- ein BEISPIEL. Tabelle, `count`, Bereichstypen.
#   2. `dokumente/FRAGMENTE.md` F7 -- ein FRAGMENT, und zwar aus dem eingefrorenen Korpus
#      geschnitten, nicht aus einer Kopie. Es misst die GEISTLOESCHUNG: `BootPhase` ist ein
#      `linear ghost type`, und die Frage, die dieser Lauf beantwortet, lautet **was kostet
#      die Phasendisziplin zur Laufzeit** -- Antwort: nichts.
set -euo pipefail
W="$(cd "$(dirname "$0")" && pwd)"
ARB="$(mktemp -d)"
trap 'rm -rf "$ARB"' EXIT

# **W1: eine uebersprungene Probe senkt die Zahl, sie laesst sie nicht unberuehrt.**
# Kein `cc` heisst NICHT „bestanden, uebersprungen" -- es heisst, dass dieser Waechter
# nichts gemessen hat, und das ist ein Rot.
if ! command -v cc > /dev/null; then
    echo "== EMISSION: KEIN CC -- der Differenztest hat NICHTS gemessen =="
    echo "  Ein fehlendes Werkzeug ist kein bestandener Test. W1: der Ausfall senkt die"
    echo "  Zahl, er laesst sie nicht unberuehrt."
    exit 1
fi

# Schneidet den ```gabbro-Block, der eine gegebene Zeile enthaelt, aus einer Markdown-Datei.
# **Aus dem Korpus, nicht aus einer Kopie** -- sonst misst der Waechter seine eigene Ablage.
schneide() {
    awk -v marke="$2" '
        /^```gabbro/ { drin=1; puffer=""; next }
        drin && /^```/ { if (puffer ~ marke) { printf "%s", puffer; exit } drin=0; next }
        drin { puffer = puffer $0 "\n" }
    ' "$1"
}

lauf() {          # $1 Name  $2 Quelle  $3 Treiber  $4 Erwartet  $5 Gift-sed  $6 Zeugnis
    local name="$1" quelle="$2" treiber="$3" erwartet="$4" gift="$5" zeugnis="$6"
    local c="$ARB/$name.c"
    echo "== Differenztest: $name =="

    # 1. Erzeugen. Der Pruefer laeuft davor -- C aus einem Baum zu erzeugen, den die Paesse
    #    nicht angenommen haben, waere C fuer ein Programm, das Gabbro ablehnt.
    if ! cargo run -q --manifest-path "$W/Cargo.toml" --bin gabbro -- emit "$quelle" \
            > "$c" 2> "$ARB/fehler"; then
        echo "  1. erzeugen:   GESCHEITERT"; cat "$ARB/fehler"; exit 1
    fi
    echo "  1. erzeugen:   ok ($(grep -c '' "$c") Zeilen C)"

    # 2. Der Lizenzhinweis. `LIZENZ-ZUSATZ.md` knuepft die zusaetzliche Erlaubnis an ihn --
    #    eine Bedingung, die niemand prueft, ist eine Bitte.
    if ! grep -q "Generated by Gabbro" "$c"; then
        echo "  2. Lizenz:     FEHLT -- die Bedingung aus LIZENZ-ZUSATZ.md steht nicht im C"; exit 1
    fi
    echo "  2. Lizenz:     ok (Hinweis im Kopf)"

    # 3. Uebersetzen, und zwar streng. Eine Warnung im erzeugten C ist ein Befund ueber den
    #    Erzeuger, nicht ueber den Anwender -- er hat die Zeile nicht geschrieben.
    printf '%s' "$treiber" | sed "s/@ERZEUGT@/$name.c/" > "$ARB/$name-treiber.c"
    if ! cc -std=c11 -Wall -Wextra -Werror -I"$ARB" -o "$ARB/$name-probe" \
            "$ARB/$name-treiber.c" 2> "$ARB/ccfehler"; then
        echo "  3. cc -Werror: GESCHEITERT"; head -20 "$ARB/ccfehler"; exit 1
    fi
    echo "  3. cc -Werror: ok (keine Warnung)"

    # 4. Ausfuehren und VERGLEICHEN. Das ist die Stufe, die die anderen drei erst zu einer
    #    Aussage macht.
    local ist; ist="$("$ARB/$name-probe")"
    if [ "$ist" != "$erwartet" ]; then
        echo "  4. Ergebnis:   FALSCH"
        echo "     erwartet:   $erwartet"
        echo "     bekommen:   $ist"
        exit 1
    fi
    echo "  4. Ergebnis:   ok ($ist)"

    # 5. **Das Uebersetzungszeugnis** -- K100.4, Weg (b). Die Differenztests messen EIN
    #    Ergebnis; das Zeugnis zaehlt auf, worauf die Uebersetzung ruht. Die Bedingung hier ist
    #    die Kreuzprobe: **was der Erzeuger absenkt, muss das Zeugnis einordnen.** Steht eine
    #    Form in keiner Einordnung, hat der Erzeuger etwas abgesenkt und es niemandem gesagt.
    if ! cargo run -q --manifest-path "$W/Cargo.toml" --bin gabbro -- zeugnis "$quelle" \
            > "$ARB/$name.zeugnis" 2> "$ARB/zfehler"; then
        echo "  5. Zeugnis:    GESCHEITERT"; cat "$ARB/zfehler"; exit 1
    fi
    if grep -q "UNZUGEORDNET" "$ARB/$name.zeugnis"; then
        echo "  5. Zeugnis:    UNZUGEORDNET -- der Erzeuger senkt eine Form ab, die keine"
        echo "                 Einordnung kennt. Die Vertrauensflaeche ist groesser als gebucht."
        grep -A3 "UNZUGEORDNET" "$ARB/$name.zeugnis"; exit 1
    fi
    # **Die Zahl wird ABGELESEN, nicht nachgezaehlt** (W2). Ein `grep -c` ueber der
    # Schablonenliste zaehlte hier erst die Zeile „keine. Diese Einheit nimmt nichts an" mit --
    # sie faengt genauso mit fuenf Leerzeichen und einem Punkt an. *Eine zweite Zaehlung neben
    # einer vorhandenen ist eine Gelegenheit, sich zu widersprechen.*
    #    **Und der Befund wird VERGLICHEN, nicht gedruckt.** Ein Zeugnis, das man nur ansieht,
    #    ist ein Bericht; eines, gegen das ein Tor steht, ist eine Buchung. Wer eine Form
    #    umklassifiziert -- eine Schablone zur direkten Absenkung erklaert -- faellt hier.
    local zist; zist="$(sed -n 's/^     \(.*Schablonen.*\)$/\1/p' "$ARB/$name.zeugnis")"
    if [ "$zist" != "$zeugnis" ]; then
        echo "  5. Zeugnis:    ANDERS ALS GEBUCHT"
        echo "     gebucht:    $zeugnis"
        echo "     bekommen:   $zist"
        exit 1
    fi
    echo "  5. Zeugnis:    ok ($zist)"

    # **Die Sprechprobe in die andere Richtung.** Ein Differenztest, der nicht rot werden kann,
    # misst nichts -- dieselbe Regel, mit der jede Messung dieses Ordners anfaengt (R14).
    sed "$gift" "$c" > "$ARB/$name-gift.c"
    printf '%s' "$treiber" | sed "s/@ERZEUGT@/$name-gift.c/" > "$ARB/$name-gifttreiber.c"
    cc -std=c11 -w -I"$ARB" -o "$ARB/$name-giftprobe" "$ARB/$name-gifttreiber.c"
    if [ "$("$ARB/$name-giftprobe")" = "$erwartet" ]; then
        echo "  6. Sprechprobe: UEBERSEHEN -- ein veraendertes Erzeugnis liefert dasselbe?"; exit 1
    fi
    echo "  6. Sprechprobe: ok (verfaelschtes C faellt)"
}

# -- 1. Das Beispiel: eine Tabelle, ein Feld, eine erzeugte Operation --------------------
#
#    Erwartet:  42  -- `stand` liefert, was geschrieben wurde
#                1  -- `belegen` setzt `benutzt`
#                8  -- das Feld hat die Slots aus `count N`, N = 8
#                0  -- und Slot 0 ist unberuehrt: die Operation trifft EINEN Slot
TREIBER16='#include <stdio.h>
#include "@ERZEUGT@"
int main(void) {
    Objekte o = {0};
    o.slots[3].zaehler = 42;
    belegen(&o, 3);
    printf("%u %d %d %d\n",
           stand(&o, 3),
           (int)o.slots[3].benutzt,
           (int)(sizeof(o.slots) / sizeof(o.slots[0])),
           (int)o.slots[0].benutzt);
    return 0;
}
'
lauf "beispiel16" "$W/beispiele/16-by-ops-am-feld.gab" "$TREIBER16" "42 1 8 0" \
     's/\.benutzt = true/.benutzt = false/' \
     "0 Annahmen, 1 Schablonen (0 davon UNBEWIESEN), 5 direkte Formen, 0 fremde Ruempfe (0 sprechen ihre Pflicht aus)"

# -- 2. Das Fragment: die Geistloeschung -------------------------------------------------
#
# **Die Frage, die dieser Lauf beantwortet:** `BootPhase` ist ein `linear ghost type`, der
# durch sechs Bootschritte gefaedelt und am Ende verbraucht wird. Er traegt das ganze
# Sicherheitsargument des Fragments -- und er darf zur Laufzeit **nicht existieren**.
#
# Die Loeschung muss an DREI Orten gleichzeitig halten, und zwei davon sind still, wenn sie
# ausfallen: die Signatur (`void mmu_an(void)`, nicht `void mmu_an(BootPhase)`), der Rufort
# (`mmu_an()`, nicht `mmu_an(p)`) und die `let`-Bindung (`mmu_an();`, nicht
# `void p1 = mmu_an();`). Faellt die dritte falsch aus -- naemlich indem die ganze Anweisung
# verschwindet --, uebersetzt das C und der Bootschritt findet **nicht statt**.
#
# Genau das misst die Erwartung: **sechs Schritte, in dieser Reihenfolge, je genau einmal.**
schneide "$W/dokumente/FRAGMENTE.md" "module caprock::bringup" > "$ARB/f7.gab"
if ! grep -q "linear ghost type BootPhase" "$ARB/f7.gab"; then
    echo "== EMISSION: F7 NICHT GESCHNITTEN -- der Waechter misst seine eigene Ablage =="
    exit 1
fi
TREIBER7='#include <stdio.h>
static int spur[8];
static int n;
void mmu_an(void)               { spur[n++] = 1; }
void cap_tabellen(void)         { spur[n++] = 2; }
void ipc_tabellen(void)         { spur[n++] = 3; }
void autoritaet_melden(void)    { spur[n++] = 4; }
void verifizierer_starten(void) { spur[n++] = 5; }
void root_task_starten(void)    { spur[n++] = 6; }
#include "@ERZEUGT@"
int main(void) {
    hochlauf();
    for (int i = 0; i < n; i++) printf("%d", spur[i]);
    printf("\n");
    return 0;
}
'
lauf "fragment7" "$ARB/f7.gab" "$TREIBER7" "123456" \
     's/    ipc_tabellen();/    \/* geloescht *\//' \
     "0 Annahmen, 0 Schablonen (0 davon UNBEWIESEN), 3 direkte Formen, 7 fremde Ruempfe (0 sprechen ihre Pflicht aus)"

# -- 3. Das Fragment F8: die Sperre wird auf JEDEM Pfad gegeben --------------------------
#
# **Der Rumpf von `toeten` kehrt aus dem `locks`-Block heraus zurueck, und zwar aus beiden
# Zweigen.** Ein Erzeuger, der die Freigabe nur ans Blockende schreibt, laesst die Sperre auf
# beiden Wegen stehen -- und das C uebersetzt. *Woertlich die Klasse, die C8 bezahlt hat: ein
# neuer Abweispfad erbt die Aufraeumpflicht des alten nicht.* Hier erbt er sie, weil nicht der
# Schreiber sie ausgibt.
#
# Zweitens misst dieser Lauf den SONDERWERT: `aufloesen` liefert `option index into Laufliste`,
# und `Laufliste_NONE` ist die Laenge selbst -- der eine Wert, den ein gueltiger Index nach
# `count N` und M1 nie annimmt.
schneide "$W/dokumente/FRAGMENTE.md" "module caprock::sched" > "$ARB/f8.gab"
if ! grep -q "locks SCHEDS" "$ARB/f8.gab"; then
    echo "== EMISSION: F8 NICHT GESCHNITTEN =="; exit 1
fi
TREIBER8='#include <stdio.h>
static int genommen, gegeben;
static unsigned antwort;
void SCHEDS_nimm(void)         { genommen++; }
void SCHEDS_gib(void)          { gegeben++; }
void SCHEDS_nimm_geteilt(void) { genommen++; }
void SCHEDS_gib_geteilt(void)  { gegeben++; }
#include "@ERZEUGT@"
uint32_t aufloesen(const Laufliste *l, uint32_t t) { (void)l; (void)t; return antwort; }
int main(void) {
    static Laufliste l;
    l.slots[3].belegt = true;
    antwort = 3; genommen = 0; gegeben = 0;
    int a = toeten(&l, 7, 0);
    printf("%d %d %d %d", a, genommen, gegeben, (int)l.slots[3].belegt);

    l.slots[3].belegt = true;
    antwort = Laufliste_NONE; genommen = 0; gegeben = 0;
    int b = toeten(&l, 7, 0);
    printf(" %d %d %d %d\n", b, genommen, gegeben, (int)l.slots[3].belegt);
    return 0;
}
'
#    Erwartet, Fall A (`aufloesen` findet den Faden):
#      1  -- `toeten` meldet Erfolg
#      1  -- die Sperre wurde einmal genommen
#      1  -- **und einmal gegeben, obwohl der Weg mit `return` aus dem Block springt**
#      0  -- der Slot ist geraeumt
#    Fall B (`aufloesen` liefert `None`):
#      0  -- kein Erfolg
#      1 1 -- genommen und gegeben, auch auf dem ANDEREN Rueckkehrpfad
#      1  -- und der Slot ist unberuehrt: der None-Zweig fasst nichts an
lauf "fragment8" "$ARB/f8.gab" "$TREIBER8" "1 1 1 0 0 1 1 1" \
     '0,/^                SCHEDS_gib();$/s///' \
     "0 Annahmen, 3 Schablonen (2 davon UNBEWIESEN), 5 direkte Formen, 2 fremde Ruempfe (0 sprechen ihre Pflicht aus)"

# -- 4. Das Fragment F10: das Format und das Operationsbudget ----------------------------
#
# **Zwei Absenkungen, die keine Uebersetzungen sind.**
#
# `format` wird KEIN C-Verbund -- Fuellung und Bitreihenfolge sind in C implementierungsoffen,
# und ein Format ist genau eine Zusage ueber BYTES. Es wird ein Bytezeiger mit
# Zugriffsfunktionen in der ERKLAERTEN Reihenfolge, plus EINER Gueltigkeitsfunktion aus den
# `where`-Klauseln. *Der gemessene Bestand schreibt genau das von Hand: `be32(data, n)?`.*
#
# `retry ... bounded 65536 ops` ist ein OPERATIONSBUDGET, kein Schleifenzaehler. Geteilt durch
# die Kosten eines Durchgangs (der Kostenpass rechnet sie) ergibt das 21845 Durchgaenge.
schneide "$W/dokumente/FRAGMENTE.md" "module caprock::dtb" > "$ARB/f10.gab"
if ! grep -q "format DtbKopf" "$ARB/f10.gab"; then
    echo "== EMISSION: F10 NICHT GESCHNITTEN =="; exit 1
fi
TREIBER10='#include <stdio.h>
#include <stdlib.h>
#include "@ERZEUGT@"
static int rufe;
uint32_t naechstes_token(const DtbKopf *k, uint32_t pos) { (void)k; (void)pos; rufe++; return 1; }
_Noreturn void baum_unlesbar(void) { printf(" UEBERLAUF"); exit(0); }
int main(void) {
    static const uint8_t gut[16]    = { 0xd0,0x0d,0xfe,0xed, 0,0,0,64, 0,0,0,40, 0,0,0,50 };
    static const uint8_t falsch[16] = { 0xde,0xad,0xbe,0xef, 0,0,0,64, 0,0,0,40, 0,0,0,50 };
    DtbKopf a = { gut, 64 }, b = { falsch, 64 }, c = { gut, 8 }, d = { gut, 20 };
    rufe = 0;
    unsigned n = kerne_zaehlen(&a);
    printf("%d %d %d %d %u %d\n",
           (int)DtbKopf_gueltig(&a), (int)DtbKopf_gueltig(&b),
           (int)DtbKopf_gueltig(&c), (int)DtbKopf_gueltig(&d), n, rufe);
    return 0;
}
'
#    Erwartet:
#      1  -- der gute Kopf ist gueltig: Magie stimmt, beide Versaetze liegen im Puffer
#      0  -- **die Magie ist die Zusage, und `endian big` ist der Grund**: dieselben Bytes
#            klein gelesen ergaeben etwas anderes
#      0  -- ein Puffer kuerzer als der Kopf faellt an `v->len < 16`
#      0  -- und DAS ist die eigentliche `where`-Klausel: der Kopf passt, aber `off_struct`
#            zeigt hinter den Puffer. *Danach braucht kein Zugriff mehr eine Laengenpruefung.*
#      0  -- `kerne_zaehlen` liefert seine Null
#     65  -- **die Durchgaenge, und die Zahl ist vorhergesagt worden**: `narrow tiefe to
#            0 ..< 64` traegt 64 Durchgaenge, der 65. Test faellt. Nicht 21845 -- das
#            Operationsbudget ist die WEITERE Schranke, nicht die engere
#    **Die Sprechprobe dreht die Bytereihenfolge im LESER**, nicht seinen Namen. Der erste
#    Versuch ersetzte `gabbro_be32` durch `gabbro_le32` -- und traf damit Definition UND
#    Rufort, benannte die Funktion also bloss um. *Ein Gift, das nichts aendert, ist keines,
#    und die Probe hat es gemeldet.*
lauf "fragment10" "$ARB/f10.gab" "$TREIBER10" "1 0 0 0 0 65" \
     's/(uint32_t)p\[0\] << 24/(uint32_t)p[3] << 24/' \
     "1 Annahmen, 2 Schablonen (0 davon UNBEWIESEN), 7 direkte Formen, 2 fremde Ruempfe (0 sprechen ihre Pflicht aus)"

# -- 5. Die Traversierung: die Schleife OHNE Laufzeitzaehler ----------------------------
#
# **Der Unterschied zu `retry` steht jetzt im C nebeneinander:**
#
#     traverse  ->  for (uint32_t i = 0; i < sizeof(...)/sizeof(...[0]); i++)
#     retry     ->  while (!(...)) { if (n >= SCHRANKE) { ausgang(); } n++; ... }
#
# Die Laufgrenze hier, der Wachhund dort -- und der Grund ist die Domaene: `slots of` ist
# durch Konstruktion endlich, die Bedingung eines `retry` haengt von der Welt ab. *Genau
# darum verlangt die Grammatik dort ein `on_exceeded` und hier keines.*
TREIBER19='#include <stdio.h>
#include "@ERZEUGT@"
int main(void) {
    static Werte w;
    for (unsigned i = 0; i < 16; i++) w.slots[i].aktiv = (i % 3 == 0);
    unsigned vorher = aktive_zaehlen(&w);
    aktive_loeschen(&w);
    unsigned nachher = aktive_zaehlen(&w);
    printf("%d %u %u %d\n",
           (int)(sizeof(w.slots) / sizeof(w.slots[0])), vorher, nachher,
           (int)w.slots[15].aktiv);
    return 0;
}
'
#    Erwartet:
#     16  -- die Domaenenschranke kommt aus `count NSLOTS`, nicht aus dem Rumpf
#      6  -- Slots 0,3,6,9,12,15 sind aktiv: **jeder Slot GENAU EINMAL besucht**. Eine
#            Traversierung, die einen ausliesse, zaehlte weniger; eine, die doppelt liefe,
#            mehr -- und der Zaehler ist auf `0 ..< 16` verengt, koennte also gar nicht ueber
#            16 hinaus
#      0  -- nach dem Loeschen ist keiner mehr aktiv
#      0  -- und der LETZTE Slot ist mitgeloescht: die Grenze ist `< n`, nicht `< n-1`
lauf "beispiel19" "$W/beispiele/19-traversierung.gab" "$TREIBER19" "16 6 0 0" \
     's/; i++)/; i += 2)/' \
     "0 Annahmen, 2 Schablonen (0 davon UNBEWIESEN), 8 direkte Formen, 0 fremde Ruempfe (0 sprechen ihre Pflicht aus)"

# -- 6. Das Geraet: ein Register ist KEIN Feld ------------------------------------------
#
# Ein C-Verbund haette dieselbe Schwaeche wie beim `format`: die Versaetze stehen in der
# Deklaration, die Fuellung eines `struct` bestimmt der Uebersetzer. Dazu kommt hier, dass ein
# Registerzugriff **nicht wegoptimiert werden darf** -- `volatile` ist die eine Stelle, an der
# die Absenkung dem C-Uebersetzer etwas VERBIETEN muss.
#
#     r.AVAIL_IDX += 1;   ->   (*(volatile uint16_t *)(r->basis + 258)) += 1;
#
# **Und der Umlauf ist erklaert, nicht geduldet** («B32»): `u16 wrapping` senkt zu `uint16_t`
# ab, dessen Umlauf C definiert. Bei 0xffff geht es auf 0 -- genau das, was virtio meint.
TREIBER12='#include <stdio.h>
#include "@ERZEUGT@"
static uint8_t bank[512];
int main(void) {
    Ring r = { bank };
    *(volatile uint16_t *)(bank + 258) = 7;
    *(volatile uint16_t *)(bank + 260) = 64;
    vorruecken(&r);
    unsigned a = *(volatile uint16_t *)(bank + 258);
    *(volatile uint16_t *)(bank + 258) = 0xffff;
    vorruecken(&r);
    unsigned b = *(volatile uint16_t *)(bank + 258);
    unsigned c = *(volatile uint16_t *)(bank + 260);
    printf("%u %u %u %d\n", a, b, c, (int)sizeof(Ring));
    return 0;
}
'
#    Erwartet:
#      8  -- 7 + 1: der Zugriff trifft Versatz 0x102 und nichts daneben
#      0  -- **0xffff + 1 laeuft um**, und zwar mit Absicht: `u16 wrapping` («B32»)
#     64  -- das NACHBARREGISTER bei 0x104 ist unberuehrt geblieben
#      8  -- der Griff ist ein Zeiger, kein abgebildeter Registersatz: kein `struct` mit
#            Fuellung, ueber die der Uebersetzer entscheidet
lauf "beispiel12" "$W/beispiele/12-umlaufendes-register.gab" "$TREIBER12" "8 0 64 8" \
     's/+ 258/+ 260/' \
     "0 Annahmen, 1 Schablonen (0 davon UNBEWIESEN), 2 direkte Formen, 0 fremde Ruempfe (0 sprechen ihre Pflicht aus)"

# -- 7. FALLE 4: `mirrors`, und der Test misst genau die bezahlte Falle -----------------
#
# **Die Falle, in einem Satz:** `GCMD` ist kein Lese-Aendere-Schreib-Register. Wer ein Bit
# setzt, schreibt das GANZE Wort -- und jedes Zustandsbit, das er nicht mitschreibt, ist
# danach geloescht. Die mitzuschreibenden Bits stehen nicht in GCMD (es ist `class w`,
# unlesbar), sondern im Statusregister daneben.
#
#     mirrors GCMD from GSTS;   ->   write(GCMD, (read(GSTS) & ~geaendert) | neu)
#
# *Eine Zeile je Geraet, und sie ersetzt `GCMD_STATE_MASK` samt der Kommentarwand.*
TREIBER20='#include <stdio.h>
#include "@ERZEUGT@"
static uint8_t mmio[64];
#define GCMD (*(volatile uint32_t *)(mmio + 0x18))
#define GSTS (*(volatile uint32_t *)(mmio + 0x1c))
int main(void) {
    Einheit e = { mmio };
    /* Das Geraet meldet: die Uebersetzung laeuft bereits (TES, Bit 31). */
    GSTS = 1u << 31;
    GCMD = 0;
    Einheit_setze_rtp(&e);
    unsigned nach_rtp = GCMD;

    /* Und jetzt meldet es zusaetzlich RTPS (Bit 30). */
    GSTS = (1u << 31) | (1u << 30);
    GCMD = 0;
    Einheit_scharf_te(&e);
    unsigned nach_te = GCMD;

    printf("%d %d %d %d\n",
           !!(nach_rtp & (1u << 30)),   /* SRTP gesetzt */
           !!(nach_rtp & (1u << 31)),   /* TES MITGESCHRIEBEN -- das ist die Falle */
           !!(nach_te  & (1u << 31)),   /* TE gesetzt */
           !!(nach_te  & (1u << 30)));  /* RTPS mitgeschrieben */
    return 0;
}
'
#    Erwartet:  1 1 1 1
#      Die ERSTE und die DRITTE Zahl sagen, dass der Uebergang tut, was er sagt.
#      **Die ZWEITE und die VIERTE sind die Falle.** Ohne `mirrors` waeren sie 0: das
#      Zustandsbit, das niemand mitgeschrieben hat, waere geloescht -- und die Einheit haette
#      die Uebersetzung mitten im Betrieb abgeschaltet. *Genau dafuer hat der Bestand eine
#      Maske und eine Kommentarwand; hier ist es eine Zeile.*
lauf "beispiel20" "$W/beispiele/20-falle-vier.gab" "$TREIBER20" "1 1 1 1" \
     's/(_s \& /(0*_s \& /' \
     "0 Annahmen, 2 Schablonen (0 davon UNBEWIESEN), 1 direkte Formen, 0 fremde Ruempfe (0 sprechen ihre Pflicht aus)"


# -- 8. «B7»: der Verbundwert, und der Test misst genau das, wofuer die Marken Pflicht sind --
#
# **Die Entscheidung, in einem Satz:** ein geschweiftes `P { a: 1 }` waere die erste
# Ausdrucksform gewesen, die mit `{` weitergeht -- an 76 Korpusstellen folgt ein `{` direkt
# auf einen Ausdruck, und ein falsch gesetzter Kontextschalter verliest sie ALLE still.
# Gewaehlt ist darum der markierte Ruf `P(a: …, b: …)`.
#
# **Und die Marken sind nicht Zierde.** `Completion` hat zwei `u32`-Felder; eine Reihung
# `Completion(k, n)` liesse sich vertauschen, ohne dass ein Typ dagegen spricht. Der Erzeuger
# uebersetzt die Marken zu BENANNTEN Bestimmern -- `(Completion){ .id = k, .len = n }` --,
# und damit steht die bewiesene Zusage `map fst zs = fs` im Erzeugnis statt nur im Pruefer.
TREIBER21='#include <stdio.h>
#include "@ERZEUGT@"
int main(void) {
    Completion c = fertig(5, 300);
    Marke m = markiere(9);
    printf("%u %u %u %u %d\n", c.id, c.len, laenge_von(5), m.wer, m.fertig ? 1 : 0);
    return 0;
}
'
#    Erwartet:  5 300 7 9 1
#      Die ersten beiden Zahlen sind die Falle: **vertauscht waeren sie `300 5`**, und kein
#      Typ haette etwas dagegen gehabt. Das Gift unten vertauscht genau die zwei Bestimmer.
lauf "beispiel21" "$W/beispiele/21-verbundwert.gab" "$TREIBER21" "5 300 7 9 1" \
     's/\.id = k, \.len = n/.id = n, .len = k/' \
     "0 Annahmen, 1 Schablonen (0 davon UNBEWIESEN), 4 direkte Formen, 0 fremde Ruempfe (0 sprechen ihre Pflicht aus)"


# -- 9. K11.2.3: `release`/`acquire` senken ab -- und was der Test NICHT zeigen kann ------
#
# Bis zum 2026-08-17 weigerte sich der Erzeuger hier, mit diesem Grund: *„dass ein
# release-Speichern die Sichtbarkeit HERSTELLT, die die Paarung behauptet, ist eine Aussage
# ueber das Speichermodell."* **Der Grund stimmt weiter -- er ist nur kein Grund fuer eine
# Weigerung.** Die Aussage steht als A10 in der Axiomschicht, gebucht als NICHT falsifizierbar.
#
# **Und die Grenze dieses Tests gehoert hierher, nicht in eine Fussnote:** ein Differenztest
# kann die ABWESENHEIT eines Rennens nicht zeigen. Ein gruener Lauf sagt nur, dass die
# Umordnung diesmal ausblieb -- woertlich der Satz, mit dem A10 als nicht falsifizierbar
# gebucht ist.
#
# *Was er zeigt, ist die STRUKTURELLE Zusage: im C steht die Ordnung, die die Quelle sagte,
# und nicht das Vorgabemodell von `_Atomic`.* Das Gift unten ersetzt sie durch `relaxed`.
TREIBER14='#include <stdio.h>
struct Bericht { unsigned daten; };
#include "@ERZEUGT@"
int main(void) {
    struct Bericht b = { 0 };
    printf("%d ", abholen(&b) ? 1 : 0);
    anstossen(&b);
    printf("%d\n", abholen(&b) ? 1 : 0);
    return 0;
}
'
#    Erwartet:  0 1
#      Vor dem Anstossen liest die Gegenseite `false`, danach `true` -- die Paarung traegt
#      ueber eine ZWISCHENFUNKTION (`anstossen` publiziert selbst nicht).
#
#    **Das Gift vertauscht den WERT, nicht die Ordnung, und das ist kein Versehen.** Ein
#    erster Versuch ersetzte `memory_order_release` durch `relaxed` -- und die Sprechprobe
#    meldete UEBERSEHEN: das veraenderte Erzeugnis liefert dasselbe. *Natuerlich tut es das.*
#    Ein einlaeufiger Test kann eine Ordnung nicht sehen.
#
#    > **Genau das hat `PLAN.md` (K11.2.3) vorab gesagt:** ein Differenztest kann die
#    > ABWESENHEIT eines Rennens nicht zeigen. Die Ordnung im C wird darum ANDERSWO gehalten
#    > -- durch das gebuchte Zeugnis (Stufe 5), eine Sprechprobe in `rechenwerk.rs` und zwei
#    > Mutationen. *Hier faellt der Wert; die Ordnung faellt dort.*
lauf "beispiel14" "$W/beispiele/14-paarung-ueber-zwischenfunktion.gab" "$TREIBER14" "0 1" \
     's/atomic_store_explicit(&FERTIG, true,/atomic_store_explicit(\&FERTIG, false,/' \
     "0 Annahmen, 0 Schablonen (0 davon UNBEWIESEN), 6 direkte Formen, 0 fremde Ruempfe (0 sprechen ihre Pflicht aus)"


# -- 10. `accumulates`: eine Zelle je Kern, und der Test misst die SCHABLONE ---------------
#
# **Der Beweis lag VOR dem Konstrukt** (`beweise/Accumulates_Monoid.thy`, 2026-08-17), und er
# hat die Falle ausgespuelt, die hier drinsteckt: `min` hat als Neutrales das MAXIMUM des
# Typs, nicht die Null. Ein Erzeuger, der mit `0` anfaengt, zieht jedes `min` auf null.
#
# Der Treiber setzt drei Kerne und liest -- **das ist der RUHEPUNKT**, und nur dort sagt die
# Schablone eine Gleichheit mit einem atomaren RMW zu.
TREIBER23='#include <stdio.h>
static unsigned aktueller_kern = 0;
unsigned gabbro_kern(void) { return aktueller_kern; }
#include "@ERZEUGT@"
int main(void) {
    aktueller_kern = 0; melde_hoch(7);  melde_tief(7);  fehler_melden(1);
    aktueller_kern = 2; melde_hoch(19); melde_tief(3);  fehler_melden(1);
    aktueller_kern = 3; melde_hoch(4);  melde_tief(11); fehler_melden(1);
    printf("%llu %llu %u\n",
           (unsigned long long)hoechster(), (unsigned long long)tiefster(), fehler());
    return 0;
}
'
#    Erwartet:  19 3 3
#      Das MITTLERE ist die Falle: `min` ueber drei Kernen, waehrend 61 Zellen UNBERUEHRT
#      sind. **Der erste Lauf lieferte dort 0** -- C nullt statische Felder, und null ist
#      nicht das Neutrale von `min`. Der Beweis hatte den Satz (`min_ist_monoid_mit_top`),
#      die Absenkung hatte ihn nicht.
#
#      Die Loesung ist die DARSTELLUNG: `min` speichert das Komplement und faltet mit `max`.
#      Das Gift nimmt die Ruecknahme heraus -- dann steht dort das Komplement statt der Zahl.
lauf "beispiel23" "$W/beispiele/23-akkumulatoren.gab" "$TREIBER23" "19 3 3" \
     's/return (uint64_t)~z;/return z;/' \
     "0 Annahmen, 1 Schablonen (0 davon UNBEWIESEN), 4 direkte Formen, 3 fremde Ruempfe (0 sprechen ihre Pflicht aus)"


# -- 11. «B24» entschieden: der IP-Kopf, an einem echten Paket gemessen ------------------
#
# **Die Bitlage liegt im EIGENEN WORT des Feldes**, und das Wort wird zuerst in der erklaerten
# Bytereihenfolge gelesen. Der Treiber legt einen echten IPv4-Kopf hin und liest ihn zurueck.
#
# *Das Gift dreht die Schiebung um -- dann liest `version` die unteren vier Bits statt der
# oberen, und aus 4 wird 5.*
TREIBER24='#include <stdio.h>
#include "@ERZEUGT@"
static const unsigned char paket[20] = {
    0x45, 0x28, 0x00, 0x54,      /* v=4 ihl=5 | dscp=10 ecn=0 | len=84 */
    0x1c, 0x46, 0x40, 0x00,      /* id | flags=2 frag=0            */
    0x40, 0x06, 0xb1, 0xe6,      /* ttl=64 proto=6 | pruefsumme    */
    0xac, 0x10, 0x0a, 0x63,
    0xac, 0x10, 0x0a, 0x0c
};
int main(void) {
    IpKopf k = { paket, 20 };
    printf("%u %u %u %u %u %u %u\n",
           IpKopf_version(&k), IpKopf_ihl(&k), IpKopf_dscp(&k), IpKopf_ecn(&k),
           IpKopf_flags(&k), IpKopf_fragment(&k), IpKopf_protokoll(&k));
    return 0;
}
'
#    Erwartet:  4 5 10 0 2 0 6
#      Die ERSTEN ZWEI sind die Falle: `version` und `ihl` teilen Byte 0. Wer die Schiebung
#      vertauscht, liest 5 und 4 -- beides gueltige Zahlen, und kein Typ sagt etwas.
lauf "beispiel24" "$W/beispiele/24-ip-kopf.gab" "$TREIBER24" "4 5 10 0 2 0 6" \
     's/>> 4) & 15u/>> 0) \& 15u/' \
     "0 Annahmen, 1 Schablonen (0 davon UNBEWIESEN), 0 direkte Formen, 0 fremde Ruempfe (0 sprechen ihre Pflicht aus)"

echo "== EMISSION: ALL PASS -- 11 Uebersetzungseinheiten durchgestochen =="
echo "  Und was das NICHT heisst: sechs weitere Fragmente sind ungeprueft, der Erzeuger"
echo '  deckt genau die Formen dieser elf Dateien, und C001 weigert sich fuer jede'
echo "  andere. Elf Ja-Aussagen sind keine ueber die Sprache."
