#!/usr/bin/env bash
# **Der Differenztest -- die JA-Aussagen dieses Ordners.**
#
# Bis zum 2026-08-17 war die Emissionsflaeche die groesste unbeschaedigbare Flaeche des
# Projekts: `mutiere-pruefer.py` wies sie mit 0 Mutationen aus, und *was 0 Mutationen hat,
# ist nicht gedeckt, sondern unbeschaedigbar*.
#
# Dieser Waechter schliesst sie fuer ZWEI Uebersetzungseinheiten, nicht fuer zehn:
#
#     .gab  ->  gabbro emit  ->  C  ->  cc -Werror  ->  ausgefuehrt  ->  Ergebnis verglichen
#
# **Jede Stufe muss halten, und die letzte ist die, auf die es ankommt.** Ein Erzeuger, der
# uebersetzbares C liefert, das etwas anderes rechnet, ist schlimmer als einer, der nichts
# liefert -- er sieht aus wie ein Ergebnis.
#
#   1. `beispiele/16-by-ops-am-feld.gab` -- ein BEISPIEL. Tabelle, `count`, Bereichstypen.
#   2. `dokumente/FRAGMENTE.md` F7 -- ein FRAGMENT, und zwar aus dem eingefrorenen Korpus
#      geschnitten, nicht aus einer Kopie. Es misst die GEISTLOESCHUNG: `BootPhase` ist ein
#      `linear ghost type`, und die Frage, die dieser Lauf beantwortet, lautet **was kostet
#      die Phasendisziplin zur Laufzeit** -- Antwort: nichts.
set -euo pipefail
W="$(cd "$(dirname "$0")" && pwd)"
ARB="$(mktemp -d)"
trap 'rm -rf "$ARB"' EXIT

# **W1: eine uebersprungene Probe senkt die Zahl, sie laesst sie nicht unberuehrt.**
# Kein `cc` heisst NICHT „bestanden, uebersprungen" -- es heisst, dass dieser Waechter
# nichts gemessen hat, und das ist ein Rot.
if ! command -v cc > /dev/null; then
    echo "== EMISSION: KEIN CC -- der Differenztest hat NICHTS gemessen =="
    echo "  Ein fehlendes Werkzeug ist kein bestandener Test. W1: der Ausfall senkt die"
    echo "  Zahl, er laesst sie nicht unberuehrt."
    exit 1
fi

# Schneidet den ```gabbro-Block, der eine gegebene Zeile enthaelt, aus einer Markdown-Datei.
# **Aus dem Korpus, nicht aus einer Kopie** -- sonst misst der Waechter seine eigene Ablage.
schneide() {
    awk -v marke="$2" '
        /^```gabbro/ { drin=1; puffer=""; next }
        drin && /^```/ { if (puffer ~ marke) { printf "%s", puffer; exit } drin=0; next }
        drin { puffer = puffer $0 "\n" }
    ' "$1"
}

lauf() {                       # $1 Name  $2 Quelle  $3 Treiber  $4 Erwartet  $5 Gift-sed
    local name="$1" quelle="$2" treiber="$3" erwartet="$4" gift="$5"
    local c="$ARB/$name.c"
    echo "== Differenztest: $name =="

    # 1. Erzeugen. Der Pruefer laeuft davor -- C aus einem Baum zu erzeugen, den die Paesse
    #    nicht angenommen haben, waere C fuer ein Programm, das Gabbro ablehnt.
    if ! cargo run -q --manifest-path "$W/Cargo.toml" --bin gabbro -- emit "$quelle" \
            > "$c" 2> "$ARB/fehler"; then
        echo "  1. erzeugen:   GESCHEITERT"; cat "$ARB/fehler"; exit 1
    fi
    echo "  1. erzeugen:   ok ($(grep -c '' "$c") Zeilen C)"

    # 2. Der Lizenzhinweis. `LIZENZ-ZUSATZ.md` knuepft die zusaetzliche Erlaubnis an ihn --
    #    eine Bedingung, die niemand prueft, ist eine Bitte.
    if ! grep -q "Generated by Gabbro" "$c"; then
        echo "  2. Lizenz:     FEHLT -- die Bedingung aus LIZENZ-ZUSATZ.md steht nicht im C"; exit 1
    fi
    echo "  2. Lizenz:     ok (Hinweis im Kopf)"

    # 3. Uebersetzen, und zwar streng. Eine Warnung im erzeugten C ist ein Befund ueber den
    #    Erzeuger, nicht ueber den Anwender -- er hat die Zeile nicht geschrieben.
    printf '%s' "$treiber" | sed "s/@ERZEUGT@/$name.c/" > "$ARB/$name-treiber.c"
    if ! cc -std=c11 -Wall -Wextra -Werror -I"$ARB" -o "$ARB/$name-probe" \
            "$ARB/$name-treiber.c" 2> "$ARB/ccfehler"; then
        echo "  3. cc -Werror: GESCHEITERT"; head -20 "$ARB/ccfehler"; exit 1
    fi
    echo "  3. cc -Werror: ok (keine Warnung)"

    # 4. Ausfuehren und VERGLEICHEN. Das ist die Stufe, die die anderen drei erst zu einer
    #    Aussage macht.
    local ist; ist="$("$ARB/$name-probe")"
    if [ "$ist" != "$erwartet" ]; then
        echo "  4. Ergebnis:   FALSCH"
        echo "     erwartet:   $erwartet"
        echo "     bekommen:   $ist"
        exit 1
    fi
    echo "  4. Ergebnis:   ok ($ist)"

    # **Die Sprechprobe in die andere Richtung.** Ein Differenztest, der nicht rot werden kann,
    # misst nichts -- dieselbe Regel, mit der jede Messung dieses Ordners anfaengt (R14).
    sed "$gift" "$c" > "$ARB/$name-gift.c"
    printf '%s' "$treiber" | sed "s/@ERZEUGT@/$name-gift.c/" > "$ARB/$name-gifttreiber.c"
    cc -std=c11 -w -I"$ARB" -o "$ARB/$name-giftprobe" "$ARB/$name-gifttreiber.c"
    if [ "$("$ARB/$name-giftprobe")" = "$erwartet" ]; then
        echo "  5. Sprechprobe: UEBERSEHEN -- ein veraendertes Erzeugnis liefert dasselbe?"; exit 1
    fi
    echo "  5. Sprechprobe: ok (verfaelschtes C faellt)"
}

# -- 1. Das Beispiel: eine Tabelle, ein Feld, eine erzeugte Operation --------------------
#
#    Erwartet:  42  -- `stand` liefert, was geschrieben wurde
#                1  -- `belegen` setzt `benutzt`
#                8  -- das Feld hat die Slots aus `count N`, N = 8
#                0  -- und Slot 0 ist unberuehrt: die Operation trifft EINEN Slot
TREIBER16='#include <stdio.h>
#include "@ERZEUGT@"
int main(void) {
    Objekte o = {0};
    o.slots[3].zaehler = 42;
    belegen(&o, 3);
    printf("%u %d %d %d\n",
           stand(&o, 3),
           (int)o.slots[3].benutzt,
           (int)(sizeof(o.slots) / sizeof(o.slots[0])),
           (int)o.slots[0].benutzt);
    return 0;
}
'
lauf "beispiel16" "$W/beispiele/16-by-ops-am-feld.gab" "$TREIBER16" "42 1 8 0" \
     's/\.benutzt = true/.benutzt = false/'

# -- 2. Das Fragment: die Geistloeschung -------------------------------------------------
#
# **Die Frage, die dieser Lauf beantwortet:** `BootPhase` ist ein `linear ghost type`, der
# durch sechs Bootschritte gefaedelt und am Ende verbraucht wird. Er traegt das ganze
# Sicherheitsargument des Fragments -- und er darf zur Laufzeit **nicht existieren**.
#
# Die Loeschung muss an DREI Orten gleichzeitig halten, und zwei davon sind still, wenn sie
# ausfallen: die Signatur (`void mmu_an(void)`, nicht `void mmu_an(BootPhase)`), der Rufort
# (`mmu_an()`, nicht `mmu_an(p)`) und die `let`-Bindung (`mmu_an();`, nicht
# `void p1 = mmu_an();`). Faellt die dritte falsch aus -- naemlich indem die ganze Anweisung
# verschwindet --, uebersetzt das C und der Bootschritt findet **nicht statt**.
#
# Genau das misst die Erwartung: **sechs Schritte, in dieser Reihenfolge, je genau einmal.**
schneide "$W/dokumente/FRAGMENTE.md" "module caprock::bringup" > "$ARB/f7.gab"
if ! grep -q "linear ghost type BootPhase" "$ARB/f7.gab"; then
    echo "== EMISSION: F7 NICHT GESCHNITTEN -- der Waechter misst seine eigene Ablage =="
    exit 1
fi
TREIBER7='#include <stdio.h>
static int spur[8];
static int n;
void mmu_an(void)               { spur[n++] = 1; }
void cap_tabellen(void)         { spur[n++] = 2; }
void ipc_tabellen(void)         { spur[n++] = 3; }
void autoritaet_melden(void)    { spur[n++] = 4; }
void verifizierer_starten(void) { spur[n++] = 5; }
void root_task_starten(void)    { spur[n++] = 6; }
#include "@ERZEUGT@"
int main(void) {
    hochlauf();
    for (int i = 0; i < n; i++) printf("%d", spur[i]);
    printf("\n");
    return 0;
}
'
lauf "fragment7" "$ARB/f7.gab" "$TREIBER7" "123456" \
     's/    ipc_tabellen();/    \/* geloescht *\//'

echo "== EMISSION: ALL PASS -- 2 Uebersetzungseinheiten durchgestochen =="
echo "  Und was das NICHT heisst: acht weitere Fragmente sind ungeprueft, der Erzeuger"
echo '  deckt genau die Formen dieser beiden Dateien, und C001 weigert sich fuer jede'
echo "  andere. Zwei Ja-Aussagen sind keine ueber die Sprache."
