#!/usr/bin/env python3
"""Generate the SMT-LIB verification condition for `L05`, parametrised by the bound.

`L05` is *"`unlink` maintains `cdt_wohlgeformt`"*, and `cdt_wohlgeformt` is

    forall s in slots of c : c.slots[s] reaches WURZEL via parent

`V1.lean`'s `reachesIn` is BOUNDED, and the bound is the table's own `count` -- that is what
makes the helper total and the unrolling finite, and it is the whole reason the row reads
DEMAND and not NOT. **Here the bound becomes a number**, and the number is the subject of the
measurement: at which depth does the solver stop answering?

    ./messung/gabbrov/erzeuge-L05.py <bound> [--mit-frischer-wurzel]

The flag adds the one premise the second run needs; the report says which and why.
"""
import sys

k = int(sys.argv[1])
frisch = "--mit-frischer-wurzel" in sys.argv

# `reachesIn w "c" "parent" k x 0`, unrolled. `.absent` is not reached -- the `| _ => false`
# arm of `V1.lean`. The term is written over a chosen field function so that the SAME
# unrolling serves the pre state and the post state.
def reaches(feld, x, tiefe):
    if tiefe == 0:
        return "(= %s WURZEL)" % x
    return ("(ite (= %s WURZEL) true (ite ((_ is some) (%s %s)) %s false))"
            % (x, feld, x, reaches(feld, "(idx (%s %s))" % (feld, x), tiefe - 1)))

print(""";; L05 -- "the CDT stays well-formed": `unlink` maintains `cdt_wohlgeformt`.
;; `messung/fragmente/F01.gab`:199-200 (the `spec fn`) against :211-228 (the body).
;; Bound %d, generated by `messung/gabbrov/erzeuge-L05.py`.
(set-option :timeout 60000)
(set-option :produce-models true)
(declare-datatypes ((Opt 0)) (((none) (some (idx Int)))))
(declare-const N Int)
(declare-const s Int)
(declare-const WURZEL Int)
(assert (= WURZEL 0))
(assert (> N 1))
(assert (and (>= s 0) (< s N)))
(declare-fun parent0 (Int) Opt)
(declare-fun prev0   (Int) Opt)
(declare-fun next0   (Int) Opt)
(assert (forall ((x Int)) (=> (and (>= x 0) (< x N))
  (and (=> ((_ is some) (parent0 x)) (and (>= (idx (parent0 x)) 0) (< (idx (parent0 x)) N)))
       (=> ((_ is some) (prev0   x)) (and (>= (idx (prev0   x)) 0) (< (idx (prev0   x)) N)))
       (=> ((_ is some) (next0   x)) (and (>= (idx (next0   x)) 0) (< (idx (next0   x)) N)))))))
(define-fun parent1 ((x Int)) Opt (ite (= x s) none (parent0 x)))""" % k)

print(";; the premise: `cdt_wohlgeformt` holds before")
print("(assert (forall ((x Int)) (=> (and (>= x 0) (< x N)) %s)))"
      % reaches("parent0", "x", k))

if frisch:
    print("""
;; SECOND RUN, one added premise: the unlinked slot IS the root.
;; It is not a premise the fragment declares. It is the only way the obligation can hold
;; at all, and the run exists to show that the solver says so rather than that I do.""")
    print("(assert (= s WURZEL))")

print(";; the goal, negated")
print("(assert (not (forall ((x Int)) (=> (and (>= x 0) (< x N)) %s))))"
      % reaches("parent1", "x", k))
print("(check-sat)")
print("(get-model)")
