#!/usr/bin/env python3
"""Generate the SMT-LIB verification conditions for the GUARDED `cdt_wohlgeformt`.

Lane 266 (OFFEN O4) decides the repair of `messung/fragmente/F01.gab`:199-200 as

    forall s in slots of c : c.slots[s].used => c.slots[s] reaches WURZEL via parent

No new domain: `=>` is already a `pred` production (SYNTAX.md:669), and the same
guard shape stands in `wurzel_ohne_vorgaenger` (F01.gab:236-238) and in
`beispiele/01-tabelle.gab`:70-71. The second half of the decision is a different
HOME: `unlink` drops `maintains cdt_wohlgeformt` (its post-state is the legitimate
transient -- used, detached), `delete_leaf` and `revoke` keep it, and
`release_slot` gains it (it preserves the guarded invariant by removing `s`
from the domain).

    ./messung/gabbrov/erzeuge-L05used.py <fall> <bound>

`fall` is one of d, e, f, g, h:

  d -- guarded invariant AND one detached UNUSED slot.   expect sat
       (the repair is livable: free slots are allowed again -- L05c was unsat).
  e -- guarded invariant AND one detached USED slot.     expect unsat
       (the guard still says something: used+detached is forbidden. The
       d/e pair is its own control -- one flipped flag, sat to unsat).
  f -- `unlink` maintains the guarded invariant.         expect sat (REFUTED)
       (`unlink` requires `used`, clears `parent`, never clears `used`, so it
       leaves exactly the state e forbids. This is why it drops the claim.)
  g -- `delete_leaf` (unlink, then release) maintains it. expect sat (REFUTED)
       (the transient never crosses the boundary, but an ORPHAN does: a node
       `y` with `parent(y) = s` while `child(s)` is none keeps `s` a leaf by
       `ist_blatt`'s measure and still loses its chain. No declared premise
       excludes it -- the sibling half of B14. Case i names the premise.)
  h -- `release_slot` maintains it.                      expect unsat (HOLDS)
  i -- case g PLUS no-dangling-parent: nothing parents to `s`.
                                                     expect unsat (HOLDS)
       (the exact missing premise -- `parent(y) = some s => child(s) is some`.
       B14-class as a TABLE invariant (L02 mutuality needs indexing THROUGH
       the option); statable today only as a per-call `requires`, which moves
       the burden to every call site instead of supplying it once.)

`unsat` is passed, `sat` is refuted with a counterexample, `unknown` is
undecided (GABBROV.md section 4, read straight off the solver).
"""
import sys

fall = sys.argv[1]
k = int(sys.argv[2])
assert fall in "defghi", "fall is one of d, e, f, g, h, i"


# `reachesIn w "c" "parent" k x 0`, unrolled -- the `| _ => false` arm of
# `V1.lean`: `.absent` is not reached. Written over a chosen field function so
# the SAME unrolling serves the pre state and the post state.
def reaches(feld, x, tiefe):
    if tiefe == 0:
        return "(= %s WURZEL)" % x
    return ("(ite (= %s WURZEL) true (ite ((_ is some) (%s %s)) %s false))"
            % (x, feld, x, reaches(feld, "(idx (%s %s))" % (feld, x), tiefe - 1)))


print(""";; L05%s -- guarded `cdt_wohlgeformt`, bound %d.
;; Generated by `messung/gabbrov/erzeuge-L05used.py`. See its docstring for the
;; five cases and the verdict each one owes.
(set-option :timeout 60000)
(set-option :produce-models true)
(declare-datatypes ((Opt 0)) (((none) (some (idx Int)))))
(declare-const N Int)
(declare-const s Int)
(declare-const WURZEL Int)
(assert (= WURZEL 0))
(assert (> N 1))
(assert (and (>= s 0) (< s N)))
(declare-fun parent0 (Int) Opt)
(declare-fun prev0   (Int) Opt)
(declare-fun next0   (Int) Opt)
(declare-fun child0  (Int) Opt)
(declare-fun used0   (Int) Bool)
(assert (forall ((x Int)) (=> (and (>= x 0) (< x N))
  (and (=> ((_ is some) (parent0 x)) (and (>= (idx (parent0 x)) 0) (< (idx (parent0 x)) N)))
       (=> ((_ is some) (prev0   x)) (and (>= (idx (prev0   x)) 0) (< (idx (prev0   x)) N)))
       (=> ((_ is some) (next0   x)) (and (>= (idx (next0   x)) 0) (< (idx (next0   x)) N)))
       (=> ((_ is some) (child0  x)) (and (>= (idx (child0  x)) 0) (< (idx (child0  x)) N)))))))
;; the premise: the GUARDED invariant holds before
(assert (forall ((x Int)) (=> (and (>= x 0) (< x N))
  (=> (used0 x) %s))))""" % (fall, k, reaches("parent0", "x", k)))

if fall in "de":
    print(";; ONE detached slot, %s -- the state `release_slot` leaves behind"
          % ("UNUSED" if fall == "d" else "USED"))
    print("(declare-const u Int)")
    print("(assert (and (>= u 0) (< u N)))")
    print("(assert (not (= u WURZEL)))")
    print("(assert ((_ is none) (parent0 u)))")
    print("(assert %s)" % ("(not (used0 u))" if fall == "d" else "(used0 u)"))

if fall in "fghi":
    # The body of `unlink`, in order -- the same nest as `erzeuge-L05.py`.
    print("(define-fun parent1 ((x Int)) Opt (ite (= x s) none (parent0 x)))")
    print("""(define-fun prev1 ((x Int)) Opt
  (ite (= x s) none
    (ite (and ((_ is some) (next0 s)) (= x (idx (next0 s)))) (prev0 s)
      (prev0 x))))""")
    print("""(define-fun next1 ((x Int)) Opt
  (ite (= x s) none
    (ite (and ((_ is some) (prev0 s)) (= x (idx (prev0 s)))) (next0 s)
      (next0 x))))""")
    if fall == "f":
        print(";; `unlink` requires `used` and never clears it")
        print("(assert (used0 s))")
        post_feld, post_used = "parent1", "(used0 x)"
    else:
        # `release_slot` (h), and `delete_leaf` (g) after it: `used(s) := false`.
        # `gen` and `badge` are outside this encoding; nothing else moves.
        post_feld = "parent0" if fall == "h" else "parent1"
        post_used = "(ite (= x s) false (used0 x))"
        if fall in "gi":
            print(";; `delete_leaf` calls `unlink` (above) then `release_slot` (used := false).")
            print(";; Its `requires` are premises of the E-obligation: `used` AND `ist_blatt`.")
            print(";; The leaf arm is load-bearing: unlinking a node WITH children orphans")
            print(";; the subtree, and no invariant survives that -- the first version of")
            print(";; this file omitted it and came back `sat` through an orphaned child.")
            print("(assert (used0 s))")
            print("(assert ((_ is none) (child0 s)))")
            if fall == "i":
                print(";; ADDED for case i: no-dangling-parent -- nothing parents to `s`.")
                print(";; Without it case g is `sat` through a node `y` with `parent(y) = s`")
                print(";; while `child(s)` is none: a leaf by `ist_blatt`'s measure that still")
                print(";; orphans `y`. B14-class as a table invariant (L02 needs indexing")
                print(";; THROUGH the option); the `== Some(s)` comparison itself checks.")
                print("(assert (forall ((y Int)) (=> (and (>= y 0) (< y N))")
                print("  (=> (= (parent0 y) (some s)) ((_ is some) (child0 s))))))")
    print(";; the goal, negated")
    print("(assert (not (forall ((x Int)) (=> (and (>= x 0) (< x N))")
    print("  (=> %s %s)))))"
          % (post_used, reaches(post_feld, "x", k)))

print("(check-sat)")
print("(get-model)")
