-- GENERATED by `gabbro obligations --g beispiele/109-lockfree-entry-roots.gab` (lean-g export plus the stated obligation) -- do not edit.
-- A mechanical export of the checked unit as a G program term
-- (`Programm gD`, the syntax `RufMaschineG.lean` runs).
--
-- NO FORM in G (accepted and dropped, each named): the module
-- wrapper; named constants (inlined at every use); bare carrier
-- widths (a bare word travels as its full range); pointer address
-- spaces; lock hold budgets;
-- the `reads` effects; `costs`; the `by unvisited`/`by consuming`
-- run form, the `decreases` witness and the `touches` clause of a
-- `traverse` (static annotations, like `costs`); `by ops` on a field
-- (a writer discipline the checker holds); `mut` on a `let`;
-- `pub` and `opaque` (both are unit-boundary rules, and
-- `Deklaration` has no boundary -- `pub` added 2026-09-15 after
-- being dropped here and named nowhere, which is the one thing
-- this ledger exists to prevent; `opaque` the same day, when its
-- alias started to travel as its range);
-- `concurrent` (its members travel as the declared starts
-- `gE.starts`; every start is parameterless, its argument list
-- `.nil`); `entry`/`boot` (the vector, the registers, the steps:
-- NO FORM; only the dispatch root travels, as a declared start
-- where exportable).
--
-- table 0: T (count 4), v : 0..4294967295
-- table 1: U (count 4), v : 0..4294967295
-- lock 0: L (rank 0) guards T
-- lock 1: M (rank 1) guards U
-- fn write_a (holds L; writes T)
-- fn distribute_a (holds; writes T)
-- fn write_b (holds M; writes U)
-- fn distribute_b (holds; writes U)
-- start 0: distribute_a
-- start 1: distribute_b
import Grammatik.ZielOrtGeraetSem
import Grammatik.SperreSem
import Grammatik.Zielsatz.Akzeptiert
import Grammatik.Zielsatz.Beweis
import Grammatik.Zielsatz.Spec

namespace Gabbro.Grammatik

namespace G109_lockfree_entry_roots_oblig

inductive GTab where
  | T
  | U
  deriving DecidableEq

inductive GLock where
  | L
  | M
  deriving DecidableEq

inductive GTFeld where
  | v
  deriving DecidableEq

inductive GUFeld where
  | v
  deriving DecidableEq

inductive GFn where
  | write_a
  | distribute_a
  | write_b
  | distribute_b
  deriving DecidableEq

def gSig_write_a : Signatur GTab Empty GLock Empty where
  params := [.index 4]
  erg := none
  gruende := 0
  haelt := [GLock.L]
  boden := some 2
  schreibt := fun | .T => true | _ => false
  gschreibt := fun e => nomatch e
  konsumiert := []
  produziert := []

def gSig_distribute_a : Signatur GTab Empty GLock Empty where
  params := []
  erg := none
  gruende := 0
  haelt := []
  boden := some 0
  schreibt := fun | .T => true | _ => false
  gschreibt := fun e => nomatch e
  konsumiert := []
  produziert := []

def gSig_write_b : Signatur GTab Empty GLock Empty where
  params := [.index 4]
  erg := none
  gruende := 0
  haelt := [GLock.M]
  boden := some 2
  schreibt := fun | .U => true | _ => false
  gschreibt := fun e => nomatch e
  konsumiert := []
  produziert := []

def gSig_distribute_b : Signatur GTab Empty GLock Empty where
  params := []
  erg := none
  gruende := 0
  haelt := []
  boden := some 1
  schreibt := fun | .U => true | _ => false
  gschreibt := fun e => nomatch e
  konsumiert := []
  produziert := []

abbrev gD : Deklaration where
  Tab := GTab
  decTab := inferInstance
  count := fun | .T => 4 | .U => 4
  Feld := fun | .T => GTFeld | .U => GUFeld
  decFeld := fun | .T => inferInstance | .U => inferInstance
  typ := fun | .T, .v => ((.int 0 4294967295)) | .U, .v => ((.int 0 4294967295))
  erlaubt := fun _ _ _ _ => false
  tabNr := fun | 0 => some GTab.T | 1 => some GTab.U | _ => none
  Glob := Empty
  decGlob := inferInstance
  gtyp := fun e => nomatch e
  nutzlast := fun e => nomatch e
  atomar := fun e => nomatch e
  geteilt := fun | .T => true | .U => true
  ggeteilt := fun e => nomatch e
  Lock := GLock
  decLock := inferInstance
  rang := fun | .L => 0 | .M => 1
  maskiert := fun _ => false
  Marke := Empty
  decMarke := inferInstance
  stufen := fun e => nomatch e
  braucht := fun | .T => [.inl GLock.L] | .U => [.inl GLock.M]
  gbraucht := fun e => nomatch e
  eigner := fun _ => []
  Fn := GFn
  sig := fun | .write_a => 0 | .distribute_a => 1 | .write_b => 2 | .distribute_b => 3
  sigNr := fun | 0 => gSig_write_a | 1 => gSig_distribute_a | 2 => gSig_write_b | 3 => gSig_distribute_b | _ => gSig_distribute_b
  eigner_nie_erzeugt := fun _ _ _ _ h => by simp at h
  Inv := Empty
  traeger := fun e => nomatch e
  invs := []
  Ax := Empty
  aparams := fun e => nomatch e
  aerg := fun e => nomatch e
  aschreibt := fun e => nomatch e
  agschreibt := fun e => nomatch e
  Reg := Empty
  rtyp := fun e => nomatch e
  rklasse := fun e => nomatch e
  spiegel := fun e => nomatch e
  rzusage := fun e => nomatch e
  Annahme := Unit
  a10 := ()
  geteilt_bewacht := fun t => by cases t <;> decide
  invarianten_gehalten := fun _ i => nomatch i
  ggeteilt_bewacht := fun e => nomatch e

abbrev gCtx_write_a : Ctx := [.index 4]
def g_write_a : gD.Fn := GFn.write_a
abbrev gCtx_distribute_a : Ctx := []
def g_distribute_a : gD.Fn := GFn.distribute_a
abbrev gCtx_write_b : Ctx := [.index 4]
def g_write_b : gD.Fn := GFn.write_b
abbrev gCtx_distribute_b : Ctx := []
def g_distribute_b : gD.Fn := GFn.distribute_b

abbrev gL_write_a : List (Res gD) := [Res.held (D := gD) GLock.L]
abbrev gL_distribute_a : List (Res gD) := []
abbrev gL_write_b : List (Res gD) := [Res.held (D := gD) GLock.M]
abbrev gL_distribute_b : List (Res gD) := []
abbrev gL_distribute_a_in_L : List (Res gD) := [Res.held (D := gD) GLock.L]
abbrev gL_distribute_b_in_M : List (Res gD) := [Res.held (D := gD) GLock.M]

theorem gDarf_write_a_T : darf gD GTab.T gL_write_a := by unfold darf; decide
theorem gDarf_write_b_U : darf gD GTab.U gL_write_b := by unfold darf; decide

theorem gHp_distribute_a_in_L_write_a : RufPasst gD (vertragVon gD g_distribute_a) (gD.signatur g_write_a) gL_distribute_a_in_L where
  hw := fun t => by cases t <;> decide
  hg := fun g => nomatch g
  hk := ⟨[], List.Perm.refl [], by simp⟩
  hh := fun L => by cases L <;> decide
  hx := fun L hL hn => by cases L <;> (first | exact absurd (by decide) hn | exact absurd hL (by decide))
  hb := fun c h => by have hV : (vertragVon gD g_distribute_a).boden = some 0 := rfl; rw [hV] at h; cases h; exact ⟨2, rfl, by decide⟩

theorem gHp_distribute_b_in_M_write_b : RufPasst gD (vertragVon gD g_distribute_b) (gD.signatur g_write_b) gL_distribute_b_in_M where
  hw := fun t => by cases t <;> decide
  hg := fun g => nomatch g
  hk := ⟨[], List.Perm.refl [], by simp⟩
  hh := fun L => by cases L <;> decide
  hx := fun L hL hn => by cases L <;> (first | exact absurd (by decide) hn | exact absurd hL (by decide))
  hb := fun c h => by have hV : (vertragVon gD g_distribute_b).boden = some 1 := rfl; rw [hV] at h; cases h; exact ⟨2, rfl, by decide⟩

def gBody_write_a : Endblock gD (vertragVon gD g_write_a) false gCtx_write_a gL_write_a :=
  (.cons (.assignSlot GTab.T GTFeld.v ((.var .hier)) ((.weiter (by decide) (by decide) (((.lit 1)) : Expr gD gCtx_write_a gL_write_a (.int 1 1))) : Expr gD gCtx_write_a gL_write_a (.int 0 4294967295)) (by decide) gDarf_write_a_T) (.ret .keine (List.Perm.refl _)))

def gBody_distribute_a : Endblock gD (vertragVon gD g_distribute_a) false gCtx_distribute_a gL_distribute_a :=
  (.cons (.locks GLock.L (fun M => by cases M <;> decide) (.cons (.call g_write_a (.cons ((.weiter (by decide) (by decide) (.lit 0) : Expr gD gCtx_distribute_a gL_distribute_a_in_L (.index (gD.count GTab.T)))) .nil) gHp_distribute_a_in_L_write_a rfl) .nil)) (.ret .keine (List.Perm.refl _)))

def gBody_write_b : Endblock gD (vertragVon gD g_write_b) false gCtx_write_b gL_write_b :=
  (.cons (.assignSlot GTab.U GUFeld.v ((.var .hier)) ((.weiter (by decide) (by decide) (((.lit 2)) : Expr gD gCtx_write_b gL_write_b (.int 2 2))) : Expr gD gCtx_write_b gL_write_b (.int 0 4294967295)) (by decide) gDarf_write_b_U) (.ret .keine (List.Perm.refl _)))

def gBody_distribute_b : Endblock gD (vertragVon gD g_distribute_b) false gCtx_distribute_b gL_distribute_b :=
  (.cons (.locks GLock.M (fun M => by cases M <;> decide) (.cons (.call g_write_b (.cons ((.weiter (by decide) (by decide) (.lit 0) : Expr gD gCtx_distribute_b gL_distribute_b_in_M (.index (gD.count GTab.U)))) .nil) gHp_distribute_b_in_M_write_b rfl) .nil)) (.ret .keine (List.Perm.refl _)))

def gP : Programm gD where
  invariante := fun i => nomatch i
  requires
    | .write_a => .wahr
    | .distribute_a => .wahr
    | .write_b => .wahr
    | .distribute_b => .wahr
  ensures
    | .write_a => .wahr
    | .distribute_a => .wahr
    | .write_b => .wahr
    | .distribute_b => .wahr
  rumpf
    | .write_a => gBody_write_a
    | .distribute_a => gBody_distribute_a
    | .write_b => gBody_write_b
    | .distribute_b => gBody_distribute_b

def gFs : List gD.Fn := [g_write_a, g_distribute_a, g_write_b, g_distribute_b]

def gLs : List gD.Lock := [GLock.L, GLock.M]

def gCs : List (gD.Tab ⊕ gD.Glob) := [(.inl GTab.T), (.inl GTab.U)]

example : programmImFragmentG gP gFs = true := by decide

example : fussOrtGB gP gFs = true := by decide

-- The lock invariant family `gS` (`SperrInv`, `SperreSem.lean`):
-- lock L: no invariant (arm `fun _ => true`)
-- lock M: no invariant (arm `fun _ => true`)
def gS : SperrInv gD where
  orte := fun | .L => [.inl GTab.T] | .M => [.inl GTab.U]
  inv := fun | .L => fun _ => true | .M => fun _ => true

example : ((gS.orte GLock.L).elem (.inl GTab.T) = true) := by decide
example : ((gD.braucht GTab.T).elem (Sum.inl GLock.L) = true) := by decide
example : ((gS.orte GLock.M).elem (.inl GTab.U) = true) := by decide
example : ((gD.braucht GTab.U).elem (Sum.inl GLock.M) = true) := by decide

-- The declared initial memory (`Speicher gD`): every slot at zero,
-- every global at its DECLARED initialiser (a `static` names one).
def gSp0 : Speicher gD :=
  ⟨(fun t _ f => match t, f with | .T, .v => ⟨0, by decide, by decide⟩ | .U, .v => ⟨0, by decide, by decide⟩), (fun g => nomatch g)⟩

def gE : Zielsatz.Einheit gD where
  P := gP
  S := gS
  Q := fun _ _ _ => true
  starts := [⟨g_distribute_a, .nil⟩, ⟨g_distribute_b, .nil⟩]
  sp0 := gSp0

-- THE USER'S OBLIGATION (stated, not discharged).
--
-- `NutzerPflicht gE`: the bodies' logic (`LogikPflicht` -- per function
-- and at EVERY `forever` budget the body triple with caller duty and no
-- `logik` outcome, owed invariants at value AND reason exits) and the
-- start obligation (`StartPflicht` -- every lock invariant at `gE.sp0`,
-- every declared start's `requires` there with its declared arguments).
-- A `def` with no proof: the proof is the user's job. Stated through the
-- IMPORTED definition `NutzerPflicht`; its body is never copied here.
def nutzerPflicht : Prop := Zielsatz.NutzerPflicht gE

-- The member lists are complete (the `Aufzaehlung`s the goal theorem
-- quantifies over), decided here so the closing theorem below needs no
-- program fact beyond the user's obligation.
theorem gFs_voll : ∀ g : gD.Fn, g ∈ gFs := by
  intro g
  cases g <;> decide

theorem gLs_voll : ∀ L : gD.Lock, L ∈ gLs := by
  intro L
  cases L <;> decide

-- Carriers are tables or globals (lane 198 exports `static mut`
-- globals; a unit without one has `Glob := Empty`), and each arm
-- closes by cases over its constructors. `simp [gCs]`
-- and not `decide`: `DecidableEq (gD.Tab ⊕ gD.Glob)` does not unfold
-- the `gD` declaration during instance search (measured on 104/108:
-- `failed to synthesize Decidable (Sum.inl … ∈ gCs)`), while `simp`
-- rewrites membership over the literal list to constructor equalities.
theorem gCs_voll : ∀ c : gD.Tab ⊕ gD.Glob, c ∈ gCs := by
  intro c
  cases c with
  | inl t => cases t <;> simp [gCs]
  | inr g => cases g <;> simp [gCs]

-- The checker premise, discharged here: the concrete checker of the
-- goal theorem (`akzeptiert_pruefer`) accepts this program on these
-- lists. Where it does not, this `decide` fails -- loudly, not wrongly.
theorem gCheck : akzeptiert_pruefer.akzeptiert gE gFs gLs gCs = true := by decide

-- THE CLOSING THEOREM: the conclusion of `GabbroZiel` for this program,
-- derived from `gabbro_ziel`. The checker premise travels discharged
-- (`gCheck`); the user's obligation stays open as a hypothesis -- that
-- is the point. Apply it once `nutzerPflicht` is proved.
theorem gP_gabbro (hN : Zielsatz.NutzerPflicht gE) (O : Orakel gD)
    (hH : Zielsatz.HardwareAnnahmen O gE.Q) (passes : Nat)
    (sp : Speicher gD.mitRuhe)
    (init : Faden → Σ f : gD.mitRuhe.Fn, Env gD.mitRuhe (gD.mitRuhe.params f))
    (hL : Zielsatz.Laufzeit gE sp init) (M : RufMaschineG gD.mitRuhe)
    (hr : RufErreichbarG gE.P.mitRuhe O.mitRuhe passes (RufStartG gE.P.mitRuhe sp init) M) :
    Zielsatz.Ziel gE.P.mitRuhe gE.S.mitRuhe O.mitRuhe passes (RufStartG gE.P.mitRuhe sp init) M :=
  Zielsatz.gabbro_ziel_g akzeptiert_pruefer gD gE ⟨gFs, gFs_voll⟩ ⟨gLs, gLs_voll⟩ ⟨gCs, gCs_voll⟩
    gCheck hN O hH passes sp init hL M hr

-- RELEASE OBLIGATIONS (stated, not discharged -- O12).
--
-- At every `locks L { ... }` exit the lock invariant of `L` must hold
-- again, and it must follow from what the section's callees PROMISE
-- (their `ensures`), not from what their bodies happen to do. No checker
-- rule refuses a section whose callees cannot re-establish it, so such
-- a section is checker-clean and still leaves `NutzerPflicht` unproved.
-- Each row below is syntactic, one-sided and order-aware (see
-- `crates/gabbro-check/src/freigabe.rs`): a write or a callee write after
-- the last promise of a cell breaks it. `RELEASE HOLDS (syntactic)` is
-- not a proof, while `RELEASE UNPROVED` names the exact gap.
-- No lock carries an invariant -- nothing is owed at any release.
end G109_lockfree_entry_roots_oblig

end Gabbro.Grammatik
