-- GENERATED by `gabbro obligations --g beispiele/118-sperrinvariante-erhaltung.gab` (lean-g export plus the stated obligation) -- do not edit.
-- A mechanical export of the checked unit as a G program term
-- (`Programm gD`, the syntax `RufMaschineG.lean` runs).
--
-- NO FORM in G (accepted and dropped, each named): the module
-- wrapper; named constants (inlined at every use); bare carrier
-- widths (a bare word travels as its full range); pointer address
-- spaces; lock hold budgets;
-- the `reads` effects; `costs`; the `by unvisited`/`by consuming`
-- run form, the `decreases` witness and the `touches` clause of a
-- `traverse` (static annotations, like `costs`); `by ops` on a field
-- (a writer discipline the checker holds); `mut` on a `let`;
-- `pub` and `opaque` (both are unit-boundary rules, and
-- `Deklaration` has no boundary -- `pub` added 2026-09-15 after
-- being dropped here and named nowhere, which is the one thing
-- this ledger exists to prevent; `opaque` the same day, when its
-- alias started to travel as its range);
-- `concurrent` (its members travel as the declared starts
-- `gE.starts`; every start is parameterless, its argument list
-- `.nil`); `entry`/`boot` (the vector, the registers, the steps:
-- NO FORM; only the dispatch root travels, as a declared start
-- where exportable).
--
-- table 0: A (count 2), x : 0..100
-- table 1: B (count 2), y : 0..100
-- lock 0: K (rank 0) guards A B
-- fn gib (holds K; writes A B)
-- fn nimm (holds K; writes A B)
import Grammatik.ZielOrtGeraetSem
import Grammatik.SperreSem
import Grammatik.Zielsatz.Akzeptiert
import Grammatik.Zielsatz.Beweis
import Grammatik.Zielsatz.Spec

namespace Gabbro.Grammatik

namespace G118_sperrinvariante_erhaltung_oblig

inductive GTab where
  | A
  | B
  deriving DecidableEq

inductive GLock where
  | K
  deriving DecidableEq

inductive GAFeld where
  | x
  deriving DecidableEq

inductive GBFeld where
  | y
  deriving DecidableEq

inductive GFn where
  | gib
  | nimm
  deriving DecidableEq

def gSig_gib : Signatur GTab Empty GLock Empty where
  params := [.ptr 0 true, .ptr 1 true]
  erg := none
  gruende := 0
  haelt := [GLock.K]
  boden := some 1
  schreibt := fun _ => true
  gschreibt := fun e => nomatch e
  konsumiert := []
  produziert := []

def gSig_nimm : Signatur GTab Empty GLock Empty where
  params := [.ptr 0 true, .ptr 1 true]
  erg := none
  gruende := 0
  haelt := [GLock.K]
  boden := some 1
  schreibt := fun _ => true
  gschreibt := fun e => nomatch e
  konsumiert := []
  produziert := []

abbrev gD : Deklaration where
  Tab := GTab
  decTab := inferInstance
  count := fun | .A => 2 | .B => 2
  Feld := fun | .A => GAFeld | .B => GBFeld
  decFeld := fun | .A => inferInstance | .B => inferInstance
  typ := fun | .A, .x => ((.int 0 100)) | .B, .y => ((.int 0 100))
  erlaubt := fun _ _ _ _ => false
  tabNr := fun | 0 => some GTab.A | 1 => some GTab.B | _ => none
  Glob := Empty
  decGlob := inferInstance
  gtyp := fun e => nomatch e
  nutzlast := fun e => nomatch e
  atomar := fun e => nomatch e
  geteilt := fun | .A => true | .B => true
  ggeteilt := fun e => nomatch e
  Lock := GLock
  decLock := inferInstance
  rang := fun | .K => 0
  maskiert := fun _ => false
  Marke := Empty
  decMarke := inferInstance
  stufen := fun e => nomatch e
  braucht := fun | .A => [.inl GLock.K] | .B => [.inl GLock.K]
  gbraucht := fun e => nomatch e
  eigner := fun _ => []
  Fn := GFn
  sig := fun | .gib => 0 | .nimm => 1
  sigNr := fun | 0 => gSig_gib | 1 => gSig_nimm | _ => gSig_nimm
  eigner_nie_erzeugt := fun _ _ _ _ h => by simp at h
  Inv := Empty
  traeger := fun e => nomatch e
  invs := []
  Ax := Empty
  aparams := fun e => nomatch e
  aerg := fun e => nomatch e
  aschreibt := fun e => nomatch e
  agschreibt := fun e => nomatch e
  Reg := Empty
  rtyp := fun e => nomatch e
  rklasse := fun e => nomatch e
  spiegel := fun e => nomatch e
  rzusage := fun e => nomatch e
  Annahme := Unit
  a10 := ()
  geteilt_bewacht := fun t => by cases t <;> decide
  invarianten_gehalten := fun _ i => nomatch i
  ggeteilt_bewacht := fun e => nomatch e

abbrev gCtx_gib : Ctx := [.ptr 0 true, .ptr 1 true]
def g_gib : gD.Fn := GFn.gib
abbrev gCtx_nimm : Ctx := [.ptr 0 true, .ptr 1 true]
def g_nimm : gD.Fn := GFn.nimm

abbrev gL_gib : List (Res gD) := [Res.held (D := gD) GLock.K]
abbrev gL_nimm : List (Res gD) := [Res.held (D := gD) GLock.K]

theorem gDarf_gib_A : darf gD GTab.A gL_gib := by unfold darf; decide
theorem gDarf_gib_B : darf gD GTab.B gL_gib := by unfold darf; decide
theorem gDarf_nimm_A : darf gD GTab.A gL_nimm := by unfold darf; decide
theorem gDarf_nimm_B : darf gD GTab.B gL_nimm := by unfold darf; decide

def gBody_gib : Endblock gD (vertragVon gD g_gib) false gCtx_gib gL_gib :=
  (.cons (.assignDurch (.var .hier) GTab.A rfl GAFeld.x (((.weiter (by decide) (by decide) (.lit 0) : Expr gD gCtx_gib gL_gib (.index (gD.count GTab.A))))) ((.weiter (by decide) (by decide) (((.lit 30)) : Expr gD gCtx_gib gL_gib (.int 30 30))) : Expr gD gCtx_gib gL_gib (.int 0 100)) (by decide) gDarf_gib_A) (.cons (.assignDurch (.var (.dort .hier)) GTab.B rfl GBFeld.y (((.weiter (by decide) (by decide) (.lit 0) : Expr gD gCtx_gib gL_gib (.index (gD.count GTab.B))))) ((.weiter (by decide) (by decide) (((.lit 70)) : Expr gD gCtx_gib gL_gib (.int 70 70))) : Expr gD gCtx_gib gL_gib (.int 0 100)) (by decide) gDarf_gib_B) (.ret .keine (List.Perm.refl _))))

def gBody_nimm : Endblock gD (vertragVon gD g_nimm) false gCtx_nimm gL_nimm :=
  (.cons (.assignDurch (.var .hier) GTab.A rfl GAFeld.x (((.weiter (by decide) (by decide) (.lit 0) : Expr gD gCtx_nimm gL_nimm (.index (gD.count GTab.A))))) ((.weiter (by decide) (by decide) (((.lit 10)) : Expr gD gCtx_nimm gL_nimm (.int 10 10))) : Expr gD gCtx_nimm gL_nimm (.int 0 100)) (by decide) gDarf_nimm_A) (.cons (.assignDurch (.var (.dort .hier)) GTab.B rfl GBFeld.y (((.weiter (by decide) (by decide) (.lit 0) : Expr gD gCtx_nimm gL_nimm (.index (gD.count GTab.B))))) ((.weiter (by decide) (by decide) (((.lit 90)) : Expr gD gCtx_nimm gL_nimm (.int 90 90))) : Expr gD gCtx_nimm gL_nimm (.int 0 100)) (by decide) gDarf_nimm_B) (.ret .keine (List.Perm.refl _))))

def gP : Programm gD where
  invariante := fun i => nomatch i
  requires
    | .gib => .wahr
    | .nimm => .wahr
  ensures
    | .gib => .wahr
    | .nimm => .wahr
  rumpf
    | .gib => gBody_gib
    | .nimm => gBody_nimm

def gFs : List gD.Fn := [g_gib, g_nimm]

def gLs : List gD.Lock := [GLock.K]

def gCs : List (gD.Tab ⊕ gD.Glob) := [(.inl GTab.A), (.inl GTab.B)]

example : programmImFragmentG gP gFs = true := by decide

example : fussOrtGB gP gFs = true := by decide

-- The lock invariant family `gS` (`SperrInv`, `SperreSem.lean`):
-- lock K: invariant below
def gS : SperrInv gD where
  orte := fun | .K => [.inl GTab.A, .inl GTab.B]
  inv := fun | .K => fun s => ((((s.slots GTab.A 0 GAFeld.x).n) + ((s.slots GTab.B 0 GBFeld.y).n)) == (100 : Int))

example : ((gS.orte GLock.K).elem (.inl GTab.A) = true) := by decide
example : ((gD.braucht GTab.A).elem (Sum.inl GLock.K) = true) := by decide
example : ((gS.orte GLock.K).elem (.inl GTab.B) = true) := by decide
example : ((gD.braucht GTab.B).elem (Sum.inl GLock.K) = true) := by decide

-- The declared initial memory (`Speicher gD`): every slot at zero,
-- every global at its DECLARED initialiser (a `static` names one).
def gSp0 : Speicher gD :=
  ⟨(fun t _ f => match t, f with | .A, .x => ⟨0, by decide, by decide⟩ | .B, .y => ⟨0, by decide, by decide⟩), (fun g => nomatch g)⟩

def gE : Zielsatz.Einheit gD where
  P := gP
  S := gS
  Q := fun _ _ _ => true
  starts := []
  sp0 := gSp0

-- THE USER'S OBLIGATION (stated, not discharged).
--
-- `NutzerPflicht gE`: the bodies' logic (`LogikPflicht` -- per function
-- and at EVERY `forever` budget the body triple with caller duty and no
-- `logik` outcome, owed invariants at value AND reason exits) and the
-- start obligation (`StartPflicht` -- every lock invariant at `gE.sp0`,
-- every declared start's `requires` there with its declared arguments).
-- A `def` with no proof: the proof is the user's job. Stated through the
-- IMPORTED definition `NutzerPflicht`; its body is never copied here.
def nutzerPflicht : Prop := Zielsatz.NutzerPflicht gE

-- The member lists are complete (the `Aufzaehlung`s the goal theorem
-- quantifies over), decided here so the closing theorem below needs no
-- program fact beyond the user's obligation.
theorem gFs_voll : ∀ g : gD.Fn, g ∈ gFs := by
  intro g
  cases g <;> decide

theorem gLs_voll : ∀ L : gD.Lock, L ∈ gLs := by
  intro L
  cases L <;> decide

-- Carriers are tables or globals (lane 198 exports `static mut`
-- globals; a unit without one has `Glob := Empty`), and each arm
-- closes by cases over its constructors. `simp [gCs]`
-- and not `decide`: `DecidableEq (gD.Tab ⊕ gD.Glob)` does not unfold
-- the `gD` declaration during instance search (measured on 104/108:
-- `failed to synthesize Decidable (Sum.inl … ∈ gCs)`), while `simp`
-- rewrites membership over the literal list to constructor equalities.
theorem gCs_voll : ∀ c : gD.Tab ⊕ gD.Glob, c ∈ gCs := by
  intro c
  cases c with
  | inl t => cases t <;> simp [gCs]
  | inr g => cases g <;> simp [gCs]

-- The checker premise, discharged here: the concrete checker of the
-- goal theorem (`akzeptiert_pruefer`) accepts this program on these
-- lists. Where it does not, this `decide` fails -- loudly, not wrongly.
theorem gCheck : akzeptiert_pruefer.akzeptiert gE gFs gLs gCs = true := by decide

-- THE CLOSING THEOREM: the conclusion of `GabbroZiel` for this program,
-- derived from `gabbro_ziel`. The checker premise travels discharged
-- (`gCheck`); the user's obligation stays open as a hypothesis -- that
-- is the point. Apply it once `nutzerPflicht` is proved.
theorem gP_gabbro (hN : Zielsatz.NutzerPflicht gE) (O : Orakel gD)
    (hH : Zielsatz.HardwareAnnahmen O gE.Q) (passes : Nat)
    (sp : Speicher gD.mitRuhe)
    (init : Faden → Σ f : gD.mitRuhe.Fn, Env gD.mitRuhe (gD.mitRuhe.params f))
    (hL : Zielsatz.Laufzeit gE sp init) (M : RufMaschineG gD.mitRuhe)
    (hr : RufErreichbarG gE.P.mitRuhe O.mitRuhe passes (RufStartG gE.P.mitRuhe sp init) M) :
    Zielsatz.Ziel gE.P.mitRuhe gE.S.mitRuhe O.mitRuhe passes (RufStartG gE.P.mitRuhe sp init) M :=
  Zielsatz.gabbro_ziel_g akzeptiert_pruefer gD gE ⟨gFs, gFs_voll⟩ ⟨gLs, gLs_voll⟩ ⟨gCs, gCs_voll⟩
    gCheck hN O hH passes sp init hL M hr

-- RELEASE OBLIGATIONS (stated, not discharged -- O12).
--
-- At every `locks L { ... }` exit the lock invariant of `L` must hold
-- again, and it must follow from what the section's callees PROMISE
-- (their `ensures`), not from what their bodies happen to do. No checker
-- rule refuses a section whose callees cannot re-establish it, so such
-- a section is checker-clean and still leaves `NutzerPflicht` unproved.
-- Each row below is syntactic, one-sided and order-aware (see
-- `crates/gabbro-check/src/freigabe.rs`): a write or a callee write after
-- the last promise of a cell breaks it. `RELEASE HOLDS (syntactic)` is
-- not a proof, while `RELEASE UNPROVED` names the exact gap.
-- No `locks` section in any body -- nothing is owed at any release.
end G118_sperrinvariante_erhaltung_oblig

end Gabbro.Grammatik
