-- GENERATED by `gabbro obligations --g beispiele/157-worker-pool.gab` (lean-g export plus the stated obligation) -- do not edit.
-- A mechanical export of the checked unit as a G program term
-- (`Programm gD`, the syntax `RufMaschineG.lean` runs).
--
-- NO FORM in G (accepted and dropped, each named): the module
-- wrapper; named constants (inlined at every use); bare carrier
-- widths (a bare word travels as its full range); pointer address
-- spaces; lock hold budgets;
-- the `reads` effects; `costs`; the `by unvisited`/`by consuming`
-- run form, the `decreases` witness and the `touches` clause of a
-- `traverse` (static annotations, like `costs`); `by ops` on a field
-- (a writer discipline the checker holds); `mut` on a `let`;
-- `pub` and `opaque` (both are unit-boundary rules, and
-- `Deklaration` has no boundary -- `pub` added 2026-09-15 after
-- being dropped here and named nowhere, which is the one thing
-- this ledger exists to prevent; `opaque` the same day, when its
-- alias started to travel as its range);
-- `concurrent` (its members travel as the declared starts
-- `gE.starts`; every start is parameterless, its argument list
-- `.nil`); `entry`/`boot` (the vector, the registers, the steps:
-- NO FORM; only the dispatch root travels, as a declared start
-- where exportable).
--
-- table 0: konto (count 2), stand : 0..100
-- lock 0: L (rank 0) guards konto
-- fn setze (holds L; writes konto)
-- fn arbeiter (holds; writes konto)
-- start 0: arbeiter
-- start 1: arbeiter
import Grammatik.ZielOrtGeraetSem
import Grammatik.SperreSem
import Grammatik.Zielsatz.Akzeptiert
import Grammatik.Zielsatz.Beweis
import Grammatik.Zielsatz.Spec

namespace Gabbro.Grammatik

namespace G157_worker_pool_oblig

inductive GTab where
  | konto
  deriving DecidableEq

inductive GLock where
  | L
  deriving DecidableEq

inductive GkontoFeld where
  | stand
  deriving DecidableEq

inductive GFn where
  | setze
  | arbeiter
  deriving DecidableEq

def gSig_setze : Signatur GTab Empty GLock Empty where
  params := [(.int 0 100)]
  erg := none
  gruende := 0
  haelt := [GLock.L]
  boden := some 1
  schreibt := fun _ => true
  gschreibt := fun e => nomatch e
  konsumiert := []
  produziert := []

def gSig_arbeiter : Signatur GTab Empty GLock Empty where
  params := []
  erg := none
  gruende := 0
  haelt := []
  boden := some 0
  schreibt := fun _ => true
  gschreibt := fun e => nomatch e
  konsumiert := []
  produziert := []

abbrev gD : Deklaration where
  Tab := GTab
  decTab := inferInstance
  count := fun | .konto => 2
  Feld := fun | .konto => GkontoFeld
  decFeld := fun | .konto => inferInstance
  typ := fun | .konto, .stand => ((.int 0 100))
  erlaubt := fun _ _ _ _ => false
  tabNr := fun | 0 => some GTab.konto | _ => none
  Glob := Empty
  decGlob := inferInstance
  gtyp := fun e => nomatch e
  nutzlast := fun e => nomatch e
  atomar := fun e => nomatch e
  geteilt := fun | .konto => true
  ggeteilt := fun e => nomatch e
  Lock := GLock
  decLock := inferInstance
  rang := fun | .L => 0
  maskiert := fun _ => false
  Marke := Empty
  decMarke := inferInstance
  stufen := fun e => nomatch e
  braucht := fun | .konto => [.inl GLock.L]
  gbraucht := fun e => nomatch e
  eigner := fun _ => []
  Fn := GFn
  sig := fun | .setze => 0 | .arbeiter => 1
  sigNr := fun | 0 => gSig_setze | 1 => gSig_arbeiter | _ => gSig_arbeiter
  eigner_nie_erzeugt := fun _ _ _ _ h => by simp at h
  Inv := Empty
  traeger := fun e => nomatch e
  invs := []
  Ax := Empty
  aparams := fun e => nomatch e
  aerg := fun e => nomatch e
  aschreibt := fun e => nomatch e
  agschreibt := fun e => nomatch e
  Reg := Empty
  rtyp := fun e => nomatch e
  rklasse := fun e => nomatch e
  spiegel := fun e => nomatch e
  rzusage := fun e => nomatch e
  Annahme := Unit
  a10 := ()
  geteilt_bewacht := fun t => by cases t <;> decide
  invarianten_gehalten := fun _ i => nomatch i
  ggeteilt_bewacht := fun e => nomatch e

abbrev gCtx_setze : Ctx := [(.int 0 100)]
def g_setze : gD.Fn := GFn.setze
abbrev gCtx_arbeiter : Ctx := []
def g_arbeiter : gD.Fn := GFn.arbeiter

abbrev gL_setze : List (Res gD) := [Res.held (D := gD) GLock.L]
abbrev gL_arbeiter : List (Res gD) := []
abbrev gL_arbeiter_in_L : List (Res gD) := [Res.held (D := gD) GLock.L]

theorem gDarf_setze_konto : darf gD GTab.konto gL_setze := by unfold darf; decide

theorem gHp_arbeiter_in_L_setze : RufPasst gD (vertragVon gD g_arbeiter) (gD.signatur g_setze) gL_arbeiter_in_L where
  hw := fun t => by cases t <;> decide
  hg := fun g => nomatch g
  hk := ⟨[], List.Perm.refl [], by simp⟩
  hh := fun L => by cases L <;> decide
  hx := fun L hL hn => by cases L <;> (first | exact absurd (by decide) hn | exact absurd hL (by decide))
  hb := fun c h => by have hV : (vertragVon gD g_arbeiter).boden = some 0 := rfl; rw [hV] at h; cases h; exact ⟨1, rfl, by decide⟩

def gEns_setze : Expr gD (ErgCtx (gD.params g_setze) (gD.erg g_setze)) (vertragVon gD g_setze).ende .bool :=
  (.und (.eq (Expr.slot (D := gD) GTab.konto GkontoFeld.stand (((.weiter (by decide) (by decide) (.lit 0) : Expr gD (ErgCtx (gD.params g_setze) (gD.erg g_setze)) gL_setze (.index (gD.count GTab.konto))))) gDarf_setze_konto) (Expr.slot (D := gD) GTab.konto GkontoFeld.stand (((.weiter (by decide) (by decide) (.lit 1) : Expr gD (ErgCtx (gD.params g_setze) (gD.erg g_setze)) gL_setze (.index (gD.count GTab.konto))))) gDarf_setze_konto)) (.eq (Expr.slot (D := gD) GTab.konto GkontoFeld.stand (((.weiter (by decide) (by decide) (.lit 0) : Expr gD (ErgCtx (gD.params g_setze) (gD.erg g_setze)) gL_setze (.index (gD.count GTab.konto))))) gDarf_setze_konto) (.var .hier)))

def gReq_setze : Expr gD (gD.params g_setze) (Signatur.anfang gD (gD.signatur g_setze)) .bool :=
  (.eq (Expr.slot (D := gD) GTab.konto GkontoFeld.stand (((.weiter (by decide) (by decide) (.lit 0) : Expr gD (gD.params g_setze) gL_setze (.index (gD.count GTab.konto))))) gDarf_setze_konto) (Expr.slot (D := gD) GTab.konto GkontoFeld.stand (((.weiter (by decide) (by decide) (.lit 1) : Expr gD (gD.params g_setze) gL_setze (.index (gD.count GTab.konto))))) gDarf_setze_konto))

def gBody_setze : Endblock gD (vertragVon gD g_setze) false gCtx_setze gL_setze :=
  (.cons (.assignSlot GTab.konto GkontoFeld.stand (((.weiter (by decide) (by decide) (.lit 0) : Expr gD gCtx_setze gL_setze (.index (gD.count GTab.konto))))) (.var .hier) (by decide) gDarf_setze_konto) (.cons (.assignSlot GTab.konto GkontoFeld.stand (((.weiter (by decide) (by decide) (.lit 1) : Expr gD gCtx_setze gL_setze (.index (gD.count GTab.konto))))) (.var .hier) (by decide) gDarf_setze_konto) (.ret .keine (List.Perm.refl _))))

def gBody_arbeiter : Endblock gD (vertragVon gD g_arbeiter) false gCtx_arbeiter gL_arbeiter :=
  (.cons (.locks GLock.L (fun M => by cases M <;> decide) (.cons (.call g_setze (.cons ((.weiter (by decide) (by decide) (((.lit 30)) : Expr gD gCtx_arbeiter gL_arbeiter_in_L (.int 30 30))) : Expr gD gCtx_arbeiter gL_arbeiter_in_L (.int 0 100)) .nil) gHp_arbeiter_in_L_setze rfl) .nil)) (.ret .keine (List.Perm.refl _)))

def gP : Programm gD where
  invariante := fun i => nomatch i
  requires
    | .setze => gReq_setze
    | .arbeiter => .wahr
  ensures
    | .setze => gEns_setze
    | .arbeiter => .wahr
  rumpf
    | .setze => gBody_setze
    | .arbeiter => gBody_arbeiter

def gFs : List gD.Fn := [g_setze, g_arbeiter]

def gLs : List gD.Lock := [GLock.L]

def gCs : List (gD.Tab ⊕ gD.Glob) := [(.inl GTab.konto)]

example : programmImFragmentG gP gFs = true := by decide

-- No `fussOrtGB` check: some accessed carrier is taken in a
-- `locks` block (or written elsewhere unguarded), so the old
-- signature-held footprint does not apply. The applicable check
-- is the flagship's `FussS`/`fussSperreB`, which has no Rust rule.

-- The lock invariant family `gS` (`SperrInv`, `SperreSem.lean`):
-- lock L: invariant below
def gS : SperrInv gD where
  orte := fun | .L => [.inl GTab.konto]
  inv := fun | .L => fun s => (((s.slots GTab.konto 0 GkontoFeld.stand).n) == ((s.slots GTab.konto 1 GkontoFeld.stand).n))

example : ((gS.orte GLock.L).elem (.inl GTab.konto) = true) := by decide
example : ((gD.braucht GTab.konto).elem (Sum.inl GLock.L) = true) := by decide

-- The declared initial memory (`Speicher gD`): every slot at zero,
-- every global at its DECLARED initialiser (a `static` names one).
def gSp0 : Speicher gD :=
  ⟨(fun t _ f => match t, f with | .konto, .stand => ⟨0, by decide, by decide⟩), (fun g => nomatch g)⟩

def gE : Zielsatz.Einheit gD where
  P := gP
  S := gS
  Q := fun _ _ _ => true
  starts := [⟨g_arbeiter, .nil⟩, ⟨g_arbeiter, .nil⟩]
  sp0 := gSp0

-- THE USER'S OBLIGATION (stated, not discharged).
--
-- `NutzerPflicht gE`: the bodies' logic (`LogikPflicht` -- per function
-- and at EVERY `forever` budget the body triple with caller duty and no
-- `logik` outcome, owed invariants at value AND reason exits) and the
-- start obligation (`StartPflicht` -- every lock invariant at `gE.sp0`,
-- every declared start's `requires` there with its declared arguments).
-- A `def` with no proof: the proof is the user's job. Stated through the
-- IMPORTED definition `NutzerPflicht`; its body is never copied here.
def nutzerPflicht : Prop := Zielsatz.NutzerPflicht gE

-- The member lists are complete (the `Aufzaehlung`s the goal theorem
-- quantifies over), decided here so the closing theorem below needs no
-- program fact beyond the user's obligation.
theorem gFs_voll : ∀ g : gD.Fn, g ∈ gFs := by
  intro g
  cases g <;> decide

theorem gLs_voll : ∀ L : gD.Lock, L ∈ gLs := by
  intro L
  cases L <;> decide

-- Carriers are tables or globals (lane 198 exports `static mut`
-- globals; a unit without one has `Glob := Empty`), and each arm
-- closes by cases over its constructors. `simp [gCs]`
-- and not `decide`: `DecidableEq (gD.Tab ⊕ gD.Glob)` does not unfold
-- the `gD` declaration during instance search (measured on 104/108:
-- `failed to synthesize Decidable (Sum.inl … ∈ gCs)`), while `simp`
-- rewrites membership over the literal list to constructor equalities.
theorem gCs_voll : ∀ c : gD.Tab ⊕ gD.Glob, c ∈ gCs := by
  intro c
  cases c with
  | inl t => cases t <;> simp [gCs]
  | inr g => cases g <;> simp [gCs]

-- The checker premise, discharged here: the concrete checker of the
-- goal theorem (`akzeptiert_pruefer`) accepts this program on these
-- lists. Where it does not, this `decide` fails -- loudly, not wrongly.
theorem gCheck : akzeptiert_pruefer.akzeptiert gE gFs gLs gCs = true := by decide

-- THE CLOSING THEOREM: the conclusion of `GabbroZiel` for this program,
-- derived from `gabbro_ziel`. The checker premise travels discharged
-- (`gCheck`); the user's obligation stays open as a hypothesis -- that
-- is the point. Apply it once `nutzerPflicht` is proved.
theorem gP_gabbro (hN : Zielsatz.NutzerPflicht gE) (O : Orakel gD)
    (hH : Zielsatz.HardwareAnnahmen O gE.Q) (passes : Nat)
    (sp : Speicher gD.mitRuhe)
    (init : Faden → Σ f : gD.mitRuhe.Fn, Env gD.mitRuhe (gD.mitRuhe.params f))
    (hL : Zielsatz.Laufzeit gE sp init) (M : RufMaschineG gD.mitRuhe)
    (hr : RufErreichbarG gE.P.mitRuhe O.mitRuhe passes (RufStartG gE.P.mitRuhe sp init) M) :
    Zielsatz.Ziel gE.P.mitRuhe gE.S.mitRuhe O.mitRuhe passes (RufStartG gE.P.mitRuhe sp init) M :=
  Zielsatz.gabbro_ziel_g akzeptiert_pruefer gD gE ⟨gFs, gFs_voll⟩ ⟨gLs, gLs_voll⟩ ⟨gCs, gCs_voll⟩
    gCheck hN O hH passes sp init hL M hr

-- THE CLOSING THEOREM ON THE THREAD MACHINE: `GabbroZiel` itself for this
-- program -- `ZielF` on every reachable thread machine (run-time spawns
-- and joins included), from any set of initially live threads.
theorem gP_gabbro_f (hN : Zielsatz.NutzerPflicht gE) (O : Orakel gD)
    (hH : Zielsatz.HardwareAnnahmen O gE.Q) (passes : Nat)
    (sp : Speicher gD.mitRuhe)
    (init : Faden → Σ f : gD.mitRuhe.Fn, Env gD.mitRuhe (gD.mitRuhe.params f))
    (hL : Zielsatz.Laufzeit gE sp init) (lebt0 : Faden → Bool)
    (K : FadenMaschine gD.mitRuhe)
    (hK : FadenErreichbar gE.P.mitRuhe O.mitRuhe passes (FadenStart gE.P.mitRuhe sp init lebt0) K) :
    Zielsatz.ZielF gE.P.mitRuhe gE.S.mitRuhe O.mitRuhe passes (RufStartG gE.P.mitRuhe sp init) K :=
  Zielsatz.gabbro_ziel akzeptiert_pruefer gD gE ⟨gFs, gFs_voll⟩ ⟨gLs, gLs_voll⟩ ⟨gCs, gCs_voll⟩
    gCheck hN O hH passes sp init hL lebt0 K hK

-- RELEASE OBLIGATIONS (stated, not discharged -- O12).
--
-- At every `locks L { ... }` exit the lock invariant of `L` must hold
-- again, and it must follow from what the section's callees PROMISE
-- (their `ensures`), not from what their bodies happen to do. No checker
-- rule refuses a section whose callees cannot re-establish it, so such
-- a section is checker-clean and still leaves `NutzerPflicht` unproved.
-- Each row below is syntactic, one-sided and order-aware (see
-- `crates/gabbro-check/src/freigabe.rs`): a write or a callee write after
-- the last promise of a cell breaks it. `RELEASE HOLDS (syntactic)` is
-- not a proof, while `RELEASE UNPROVED` names the exact gap.
-- * arbeiter locks `L`: invariant over {konto.slots[0].stand, konto.slots[1].stand}; setze promises {konto.slots[0].stand, konto.slots[1].stand} -- RELEASE HOLDS (syntactic).
end G157_worker_pool_oblig

end Gabbro.Grammatik
