-- GENERATED by `gabbro obligations --g beispiele/174-tor-im-modell.gab` (lean-g export plus the stated obligation) -- do not edit.
-- A mechanical export of the checked unit as a G program term
-- (`Programm gD`, the syntax `RufMaschineG.lean` runs).
--
-- NO FORM in G (accepted and dropped, each named): the module
-- wrapper; named constants (inlined at every use); bare carrier
-- widths (a bare word travels as its full range); pointer address
-- spaces; lock hold budgets;
-- the `reads` effects; `costs`; the `by unvisited`/`by consuming`
-- run form, the `decreases` witness and the `touches` clause of a
-- `traverse` (static annotations, like `costs`); `by ops` on a field
-- (a writer discipline the checker holds); `mut` on a `let`;
-- `pub` and `opaque` (both are unit-boundary rules, and
-- `Deklaration` has no boundary -- `pub` added 2026-09-15 after
-- being dropped here and named nowhere, which is the one thing
-- this ledger exists to prevent; `opaque` the same day, when its
-- alias started to travel as its range);
-- `concurrent` (its members travel as the declared starts
-- `gE.starts`; every start is parameterless, its argument list
-- `.nil`); `entry`/`boot` (the vector, the registers, the steps:
-- NO FORM; only the dispatch root travels, as a declared start
-- where exportable, and a thrown `entry` -- one carrying a `via` path -- as
-- `gP.unterbricht`).
-- A `syscall` gate travels as `D.Ax` (parameters, answer; it
-- writes nothing); NO FORM: its ABI (`abi`, `arch`, `number`, the
-- register map, `clobbers`, `errors`, `syscall V;` and `target`
-- blocks) and its `assume … falsifier …` -- the C-side stub's half;
-- what the answer may be is premise (c), `HardwareAnnahmen O gE.Q`.
-- An `assume` travels as a `D.Annahme` constructor (a NAME: no
-- exported statement consumes it); its text and probe: NO FORM.
--
-- table 0: Protokoll (count 4), pid : 0..4194304
-- lock 0: Schutz (rank 1) guards Protokoll
-- fn merke (holds; writes Protokoll)
-- fn ende_wenn (holds; writes)
-- gate 0: getpid (0 parameters; answers 1..4194304)
-- gate 1: exit_group (1 parameters; answers never)
import Grammatik.ZielOrtGeraetSem
import Grammatik.SperreSem
import Grammatik.Zielsatz.Akzeptiert
import Grammatik.Zielsatz.Beweis
import Grammatik.Zielsatz.BeweisAtomar
import Grammatik.Zielsatz.Spec

namespace Gabbro.Grammatik

namespace G174_tor_im_modell_oblig

inductive GTab where
  | Protokoll
  deriving DecidableEq

inductive GLock where
  | Schutz
  deriving DecidableEq

inductive GProtokollFeld where
  | pid
  deriving DecidableEq

inductive GAx where
  | getpid
  | exit_group
  deriving DecidableEq

inductive GAnn where
  | a10
  | linux_getpid
  | linux_exit_group
  deriving DecidableEq

inductive GFn where
  | merke
  | ende_wenn
  deriving DecidableEq

def gSig_merke : Signatur GTab Empty GLock Empty where
  params := [.index 4]
  erg := none
  gruende := 0
  haelt := []
  boden := some 1
  schreibt := fun _ => true
  gschreibt := fun e => nomatch e
  konsumiert := []
  produziert := []

def gSig_ende_wenn : Signatur GTab Empty GLock Empty where
  params := [.bool]
  erg := none
  gruende := 0
  haelt := []
  boden := some 2
  schreibt := fun _ => false
  gschreibt := fun e => nomatch e
  konsumiert := []
  produziert := []

abbrev gD : Deklaration where
  Tab := GTab
  decTab := inferInstance
  count := fun | .Protokoll => 4
  Feld := fun | .Protokoll => GProtokollFeld
  decFeld := fun | .Protokoll => inferInstance
  typ := fun | .Protokoll, .pid => ((.int 0 4194304))
  erlaubt := fun _ _ _ _ => false
  tabNr := fun | 0 => some GTab.Protokoll | _ => none
  Glob := Empty
  decGlob := inferInstance
  gtyp := fun e => nomatch e
  nutzlast := fun e => nomatch e
  atomar := fun e => nomatch e
  geteilt := fun | .Protokoll => true
  ggeteilt := fun e => nomatch e
  Lock := GLock
  decLock := inferInstance
  rang := fun | .Schutz => 1
  maskiert := fun _ => false
  Marke := Empty
  decMarke := inferInstance
  stufen := fun e => nomatch e
  braucht := fun | .Protokoll => [.inl GLock.Schutz]
  gbraucht := fun e => nomatch e
  eigner := fun _ => []
  Fn := GFn
  sig := fun | .merke => 0 | .ende_wenn => 1
  sigNr := fun | 0 => gSig_merke | 1 => gSig_ende_wenn | _ => gSig_ende_wenn
  eigner_nie_erzeugt := fun _ _ _ _ h => by simp at h
  Inv := Empty
  traeger := fun e => nomatch e
  invs := []
  Ax := GAx
  aparams := fun | .getpid => [] | .exit_group => [(.int 0 18446744073709551615)]
  aerg := fun | .getpid => some ((.int 1 4194304)) | .exit_group => some .never
  aschreibt := fun _ _ => false
  agschreibt := fun _ _ => false
  Reg := Empty
  rtyp := fun e => nomatch e
  rklasse := fun e => nomatch e
  spiegel := fun e => nomatch e
  rzusage := fun e => nomatch e
  Annahme := GAnn
  a10 := GAnn.a10
  geteilt_bewacht := fun t => by cases t <;> decide
  invarianten_gehalten := fun _ i => nomatch i
  ggeteilt_bewacht := fun e => nomatch e

abbrev gCtx_merke : Ctx := [.index 4]
def g_merke : gD.Fn := GFn.merke
abbrev gCtx_ende_wenn : Ctx := [.bool]
def g_ende_wenn : gD.Fn := GFn.ende_wenn

abbrev gL_merke : List (Res gD) := []
abbrev gL_ende_wenn : List (Res gD) := []
abbrev gL_merke_in_Schutz : List (Res gD) := [Res.held (D := gD) GLock.Schutz]

theorem gDarf_merke_in_Schutz_Protokoll : darf gD GTab.Protokoll gL_merke_in_Schutz := by unfold darf; decide

def gBody_merke : Endblock gD (vertragVon gD g_merke) false gCtx_merke gL_merke :=
  (.cons (.locks GLock.Schutz (fun M => by cases M <;> decide) (.bindAxiom GAx.getpid .nil rfl (fun _ h => nomatch h) (fun _ h => nomatch h) (fun _ h => nomatch h) (fun _ h => nomatch h) (.cons (.assignSlot GTab.Protokoll GProtokollFeld.pid ((.var (.dort .hier))) ((.weiter (by decide) (by decide) (.var .hier)) : Expr gD ((.int 1 4194304) :: gCtx_merke) gL_merke_in_Schutz (.int 0 4194304)) (by decide) gDarf_merke_in_Schutz_Protokoll) .nil))) (.ret .keine (List.Perm.refl _)))

def gBody_ende_wenn : Endblock gD (vertragVon gD g_ende_wenn) false gCtx_ende_wenn gL_ende_wenn :=
  (.cons (.ite (.var .hier) (.bindAxiom GAx.exit_group (.cons ((.weiter (by decide) (by decide) (((.lit 1)) : Expr gD gCtx_ende_wenn gL_ende_wenn (.int 1 1))) : Expr gD gCtx_ende_wenn gL_ende_wenn (.int 0 18446744073709551615)) .nil) rfl (fun _ h => nomatch h) (fun _ h => nomatch h) (fun _ h => nomatch h) (fun _ h => nomatch h) .nil) .nil) (.ret .keine (List.Perm.refl _)))

def gP : Programm gD where
  invariante := fun i => nomatch i
  requires
    | .merke => .wahr
    | .ende_wenn => .wahr
  ensures
    | .merke => .wahr
    | .ende_wenn => .wahr
  rumpf
    | .merke => gBody_merke
    | .ende_wenn => gBody_ende_wenn

def gFs : List gD.Fn := [g_merke, g_ende_wenn]

def gLs : List gD.Lock := [GLock.Schutz]

def gCs : List (gD.Tab ⊕ gD.Glob) := [(.inl GTab.Protokoll)]

example : programmImFragmentG gP gFs = true := by decide

-- No `fussOrtGB` check: some accessed carrier is taken in a
-- `locks` block (or written elsewhere unguarded), so the old
-- signature-held footprint does not apply. The applicable check
-- is the flagship's `FussS`/`fussSperreB`, which has no Rust rule.

-- The lock invariant family `gS` (`SperrInv`, `SperreSem.lean`):
-- lock Schutz: no invariant (arm `fun _ => true`)
def gS : SperrInv gD where
  orte := fun | .Schutz => [.inl GTab.Protokoll]
  inv := fun | .Schutz => fun _ => true

example : ((gS.orte GLock.Schutz).elem (.inl GTab.Protokoll) = true) := by decide
example : ((gD.braucht GTab.Protokoll).elem (Sum.inl GLock.Schutz) = true) := by decide

-- The declared initial memory (`Speicher gD`): every slot at zero,
-- every global at its DECLARED initialiser (a `static` names one).
def gSp0 : Speicher gD :=
  ⟨(fun t _ f => match t, f with | .Protokoll, .pid => ⟨0, by decide, by decide⟩), (fun g => nomatch g)⟩

def gE : Zielsatz.Einheit gD where
  P := gP
  S := gS
  Q := fun _ _ _ => true
  starts := []
  sp0 := gSp0

-- THE USER'S OBLIGATION (stated, not discharged).
--
-- `NutzerPflichtA gE`: the bodies' logic WITH THE ATOMIC RELY (`LogikPflichtA`
-- -- per function and at EVERY `forever` budget the body triple against
-- every value a read of a shared atomic of the unit may return, with caller
-- duty and no `logik` outcome, owed invariants at value AND reason exits)
-- and the start obligation (`StartPflicht` -- every lock invariant at
-- `gE.sp0`, every declared start's `requires` there with its declared
-- arguments). On a unit without a shared atomic it is `NutzerPflicht gE`.
-- A `def` with no proof: the proof is the user's job. Stated through the
-- IMPORTED definition `NutzerPflichtA`; its body is never copied here.
def nutzerPflicht : Prop := Zielsatz.NutzerPflichtA gE

-- The member lists are complete (the `Aufzaehlung`s the goal theorem
-- quantifies over), decided here so the closing theorem below needs no
-- program fact beyond the user's obligation.
theorem gFs_voll : ∀ g : gD.Fn, g ∈ gFs := by
  intro g
  cases g <;> decide

theorem gLs_voll : ∀ L : gD.Lock, L ∈ gLs := by
  intro L
  cases L <;> decide

-- Carriers are tables or globals (lane 198 exports `static mut`
-- globals; a unit without one has `Glob := Empty`), and each arm
-- closes by cases over its constructors. `simp [gCs]`
-- and not `decide`: `DecidableEq (gD.Tab ⊕ gD.Glob)` does not unfold
-- the `gD` declaration during instance search (measured on 104/108:
-- `failed to synthesize Decidable (Sum.inl … ∈ gCs)`), while `simp`
-- rewrites membership over the literal list to constructor equalities.
theorem gCs_voll : ∀ c : gD.Tab ⊕ gD.Glob, c ∈ gCs := by
  intro c
  cases c with
  | inl t => cases t <;> simp [gCs]
  | inr g => cases g <;> simp [gCs]

-- The checker premise, discharged here: the concrete checker of the
-- goal theorem (`akzeptiertX_pruefer`, the Bool `AkzeptiertX`) accepts
-- this program on these lists. Where it does not, this `decide` fails --
-- loudly, not wrongly.
theorem gCheck : Zielsatz.akzeptiertX_pruefer.akzeptiert gE gFs gLs gCs = true := by decide

-- THE CLOSING THEOREM: the conclusion of `GabbroZiel` for this program on
-- every run of machine GX with every thread live (`gabbro_ziel_gx`). The
-- checker premise travels discharged (`gCheck`); the user's obligation
-- stays open as a hypothesis -- that is the point. Apply it once
-- `nutzerPflicht` is proved.
theorem gP_gabbro (hN : Zielsatz.NutzerPflichtA gE) (O : Orakel gD)
    (hH : Zielsatz.HardwareAnnahmen O gE.Q) (passes : Nat)
    (sp : Speicher gD.mitRuhe)
    (init : Faden → Σ f : gD.mitRuhe.Fn, Env gD.mitRuhe (gD.mitRuhe.params f))
    (hL : Zielsatz.Laufzeit gE sp init) (M : RufMaschineG gD.mitRuhe)
    (hr : RufErreichbarGX gE.P.mitRuhe O.mitRuhe passes (Zielsatz.GeteiltV (D := gD) gE.P gE.ws)
      (RufStartG gE.P.mitRuhe sp init) M) :
    Zielsatz.ZielX gE.P.mitRuhe gE.S.mitRuhe O.mitRuhe passes (Zielsatz.GeteiltV (D := gD) gE.P gE.ws)
      (RufStartG gE.P.mitRuhe sp init) M :=
  Zielsatz.gabbro_ziel_gx Zielsatz.akzeptiertX_pruefer gD gE ⟨gFs, gFs_voll⟩ ⟨gLs, gLs_voll⟩ ⟨gCs, gCs_voll⟩
    gCheck hN O hH passes sp init hL M hr

-- THE CLOSING THEOREM ON THE THREAD MACHINE: `GabbroZiel` itself for this
-- program -- `ZielFX` on every reachable thread machine over GX (run-time
-- spawns and joins included), from any set of initially live threads.
theorem gP_gabbro_f (hN : Zielsatz.NutzerPflichtA gE) (O : Orakel gD)
    (hH : Zielsatz.HardwareAnnahmen O gE.Q) (passes : Nat)
    (sp : Speicher gD.mitRuhe)
    (init : Faden → Σ f : gD.mitRuhe.Fn, Env gD.mitRuhe (gD.mitRuhe.params f))
    (hL : Zielsatz.Laufzeit gE sp init) (lebt0 : Faden → Bool)
    (K : FadenMaschine gD.mitRuhe)
    (hK : FadenErreichbarX gE.P.mitRuhe O.mitRuhe passes (Zielsatz.GeteiltV (D := gD) gE.P gE.ws)
      (FadenStart gE.P.mitRuhe sp init lebt0) K) :
    Zielsatz.ZielFX gE.P.mitRuhe gE.S.mitRuhe O.mitRuhe passes (Zielsatz.GeteiltV (D := gD) gE.P gE.ws)
      (RufStartG gE.P.mitRuhe sp init) K :=
  Zielsatz.gabbro_ziel Zielsatz.akzeptiertX_pruefer gD gE ⟨gFs, gFs_voll⟩ ⟨gLs, gLs_voll⟩ ⟨gCs, gCs_voll⟩
    gCheck hN O hH passes sp init hL lebt0 K hK

-- RELEASE OBLIGATIONS (stated, not discharged -- O12).
--
-- At every `locks L { ... }` exit the lock invariant of `L` must hold
-- again, and it must follow from what the section's callees PROMISE
-- (their `ensures`), not from what their bodies happen to do. What does
-- not follow is refused with `N511` (`freigabe_pruef.rs`); the rows below
-- state the same verdict per section (`beurteile`).
-- Each row below is syntactic, one-sided and order-aware (see
-- `crates/gabbro-check/src/freigabe.rs`): the invariant must follow from
-- the acquire frame, the section's own writes and what the section's
-- callees PROMISE (their `ensures`), never their bodies. `RELEASE HOLDS
-- (syntactic)` is not a proof, while `RELEASE UNPROVED` names the exact gap.
-- No lock carries an invariant -- nothing is owed at any release.
end G174_tor_im_modell_oblig

end Gabbro.Grammatik
