-- GENERATED by `gabbro obligations --g beispiele/59-eintritt-nimmt-maskierte-sperre.gab` (lean-g export plus the stated obligation) -- do not edit.
-- A mechanical export of the checked unit as a G program term
-- (`Programm gD`, the syntax `RufMaschineG.lean` runs).
--
-- NO FORM in G (accepted and dropped, each named): the module
-- wrapper; named constants (inlined at every use); bare carrier
-- widths (a bare word travels as its full range); pointer address
-- spaces; lock hold budgets;
-- the `reads` effects; `costs`; the `deadline` date with its `arch`
-- machine and `falsifier` probe (an environment promise, dropped
-- like `costs`); the `by unvisited`/`by consuming`
-- run form, the `decreases` witness and the `touches` clause of a
-- `traverse` (static annotations, like `costs`); `by ops` on a field
-- (a writer discipline the checker holds); `mut` on a `let`;
-- `pub` and `opaque` (both are unit-boundary rules, and
-- `Deklaration` has no boundary -- `pub` added 2026-09-15 after
-- being dropped here and named nowhere, which is the one thing
-- this ledger exists to prevent; `opaque` the same day, when its
-- alias started to travel as its range);
-- `concurrent` (its members travel as the declared starts
-- `gE.starts`; every start is parameterless, its argument list
-- `.nil`); `entry`/`boot` (the vector, the registers, the steps:
-- NO FORM; only the dispatch root travels, as a declared start
-- where exportable).
--
-- table 0: Takte (count 64), stand : 0..18446744073709551615
-- table 1: Auftraege (count 16), stand : 0..18446744073709551615
-- lock 0: TAKT (rank 0) guards Takte
-- lock 1: RING (rank 0) guards Auftraege
-- fn zaehle (holds TAKT; writes Takte)
-- fn takt_verteiler (holds; writes Takte)
-- fn bearbeite (holds RING; writes Auftraege)
-- fn ruf_verteiler (holds; writes Auftraege)
-- start 0: takt_verteiler
-- start 1: ruf_verteiler
import Grammatik.ZielOrtGeraetSem
import Grammatik.SperreSem
import Grammatik.Zielsatz.Akzeptiert
import Grammatik.Zielsatz.Beweis
import Grammatik.Zielsatz.Spec

namespace Gabbro.Grammatik

namespace G59_eintritt_nimmt_maskierte_sperre_oblig

inductive GTab where
  | Takte
  | Auftraege
  deriving DecidableEq

inductive GLock where
  | TAKT
  | RING
  deriving DecidableEq

inductive GTakteFeld where
  | stand
  deriving DecidableEq

inductive GAuftraegeFeld where
  | stand
  deriving DecidableEq

inductive GFn where
  | zaehle
  | takt_verteiler
  | bearbeite
  | ruf_verteiler
  deriving DecidableEq

def gSig_zaehle : Signatur GTab Empty GLock Empty where
  params := [.index 64]
  erg := none
  gruende := 0
  haelt := [GLock.TAKT]
  boden := some 1
  schreibt := fun | .Takte => true | _ => false
  gschreibt := fun e => nomatch e
  konsumiert := []
  produziert := []

def gSig_takt_verteiler : Signatur GTab Empty GLock Empty where
  params := []
  erg := none
  gruende := 0
  haelt := []
  boden := some 0
  schreibt := fun | .Takte => true | _ => false
  gschreibt := fun e => nomatch e
  konsumiert := []
  produziert := []

def gSig_bearbeite : Signatur GTab Empty GLock Empty where
  params := [.index 16]
  erg := none
  gruende := 0
  haelt := [GLock.RING]
  boden := some 1
  schreibt := fun | .Auftraege => true | _ => false
  gschreibt := fun e => nomatch e
  konsumiert := []
  produziert := []

def gSig_ruf_verteiler : Signatur GTab Empty GLock Empty where
  params := []
  erg := none
  gruende := 0
  haelt := []
  boden := some 0
  schreibt := fun | .Auftraege => true | _ => false
  gschreibt := fun e => nomatch e
  konsumiert := []
  produziert := []

abbrev gD : Deklaration where
  Tab := GTab
  decTab := inferInstance
  count := fun | .Takte => 64 | .Auftraege => 16
  Feld := fun | .Takte => GTakteFeld | .Auftraege => GAuftraegeFeld
  decFeld := fun | .Takte => inferInstance | .Auftraege => inferInstance
  typ := fun | .Takte, .stand => ((.int 0 18446744073709551615)) | .Auftraege, .stand => ((.int 0 18446744073709551615))
  erlaubt := fun _ _ _ _ => false
  tabNr := fun | 0 => some GTab.Takte | 1 => some GTab.Auftraege | _ => none
  Glob := Empty
  decGlob := inferInstance
  gtyp := fun e => nomatch e
  nutzlast := fun e => nomatch e
  atomar := fun e => nomatch e
  geteilt := fun | .Takte => true | .Auftraege => true
  ggeteilt := fun e => nomatch e
  Lock := GLock
  decLock := inferInstance
  rang := fun | .TAKT => 0 | .RING => 0
  maskiert := fun | .TAKT => true | .RING => false
  Marke := Empty
  decMarke := inferInstance
  stufen := fun e => nomatch e
  braucht := fun | .Takte => [.inl GLock.TAKT] | .Auftraege => [.inl GLock.RING]
  gbraucht := fun e => nomatch e
  eigner := fun _ => []
  Fn := GFn
  sig := fun | .zaehle => 0 | .takt_verteiler => 1 | .bearbeite => 2 | .ruf_verteiler => 3
  sigNr := fun | 0 => gSig_zaehle | 1 => gSig_takt_verteiler | 2 => gSig_bearbeite | 3 => gSig_ruf_verteiler | _ => gSig_ruf_verteiler
  eigner_nie_erzeugt := fun _ _ _ _ h => by simp at h
  Inv := Empty
  traeger := fun e => nomatch e
  invs := []
  Ax := Empty
  aparams := fun e => nomatch e
  aerg := fun e => nomatch e
  aschreibt := fun e => nomatch e
  agschreibt := fun e => nomatch e
  Reg := Empty
  rtyp := fun e => nomatch e
  rklasse := fun e => nomatch e
  spiegel := fun e => nomatch e
  rzusage := fun e => nomatch e
  Annahme := Unit
  a10 := ()
  geteilt_bewacht := fun t => by cases t <;> decide
  invarianten_gehalten := fun _ i => nomatch i
  ggeteilt_bewacht := fun e => nomatch e

abbrev gCtx_zaehle : Ctx := [.index 64]
def g_zaehle : gD.Fn := GFn.zaehle
abbrev gCtx_takt_verteiler : Ctx := []
def g_takt_verteiler : gD.Fn := GFn.takt_verteiler
abbrev gCtx_bearbeite : Ctx := [.index 16]
def g_bearbeite : gD.Fn := GFn.bearbeite
abbrev gCtx_ruf_verteiler : Ctx := []
def g_ruf_verteiler : gD.Fn := GFn.ruf_verteiler

abbrev gL_zaehle : List (Res gD) := [Res.held (D := gD) GLock.TAKT]
abbrev gL_takt_verteiler : List (Res gD) := []
abbrev gL_bearbeite : List (Res gD) := [Res.held (D := gD) GLock.RING]
abbrev gL_ruf_verteiler : List (Res gD) := []
abbrev gL_takt_verteiler_in_TAKT : List (Res gD) := [Res.held (D := gD) GLock.TAKT]
abbrev gL_ruf_verteiler_in_RING : List (Res gD) := [Res.held (D := gD) GLock.RING]

theorem gDarf_bearbeite_Auftraege : darf gD GTab.Auftraege gL_bearbeite := by unfold darf; decide
theorem gDarf_zaehle_Takte : darf gD GTab.Takte gL_zaehle := by unfold darf; decide

theorem gHp_takt_verteiler_in_TAKT_zaehle : RufPasst gD (vertragVon gD g_takt_verteiler) (gD.signatur g_zaehle) gL_takt_verteiler_in_TAKT where
  hw := fun t => by cases t <;> decide
  hg := fun g => nomatch g
  hk := ⟨[], List.Perm.refl [], by simp⟩
  hh := fun L => by cases L <;> decide
  hx := fun L hL hn => by cases L <;> (first | exact absurd (by decide) hn | exact absurd hL (by decide))
  hb := fun c h => by have hV : (vertragVon gD g_takt_verteiler).boden = some 0 := rfl; rw [hV] at h; cases h; exact ⟨1, rfl, by decide⟩

theorem gHp_ruf_verteiler_in_RING_bearbeite : RufPasst gD (vertragVon gD g_ruf_verteiler) (gD.signatur g_bearbeite) gL_ruf_verteiler_in_RING where
  hw := fun t => by cases t <;> decide
  hg := fun g => nomatch g
  hk := ⟨[], List.Perm.refl [], by simp⟩
  hh := fun L => by cases L <;> decide
  hx := fun L hL hn => by cases L <;> (first | exact absurd (by decide) hn | exact absurd hL (by decide))
  hb := fun c h => by have hV : (vertragVon gD g_ruf_verteiler).boden = some 0 := rfl; rw [hV] at h; cases h; exact ⟨1, rfl, by decide⟩

def gBody_zaehle : Endblock gD (vertragVon gD g_zaehle) false gCtx_zaehle gL_zaehle :=
  (.cons (.assignSlot GTab.Takte GTakteFeld.stand ((.var .hier)) ((.weiter (by decide) (by decide) (((.lit 1)) : Expr gD gCtx_zaehle gL_zaehle (.int 1 1))) : Expr gD gCtx_zaehle gL_zaehle (.int 0 18446744073709551615)) (by decide) gDarf_zaehle_Takte) (.ret .keine (List.Perm.refl _)))

def gBody_takt_verteiler : Endblock gD (vertragVon gD g_takt_verteiler) false gCtx_takt_verteiler gL_takt_verteiler :=
  (.cons (.locks GLock.TAKT (fun M => by cases M <;> decide) (.cons (.call g_zaehle (.cons ((.weiter (by decide) (by decide) (.lit 0) : Expr gD gCtx_takt_verteiler gL_takt_verteiler_in_TAKT (.index (gD.count GTab.Takte)))) .nil) gHp_takt_verteiler_in_TAKT_zaehle rfl) .nil)) (.ret .keine (List.Perm.refl _)))

def gBody_bearbeite : Endblock gD (vertragVon gD g_bearbeite) false gCtx_bearbeite gL_bearbeite :=
  (.cons (.assignSlot GTab.Auftraege GAuftraegeFeld.stand ((.var .hier)) ((.weiter (by decide) (by decide) (((.lit 1)) : Expr gD gCtx_bearbeite gL_bearbeite (.int 1 1))) : Expr gD gCtx_bearbeite gL_bearbeite (.int 0 18446744073709551615)) (by decide) gDarf_bearbeite_Auftraege) (.ret .keine (List.Perm.refl _)))

def gBody_ruf_verteiler : Endblock gD (vertragVon gD g_ruf_verteiler) false gCtx_ruf_verteiler gL_ruf_verteiler :=
  (.cons (.locks GLock.RING (fun M => by cases M <;> decide) (.cons (.call g_bearbeite (.cons ((.weiter (by decide) (by decide) (.lit 0) : Expr gD gCtx_ruf_verteiler gL_ruf_verteiler_in_RING (.index (gD.count GTab.Auftraege)))) .nil) gHp_ruf_verteiler_in_RING_bearbeite rfl) .nil)) (.ret .keine (List.Perm.refl _)))

def gP : Programm gD where
  invariante := fun i => nomatch i
  requires
    | .zaehle => .wahr
    | .takt_verteiler => .wahr
    | .bearbeite => .wahr
    | .ruf_verteiler => .wahr
  ensures
    | .zaehle => .wahr
    | .takt_verteiler => .wahr
    | .bearbeite => .wahr
    | .ruf_verteiler => .wahr
  rumpf
    | .zaehle => gBody_zaehle
    | .takt_verteiler => gBody_takt_verteiler
    | .bearbeite => gBody_bearbeite
    | .ruf_verteiler => gBody_ruf_verteiler

def gFs : List gD.Fn := [g_zaehle, g_takt_verteiler, g_bearbeite, g_ruf_verteiler]

def gLs : List gD.Lock := [GLock.TAKT, GLock.RING]

def gCs : List (gD.Tab ⊕ gD.Glob) := [(.inl GTab.Takte), (.inl GTab.Auftraege)]

example : programmImFragmentG gP gFs = true := by decide

example : fussOrtGB gP gFs = true := by decide

-- The lock invariant family `gS` (`SperrInv`, `SperreSem.lean`):
-- lock TAKT: no invariant (arm `fun _ => true`)
-- lock RING: no invariant (arm `fun _ => true`)
def gS : SperrInv gD where
  orte := fun | .TAKT => [.inl GTab.Takte] | .RING => [.inl GTab.Auftraege]
  inv := fun | .TAKT => fun _ => true | .RING => fun _ => true

example : ((gS.orte GLock.TAKT).elem (.inl GTab.Takte) = true) := by decide
example : ((gD.braucht GTab.Takte).elem (Sum.inl GLock.TAKT) = true) := by decide
example : ((gS.orte GLock.RING).elem (.inl GTab.Auftraege) = true) := by decide
example : ((gD.braucht GTab.Auftraege).elem (Sum.inl GLock.RING) = true) := by decide

-- The declared initial memory (`Speicher gD`): every slot at zero,
-- every global at its DECLARED initialiser (a `static` names one).
def gSp0 : Speicher gD :=
  ⟨(fun t _ f => match t, f with | .Takte, .stand => ⟨0, by decide, by decide⟩ | .Auftraege, .stand => ⟨0, by decide, by decide⟩), (fun g => nomatch g)⟩

def gE : Zielsatz.Einheit gD where
  P := gP
  S := gS
  Q := fun _ _ _ => true
  starts := [⟨g_takt_verteiler, .nil⟩, ⟨g_ruf_verteiler, .nil⟩]
  sp0 := gSp0

-- THE USER'S OBLIGATION (stated, not discharged).
--
-- `NutzerPflicht gE`: the bodies' logic (`LogikPflicht` -- per function
-- and at EVERY `forever` budget the body triple with caller duty and no
-- `logik` outcome, owed invariants at value AND reason exits) and the
-- start obligation (`StartPflicht` -- every lock invariant at `gE.sp0`,
-- every declared start's `requires` there with its declared arguments).
-- A `def` with no proof: the proof is the user's job. Stated through the
-- IMPORTED definition `NutzerPflicht`; its body is never copied here.
def nutzerPflicht : Prop := Zielsatz.NutzerPflicht gE

-- The member lists are complete (the `Aufzaehlung`s the goal theorem
-- quantifies over), decided here so the closing theorem below needs no
-- program fact beyond the user's obligation.
theorem gFs_voll : ∀ g : gD.Fn, g ∈ gFs := by
  intro g
  cases g <;> decide

theorem gLs_voll : ∀ L : gD.Lock, L ∈ gLs := by
  intro L
  cases L <;> decide

-- Carriers are tables or globals (lane 198 exports `static mut`
-- globals; a unit without one has `Glob := Empty`), and each arm
-- closes by cases over its constructors. `simp [gCs]`
-- and not `decide`: `DecidableEq (gD.Tab ⊕ gD.Glob)` does not unfold
-- the `gD` declaration during instance search (measured on 104/108:
-- `failed to synthesize Decidable (Sum.inl … ∈ gCs)`), while `simp`
-- rewrites membership over the literal list to constructor equalities.
theorem gCs_voll : ∀ c : gD.Tab ⊕ gD.Glob, c ∈ gCs := by
  intro c
  cases c with
  | inl t => cases t <;> simp [gCs]
  | inr g => cases g <;> simp [gCs]

-- The checker premise, discharged here: the concrete checker of the
-- goal theorem (`akzeptiert_pruefer`) accepts this program on these
-- lists. Where it does not, this `decide` fails -- loudly, not wrongly.
theorem gCheck : akzeptiert_pruefer.akzeptiert gE gFs gLs gCs = true := by decide

-- THE CLOSING THEOREM: the conclusion of `GabbroZiel` for this program,
-- derived from `gabbro_ziel`. The checker premise travels discharged
-- (`gCheck`); the user's obligation stays open as a hypothesis -- that
-- is the point. Apply it once `nutzerPflicht` is proved.
theorem gP_gabbro (hN : Zielsatz.NutzerPflicht gE) (O : Orakel gD)
    (hH : Zielsatz.HardwareAnnahmen O gE.Q) (passes : Nat)
    (sp : Speicher gD.mitRuhe)
    (init : Faden → Σ f : gD.mitRuhe.Fn, Env gD.mitRuhe (gD.mitRuhe.params f))
    (hL : Zielsatz.Laufzeit gE sp init) (M : RufMaschineG gD.mitRuhe)
    (hr : RufErreichbarG gE.P.mitRuhe O.mitRuhe passes (RufStartG gE.P.mitRuhe sp init) M) :
    Zielsatz.Ziel gE.P.mitRuhe gE.S.mitRuhe O.mitRuhe passes (RufStartG gE.P.mitRuhe sp init) M :=
  Zielsatz.gabbro_ziel_g akzeptiert_pruefer gD gE ⟨gFs, gFs_voll⟩ ⟨gLs, gLs_voll⟩ ⟨gCs, gCs_voll⟩
    gCheck hN O hH passes sp init hL M hr

-- RELEASE OBLIGATIONS (stated, not discharged -- O12).
--
-- At every `locks L { ... }` exit the lock invariant of `L` must hold
-- again, and it must follow from what the section's callees PROMISE
-- (their `ensures`), not from what their bodies happen to do. No checker
-- rule refuses a section whose callees cannot re-establish it, so such
-- a section is checker-clean and still leaves `NutzerPflicht` unproved.
-- Each row below is syntactic, one-sided and order-aware (see
-- `crates/gabbro-check/src/freigabe.rs`): a write or a callee write after
-- the last promise of a cell breaks it. `RELEASE HOLDS (syntactic)` is
-- not a proof, while `RELEASE UNPROVED` names the exact gap.
-- No lock carries an invariant -- nothing is owed at any release.
end G59_eintritt_nimmt_maskierte_sperre_oblig

end Gabbro.Grammatik
