-- GENERATED by `gabbro obligations --g beispiele/gift/700-lesen-ohne-klausel.gab` (lean-g export plus the stated obligation) -- do not edit.
-- A mechanical export of the checked unit as a G program term
-- (`Programm gD`, the syntax `RufMaschineG.lean` runs).
--
-- NO FORM in G (accepted and dropped, each named): the module
-- wrapper; named constants (inlined at every use); bare carrier
-- widths (a bare word travels as its full range); pointer address
-- spaces; lock hold budgets;
-- the `reads` effects; `costs`; the `by unvisited`/`by consuming`
-- run form, the `decreases` witness and the `touches` clause of a
-- `traverse` (static annotations, like `costs`); `by ops` on a field
-- (a writer discipline the checker holds); `mut` on a `let`;
-- `pub` and `opaque` (both are unit-boundary rules, and
-- `Deklaration` has no boundary -- `pub` added 2026-09-15 after
-- being dropped here and named nowhere, which is the one thing
-- this ledger exists to prevent; `opaque` the same day, when its
-- alias started to travel as its range);
-- `concurrent` (its members travel as the declared starts
-- `gE.starts`; every start is parameterless, its argument list
-- `.nil`); `entry`/`boot` (the vector, the registers, the steps:
-- NO FORM; only the dispatch root travels, as a declared start
-- where exportable).
--
-- static 0: g : 0..4294967295 = 0
-- fn liest_ohne_klausel (holds; writes)
import Grammatik.ZielOrtGeraetSem
import Grammatik.SperreSem
import Grammatik.Zielsatz.Akzeptiert
import Grammatik.Zielsatz.Beweis
import Grammatik.Zielsatz.Spec

namespace Gabbro.Grammatik

namespace G700_lesen_ohne_klausel_oblig

abbrev GTab := Empty

abbrev GLock := Empty

inductive GGlob where
  | g
  deriving DecidableEq

inductive GFn where
  | liest_ohne_klausel
  deriving DecidableEq

def gSig_liest_ohne_klausel : Signatur GTab GGlob GLock Empty where
  params := []
  erg := some ((.int 0 4294967295))
  gruende := 0
  haelt := []
  boden := none
  schreibt := fun _ => false
  gschreibt := fun _ => false
  konsumiert := []
  produziert := []

abbrev gD : Deklaration where
  Tab := GTab
  decTab := inferInstance
  count := fun t => nomatch t
  Feld := fun t => nomatch t
  decFeld := fun t => nomatch t
  typ := fun t => nomatch t
  erlaubt := fun _ _ _ _ => false
  tabNr := fun _ => none
  Glob := GGlob
  decGlob := inferInstance
  gtyp := fun | .g => (.int 0 4294967295)
  nutzlast := fun _ => []
  atomar := fun _ => false
  geteilt := fun t => nomatch t
  ggeteilt := fun | .g => false
  Lock := GLock
  decLock := inferInstance
  rang := fun L => nomatch L
  maskiert := fun _ => false
  Marke := Empty
  decMarke := inferInstance
  stufen := fun e => nomatch e
  braucht := fun t => nomatch t
  gbraucht := fun | .g => []
  eigner := fun _ => []
  Fn := GFn
  sig := fun | .liest_ohne_klausel => 0
  sigNr := fun | 0 => gSig_liest_ohne_klausel | _ => gSig_liest_ohne_klausel
  eigner_nie_erzeugt := fun _ _ _ _ h => by simp at h
  Inv := Empty
  traeger := fun e => nomatch e
  invs := []
  Ax := Empty
  aparams := fun e => nomatch e
  aerg := fun e => nomatch e
  aschreibt := fun e => nomatch e
  agschreibt := fun e => nomatch e
  Reg := Empty
  rtyp := fun e => nomatch e
  rklasse := fun e => nomatch e
  spiegel := fun e => nomatch e
  rzusage := fun e => nomatch e
  Annahme := Unit
  a10 := ()
  geteilt_bewacht := fun t => by cases t <;> decide
  invarianten_gehalten := fun _ i => nomatch i
  ggeteilt_bewacht := fun g => by cases g <;> decide

abbrev gCtx_liest_ohne_klausel : Ctx := []
def g_liest_ohne_klausel : gD.Fn := GFn.liest_ohne_klausel

abbrev gL_liest_ohne_klausel : List (Res gD) := []

theorem gGDarf_liest_ohne_klausel_g : gdarf gD GGlob.g gL_liest_ohne_klausel := by unfold gdarf; decide

def gBody_liest_ohne_klausel : Endblock gD (vertragVon gD g_liest_ohne_klausel) false gCtx_liest_ohne_klausel gL_liest_ohne_klausel :=
  (.ret (.wert (Expr.glob (D := gD) GGlob.g gGDarf_liest_ohne_klausel_g)) (List.Perm.refl _))

def gP : Programm gD where
  invariante := fun i => nomatch i
  requires
    | .liest_ohne_klausel => .wahr
  ensures
    | .liest_ohne_klausel => .wahr
  rumpf
    | .liest_ohne_klausel => gBody_liest_ohne_klausel

def gFs : List gD.Fn := [g_liest_ohne_klausel]

def gLs : List gD.Lock := []

def gCs : List (gD.Tab ⊕ gD.Glob) := [(.inr GGlob.g)]

example : programmImFragmentG gP gFs = true := by decide

example : fussOrtGB gP gFs = true := by decide

-- The lock invariant family `gS` (`SperrInv`, `SperreSem.lean`):
def gS : SperrInv gD where
  orte := fun _ => []
  inv := fun _ _ => true


-- The declared initial memory (`Speicher gD`): every slot at zero,
-- every global at its DECLARED initialiser (a `static` names one).
def gSp0 : Speicher gD :=
  ⟨(fun t => nomatch t), (fun | .g => ⟨0, by decide, by decide⟩)⟩

def gE : Zielsatz.Einheit gD where
  P := gP
  S := gS
  Q := fun _ _ _ => true
  starts := []
  sp0 := gSp0

-- THE USER'S OBLIGATION (stated, not discharged).
--
-- `NutzerPflicht gE`: the bodies' logic (`LogikPflicht` -- per function
-- and at EVERY `forever` budget the body triple with caller duty and no
-- `logik` outcome, owed invariants at value AND reason exits) and the
-- start obligation (`StartPflicht` -- every lock invariant at `gE.sp0`,
-- every declared start's `requires` there with its declared arguments).
-- A `def` with no proof: the proof is the user's job. Stated through the
-- IMPORTED definition `NutzerPflicht`; its body is never copied here.
def nutzerPflicht : Prop := Zielsatz.NutzerPflicht gE

-- The member lists are complete (the `Aufzaehlung`s the goal theorem
-- quantifies over), decided here so the closing theorem below needs no
-- program fact beyond the user's obligation.
theorem gFs_voll : ∀ g : gD.Fn, g ∈ gFs := by
  intro g
  cases g <;> decide

theorem gLs_voll : ∀ L : gD.Lock, L ∈ gLs := by
  intro L
  cases L <;> decide

-- Carriers are tables or globals (lane 198 exports `static mut`
-- globals; a unit without one has `Glob := Empty`), and each arm
-- closes by cases over its constructors. `simp [gCs]`
-- and not `decide`: `DecidableEq (gD.Tab ⊕ gD.Glob)` does not unfold
-- the `gD` declaration during instance search (measured on 104/108:
-- `failed to synthesize Decidable (Sum.inl … ∈ gCs)`), while `simp`
-- rewrites membership over the literal list to constructor equalities.
theorem gCs_voll : ∀ c : gD.Tab ⊕ gD.Glob, c ∈ gCs := by
  intro c
  cases c with
  | inl t => cases t <;> simp [gCs]
  | inr g => cases g <;> simp [gCs]

-- The checker premise, discharged here: the concrete checker of the
-- goal theorem (`akzeptiert_pruefer`) accepts this program on these
-- lists. Where it does not, this `decide` fails -- loudly, not wrongly.
theorem gCheck : akzeptiert_pruefer.akzeptiert gE gFs gLs gCs = true := by decide

-- THE CLOSING THEOREM: the conclusion of `GabbroZiel` for this program,
-- derived from `gabbro_ziel`. The checker premise travels discharged
-- (`gCheck`); the user's obligation stays open as a hypothesis -- that
-- is the point. Apply it once `nutzerPflicht` is proved.
theorem gP_gabbro (hN : Zielsatz.NutzerPflicht gE) (O : Orakel gD)
    (hH : Zielsatz.HardwareAnnahmen O gE.Q) (passes : Nat)
    (sp : Speicher gD.mitRuhe)
    (init : Faden → Σ f : gD.mitRuhe.Fn, Env gD.mitRuhe (gD.mitRuhe.params f))
    (hL : Zielsatz.Laufzeit gE sp init) (M : RufMaschineG gD.mitRuhe)
    (hr : RufErreichbarG gE.P.mitRuhe O.mitRuhe passes (RufStartG gE.P.mitRuhe sp init) M) :
    Zielsatz.Ziel gE.P.mitRuhe gE.S.mitRuhe O.mitRuhe passes (RufStartG gE.P.mitRuhe sp init) M :=
  Zielsatz.gabbro_ziel_g akzeptiert_pruefer gD gE ⟨gFs, gFs_voll⟩ ⟨gLs, gLs_voll⟩ ⟨gCs, gCs_voll⟩
    gCheck hN O hH passes sp init hL M hr

-- THE CLOSING THEOREM ON THE THREAD MACHINE: `GabbroZiel` itself for this
-- program -- `ZielF` on every reachable thread machine (run-time spawns
-- and joins included), from any set of initially live threads.
theorem gP_gabbro_f (hN : Zielsatz.NutzerPflicht gE) (O : Orakel gD)
    (hH : Zielsatz.HardwareAnnahmen O gE.Q) (passes : Nat)
    (sp : Speicher gD.mitRuhe)
    (init : Faden → Σ f : gD.mitRuhe.Fn, Env gD.mitRuhe (gD.mitRuhe.params f))
    (hL : Zielsatz.Laufzeit gE sp init) (lebt0 : Faden → Bool)
    (K : FadenMaschine gD.mitRuhe)
    (hK : FadenErreichbar gE.P.mitRuhe O.mitRuhe passes (FadenStart gE.P.mitRuhe sp init lebt0) K) :
    Zielsatz.ZielF gE.P.mitRuhe gE.S.mitRuhe O.mitRuhe passes (RufStartG gE.P.mitRuhe sp init) K :=
  Zielsatz.gabbro_ziel akzeptiert_pruefer gD gE ⟨gFs, gFs_voll⟩ ⟨gLs, gLs_voll⟩ ⟨gCs, gCs_voll⟩
    gCheck hN O hH passes sp init hL lebt0 K hK

-- RELEASE OBLIGATIONS (stated, not discharged -- O12).
--
-- At every `locks L { ... }` exit the lock invariant of `L` must hold
-- again, and it must follow from what the section's callees PROMISE
-- (their `ensures`), not from what their bodies happen to do. What does
-- not follow is refused with `N511` (`freigabe_pruef.rs`); the rows below
-- state the same verdict per section (`beurteile`).
-- Each row below is syntactic, one-sided and order-aware (see
-- `crates/gabbro-check/src/freigabe.rs`): the invariant must follow from
-- the acquire frame, the section's own writes and what the section's
-- callees PROMISE (their `ensures`), never their bodies. `RELEASE HOLDS
-- (syntactic)` is not a proof, while `RELEASE UNPROVED` names the exact gap.
-- No lock carries an invariant -- nothing is owed at any release.
end G700_lesen_ohne_klausel_oblig

end Gabbro.Grammatik
