/* Generated by Gabbro -- https://github.com/SimonVitzethum/Gabbro
 *
 * This file was generated. Edit the .gab source, not this file.
 *
 * Gabbro is AGPL-3.0 with an additional permission: this generated file and the program it
 * belongs to are NOT a derived work of Gabbro. The permission is conditional on this notice
 * being preserved. See LIZENZ-ZUSATZ.md.
 */
#include <stdint.h>
#include <stdbool.h>
#include <stdatomic.h>
#include <math.h>

#define NFAECHER 8u

typedef struct {
    uint32_t marke;
    bool gueltig;
    uint64_t breit;
    uint8_t schmal;
} Fach_slot;

typedef struct {
    Fach_slot slots[NFAECHER];
} Fach;
/* `Fach` is addressed by NAME: the table IS the storage (beispiele/09). */
static Fach Fach_speicher;
#define Fach_NONE (NFAECHER)

typedef struct {
    uint32_t wert;
} Plan_slot;

typedef struct {
    Plan_slot slots[NFAECHER];
} Plan;
/* `Plan` is addressed by NAME: the table IS the storage (beispiele/09). */
static Plan Plan_speicher;
#define Plan_NONE (NFAECHER)

void A_nimm(void);
void A_gib(void);

void B_nimm(void);
void B_gib(void);

void rangtreu(uint32_t i, uint32_t w);

uint32_t fremd_schreiben(Fach *restrict f, uint32_t i, uint32_t w);

uint32_t lies_marke(const Fach *restrict f, uint32_t i) __attribute__((pure));

uint32_t misch(Fach *a, Fach *b, uint32_t i);

void rangtreu(uint32_t i, uint32_t w) {
    A_nimm();
    {
        B_nimm();
        {
            Fach_speicher.slots[i].marke = w;
            Plan_speicher.slots[i].wert = w;
        }
        B_gib();
    }
    A_gib();
}

uint32_t fremd_schreiben(Fach *restrict f, uint32_t i, uint32_t w) {
    f->slots[i].marke = w;
    return f->slots[i].marke;
}

uint32_t lies_marke(const Fach *restrict f, uint32_t i) {
    return f->slots[i].marke;
}

uint32_t misch(Fach *a, Fach *b, uint32_t i) {
    a->slots[i].marke = 1;
    b->slots[i].marke = 2;
    return a->slots[i].marke;
}
