//! Per-unit hosted driver generator: `gabbro build` writes one driver C file
//! per concurrent unit (lane 246).
//!
//! The emitter translates each `concurrent` member to a plain function and
//! emits no caller and no `main`; this generator writes the missing half in
//! the exact shape of `laufzeit/start.c`: one wrapper per root, one thread
//! per root, join all, the idle root present but never spawned on hosted,
//! and the lock primitives the emitter only declares (mutex on hosted).
//! The generated file is a build artefact, pinned per unit: the probe
//! compares the `concurrent { ... }` occurrences of the sources against the
//! `pthread_create` sites of the driver, BY COUNT (a multiset since fix lane
//! F4): a root added, dropped or started a different number of times without
//! regenerating fails loudly.

use std::collections::{BTreeMap, BTreeSet};

/// One declared start, resolved to the C name the emitter writes.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub struct Wurzel {
    /// Short name: the C function (`hauptA`), i.e. the last path segment.
    pub c_name: String,
    /// Full Gabbro path as declared (`hauptA` or `modul::hauptA`).
    pub gab_path: String,
}

/// One lock the driver must define (the emitter only declares it).
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub struct Sperre {
    /// Short lock name (`L`); the primitives are `<name>_nimm` / `<name>_gib`.
    pub name: String,
    /// A shared (`geteilt`) lock additionally needs `_nimm_geteilt` / `_gib_geteilt`.
    pub geteilt: bool,
}

/// **The generator's version, carried in the unit fingerprint.** The driver
/// is rendered deterministically out of the sources, so a template change
/// with unchanged sources would otherwise leave a stale driver behind a
/// valid record. Bump this on every template change; `bau.rs` mixes it into
/// the fingerprint of every unit that owns a driver.
pub const GENERATOR_KENNUNG: &str = "treiber-gen-2";

/// True for `[A-Za-z_][A-Za-z0-9_]*` (ASCII only: a Gabbro name that reaches
/// C is ASCII; anything else cannot name a C function and is refused before
/// generation, never truncated into one).
pub fn gueltiger_c_name(s: &str) -> bool {
    let mut zeichen = s.chars();
    let Some(erstes) = zeichen.next() else {
        return false;
    };
    if !(erstes.is_ascii_alphabetic() || erstes == '_') {
        return false;
    }
    zeichen.all(|c| c.is_ascii_alphanumeric() || c == '_')
}

/// Render the hosted driver for one unit.
///
/// `wurzeln` are the resolved roots in declaration order, ONE ENTRY PER
/// OCCURRENCE (fix lane F4: `concurrent { f, f }` is two starts, and the
/// accepted pool-safe duplicate must get two threads); the generator writes
/// one wrapper per distinct name and one `pthread_create` per entry.
/// `sperren` the locks to define. `nachlauf` is optional
/// unit-specific observation C after the join loop (the 124 invariant
/// checks); the plain build passes `None`, so the artefact carries the
/// runtime half only and a test harness supplies the check half. The file
/// always ends in `return 0;`, which is unreachable but valid C when
/// `nachlauf` returns itself.
///
/// The output is deterministic: same inputs, same bytes (no hashes, no
/// timestamps), so a stale driver is detectable by comparison, not by age.
pub fn erzeuge(
    einheit: &str,
    wurzeln: &[Wurzel],
    sperren: &[Sperre],
    nachlauf: Option<&str>,
) -> String {
    let mut aus = String::new();
    aus.push_str(&format!(
        "/* {einheit}.treiber.c -- GENERATED by `gabbro build` (lane 246). Do not edit.\n"
    ));
    aus.push_str(
        " *\n \
         * WHAT THIS IS. The hosted runtime driver for one concurrent unit, in the\n \
         * shape of `laufzeit/start.c`: the emitter translated each `concurrent`\n \
         * member to a plain function and emitted no caller and no `main`; this\n \
         * file starts exactly the declared roots, one thread per occurrence, and\n \
         * carries the idle root for bare metal. Regenerate after every change to the\n \
         * unit's `concurrent` sets or locks: the pin probe compares the source\n \
         * sets against the `pthread_create` sites below and fails a stale file.\n \
         *\n \
         * BUILD (from the tree root; `<ausgabe>` is the manifest's `out` dir):\n \
         *\n \
         *   cc -std=c11 -O0 -Wall -Wextra -Werror -pthread -I <ausgabe> \\\n \
         *      -DEINHEIT_INCLUDE='\"<einheit>.c\"' -o <ausgabe>/<einheit>.treiber \\\n \
         *      <ausgabe>/<einheit>.treiber.c\n \
         */\n",
    );
    aus.push_str("\n#include <pthread.h>\n#include <stdio.h>\n#include <stdlib.h>\n#include <unistd.h>\n");
    aus.push_str("\n/* -- The emitted unit -------------------------------------------------- */\n\n");
    aus.push_str("#include EINHEIT_INCLUDE\n");
    aus.push_str("\n/* -- Lock primitives: the emitter declares them, the runtime defines them.\n");
    aus.push_str(" *\n * WHY HERE. A lock is a runtime object (mutex on hosted POSIX, the ticket\n");
    aus.push_str(" * lock of NICHTINTERFERENZ.md section 10 on bare metal), never program\n");
    aus.push_str(" * text. The name on each side is the contract between them, checked by\n");
    aus.push_str(" * `cc`: a misspelt name is an undefined reference, not a silent default.\n */\n");
    let mut sortiert: Vec<&Sperre> = sperren.iter().collect();
    sortiert.sort_by(|a, b| a.name.cmp(&b.name));
    for s in sortiert {
        let n = &s.name;
        aus.push_str(&format!(
            "static pthread_mutex_t sperre_{n} = PTHREAD_MUTEX_INITIALIZER;\n\n\
             void {n}_nimm(void)\n{{\n    int rc = pthread_mutex_lock(&sperre_{n});\n\
             \x20   if (rc != 0) {{\n        fprintf(stderr, \"{n}_nimm: pthread_mutex_lock: %d\\n\", rc);\n\
             \x20       abort();\n    }}\n}}\n\n\
             void {n}_gib(void)\n{{\n    int rc = pthread_mutex_unlock(&sperre_{n});\n\
             \x20   if (rc != 0) {{\n        fprintf(stderr, \"{n}_gib: pthread_mutex_unlock: %d\\n\", rc);\n\
             \x20       abort();\n    }}\n}}\n\n"
        ));
        if s.geteilt {
            aus.push_str(&format!(
                "void {n}_nimm_geteilt(void)\n{{\n    int rc = pthread_mutex_lock(&sperre_{n});\n\
                 \x20   if (rc != 0) {{\n        fprintf(stderr, \"{n}_nimm_geteilt: pthread_mutex_lock: %d\\n\", rc);\n\
                 \x20       abort();\n    }}\n}}\n\n\
                 void {n}_gib_geteilt(void)\n{{\n    int rc = pthread_mutex_unlock(&sperre_{n});\n\
                 \x20   if (rc != 0) {{\n        fprintf(stderr, \"{n}_gib_geteilt: pthread_mutex_unlock: %d\\n\", rc);\n\
                 \x20       abort();\n    }}\n}}\n\n"
            ));
        }
    }
    aus.push_str("/* -- ROOTS: the declared starts of this unit.\n");
    aus.push_str(" *\n * WHY ONE WRAPPER PER ROOT. `pthread_create` wants `void *(*)(void *)`\n");
    aus.push_str(" * and the emitted roots are `void (*)(void)`; the wrapper is the adapter,\n");
    aus.push_str(" * and one adapter per root keeps the root's NAME at the `pthread_create`\n");
    aus.push_str(" * call site, which is what the pin probe reads. A root declared twice (a\n");
    aus.push_str(" * pool) has one adapter and one `pthread_create` site per declaration.\n */\n");
    let mut geschrieben: BTreeSet<&str> = BTreeSet::new();
    for w in wurzeln {
        let c = &w.c_name;
        // One adapter per NAME: a routine started twice (a pool) shares it, and
        // its two `pthread_create` sites below both name it.
        if !geschrieben.insert(c.as_str()) {
            continue;
        }
        aus.push_str(&format!(
            "static void *faden_{c}(void *u)\n{{\n    (void)u; /* No argument: the declared\n\
             \x20                              * starts of this unit take none. */\n    {c}();\n    return NULL;\n}}\n\n"
        ));
    }
    aus.push_str("/* N_WURZELN counts the declared starts, one per occurrence -- the probe checks it\n * against the number of members the source's `concurrent` sets name. */\n");
    aus.push_str(&format!("#define N_WURZELN {}\n", wurzeln.len()));
    aus.push_str("\n/* -- The idle root: `none` of `E.P.mitRuhe`.\n");
    aus.push_str(" *\n * WHY IT IS NEVER SPAWNED ON HOSTED. POSIX gives `main` no spare cores\n");
    aus.push_str(" * to park: `main` spawns exactly the declared roots and joins them. The\n");
    aus.push_str(" * function stands here so the shape exists in the artefact -- bare metal\n");
    aus.push_str(" * spawns one per extra core -- and `__attribute__((unused))` says that.\n");
    aus.push_str(" * Spinning here touches no Gabbro carrier, so it is invisible to the goal.\n */\n");
    aus.push_str(
        "static void *ruhe(void *u) __attribute__((unused));\n\
         static void *ruhe(void *u)\n{\n    (void)u;\n    for (;;) {\n        pause();\n\
         \x20   }\n    return NULL;\n}\n",
    );
    aus.push_str("\n/* -- main: start exactly the roots, join them. ---------------------------- */\n\nint main(void)\n{\n");
    aus.push_str("    pthread_t faden[N_WURZELN];\n    int rc;\n\n");
    // **A failed start joins what already runs** (fix lane F4, the finding review
    // G06 F6 made at `laufzeit/start_pool.c`, which this template shared): the
    // threads started before the failing one are joined before `main` returns,
    // so "join covers exactly the spawned set" holds on the error path too.
    for (i, w) in wurzeln.iter().enumerate() {
        let c = &w.c_name;
        let einsammeln = if i == 0 {
            String::new()
        } else {
            format!(
                "        for (int j = 0; j < {i}; j++) {{\n\
                 \x20           (void)pthread_join(faden[j], NULL);\n        }}\n"
            )
        };
        aus.push_str(&format!(
            "    rc = pthread_create(&faden[{i}], NULL, faden_{c}, NULL);\n    if (rc != 0) {{\n\
             \x20       fprintf(stderr, \"start: {c}: %d\\n\", rc);\n{einsammeln}\
             \x20       return 2;\n    }}\n"
        ));
    }
    aus.push_str(
        "    for (int i = 0; i < N_WURZELN; i++) {\n        rc = pthread_join(faden[i], NULL);\n\
         \x20       if (rc != 0) {\n            fprintf(stderr, \"join: thread %d: %d\\n\", i, rc);\n\
         \x20           return 2;\n        }\n    }\n",
    );
    if let Some(code) = nachlauf {
        aus.push_str("\n    /* -- Unit-specific observation (test half, not runtime). -- */\n");
        aus.push_str(code);
        if !code.ends_with('\n') {
            aus.push('\n');
        }
    }
    // **The marker stands in every driver, with or without observation.** A
    // test that appends a unit's checks does it HERE, so the build artefact
    // and the test artefact differ by exactly the appended block -- the
    // spawn, join and mutex bytes are identical, verifiable by diff.
    aus.push_str("    /* NACHLAUF: unit-specific observation goes here in test runs. */\n");
    aus.push_str("    return 0;\n}\n");
    aus
}

/// The `pthread_create` roots of a driver C file, COUNTED: every
/// `faden_<root>` named at a `pthread_create` call site, with the number of
/// sites that name it (a pool routine started twice has two sites).
///
/// Read with a plain scanner, not a C parser: the generator above is the
/// only writer, and the hand file `laufzeit/start.c` keeps the same shape
/// (one wrapper per root, the root's name at the call site) so the same
/// probe reads both.
pub fn pthread_create_zaehlung(treiber_c: &str) -> BTreeMap<String, usize> {
    let mut zaehlung = BTreeMap::new();
    let mut rest = treiber_c;
    // Only CALL SITES count (`pthread_create(` up to its `;`): with counts a
    // mention in a comment would be a thread start that does not exist.
    while let Some(i) = rest.find("pthread_create(") {
        let nach = &rest[i + "pthread_create(".len()..];
        let aufruf = &nach[..nach.find(';').unwrap_or(nach.len())];
        if let Some(j) = aufruf.find("faden_") {
            let mut name = String::new();
            for c in aufruf[j + "faden_".len()..].chars() {
                if c.is_ascii_alphanumeric() || c == '_' {
                    name.push(c);
                } else {
                    break;
                }
            }
            if !name.is_empty() {
                *zaehlung.entry(name).or_insert(0) += 1;
            }
        }
        rest = nach;
    }
    zaehlung
}

/// The declared starts of the sources as a multiset: short C name to the
/// number of `concurrent` occurrences naming it.
pub fn vorkommen<'a>(namen: impl IntoIterator<Item = &'a str>) -> BTreeMap<String, usize> {
    let mut m = BTreeMap::new();
    for n in namen {
        *m.entry(n.to_string()).or_insert(0) += 1;
    }
    m
}

/// The `#define N_WURZELN <n>` count of a driver C file, if present.
pub fn n_wurzeln(treiber_c: &str) -> Option<usize> {
    for zeile in treiber_c.lines() {
        let gekuerzt = zeile.trim();
        if let Some(rest) = gekuerzt.strip_prefix("#define N_WURZELN") {
            return rest.trim().parse::<usize>().ok();
        }
    }
    None
}

/// The pin: the source starts and the driver starts must be the same
/// MULTISET, and `N_WURZELN` must count them.
///
/// `quelle` maps the short C names of the declared roots to the number of
/// `concurrent` occurrences naming them (fix lane F4: a set pin could not see
/// a pool routine declared twice and started once). Returns the start count
/// on success; the error names both sides with their counts, so a stale
/// driver fails loudly instead of starting the wrong threads.
pub fn pin_pruefe(quelle: &BTreeMap<String, usize>, treiber_c: &str) -> Result<usize, String> {
    let treiber = pthread_create_zaehlung(treiber_c);
    let zeige = |m: &BTreeMap<String, usize>| -> String {
        m.iter()
            .map(|(n, k)| if *k == 1 { n.clone() } else { format!("{n} x{k}") })
            .collect::<Vec<_>>()
            .join(", ")
    };
    if treiber != *quelle {
        return Err(format!(
            "the driver starts other threads than the sources declare -- source: [{}], driver: [{}]. \
             Regenerate the driver: a root added, dropped or started a different number of times \
             without regenerating starts the wrong threads",
            zeige(quelle),
            zeige(&treiber)
        ));
    }
    let gesamt: usize = quelle.values().sum();
    match n_wurzeln(treiber_c) {
        Some(n) if n == gesamt => Ok(n),
        Some(n) => Err(format!(
            "N_WURZELN is {n} but the sources declare {gesamt} start(s) -- \
             the join loop would miss a thread or read past the array"
        )),
        None => Err("the driver carries no `#define N_WURZELN <n>` line".to_string()),
    }
}

#[cfg(test)]
mod treiber_tests {
    use super::{erzeuge, gueltiger_c_name, pin_pruefe, vorkommen, Sperre, Wurzel};
    use std::collections::BTreeMap;

    fn beispiel() -> (Vec<Wurzel>, Vec<Sperre>) {
        (
            vec![
                Wurzel {
                    c_name: "hauptA".to_string(),
                    gab_path: "hauptA".to_string(),
                },
                Wurzel {
                    c_name: "hauptB".to_string(),
                    gab_path: "hauptB".to_string(),
                },
            ],
            vec![Sperre {
                name: "L".to_string(),
                geteilt: false,
            }],
        )
    }

    fn menge(v: &[&str]) -> BTreeMap<String, usize> {
        vorkommen(v.iter().copied())
    }

    /// **The generator's own output holds its own pin.** If this ever fails,
    /// the writer and the probe disagree about the shape -- and the probe is
    /// what every other test trusts.
    #[test]
    fn erzeugter_treiber_haelt_pin() {
        let (wurzeln, sperren) = beispiel();
        let c = erzeuge("beispiel124", &wurzeln, &sperren, None);
        assert_eq!(pin_pruefe(&menge(&["hauptA", "hauptB"]), &c), Ok(2));
        assert!(c.contains("void L_nimm(void)"));
        assert!(c.contains("void L_gib(void)"));
        assert!(!c.contains("_nimm_geteilt"), "no shared pair without a shared lock");
        assert!(c.contains("#define N_WURZELN 2"));
        assert!(c.contains("/* NACHLAUF:"));
    }

    /// **A shared lock earns its shared pair, beside the exclusive one.**
    #[test]
    fn geteilte_sperre_bekommt_geteiltes_paar() {
        let (wurzeln, _) = beispiel();
        let sperren = vec![Sperre {
            name: "M".to_string(),
            geteilt: true,
        }];
        let c = erzeuge("einheit", &wurzeln, &sperren, None);
        assert!(c.contains("void M_nimm(void)"));
        assert!(c.contains("void M_nimm_geteilt(void)"));
        assert!(c.contains("void M_gib_geteilt(void)"));
    }

    /// **A stale driver fails loudly, in both directions.** A dropped root
    /// and an added root both name the two sets -- the refusal says what
    /// changed, not just that something did.
    #[test]
    fn abgestandener_treiber_faellt_laut() {
        let (wurzeln, sperren) = beispiel();
        let c = erzeuge("beispiel124", &wurzeln, &sperren, None);
        let gefallen = pin_pruefe(&menge(&["hauptA"]), &c).expect_err("a dropped root must fail");
        assert!(
            gefallen.contains("hauptB") && gefallen.contains("hauptA"),
            "both sets are named:\n{gefallen}"
        );
        let gefallen = pin_pruefe(&menge(&["hauptA", "hauptB", "hauptC"]), &c)
            .expect_err("an added root must fail");
        assert!(gefallen.contains("hauptC"), "the added root is named:\n{gefallen}");
    }

    /// **The count is checked too, not just the set.** A hand edit that adds
    /// a thread but forgets `N_WURZELN` would join the wrong array.
    #[test]
    fn vergessener_zaehler_faellt() {
        let (wurzeln, sperren) = beispiel();
        let c = erzeuge("beispiel124", &wurzeln, &sperren, None).replace(
            "#define N_WURZELN 2",
            "#define N_WURZELN 3",
        );
        let gefallen =
            pin_pruefe(&menge(&["hauptA", "hauptB"]), &c).expect_err("a wrong count must fail");
        assert!(gefallen.contains("N_WURZELN"), "the count is named:\n{gefallen}");
    }

    /// **A pool routine named twice gets two threads** (fix lane F4, review G06
    /// F5). One adapter, two `pthread_create` sites, `N_WURZELN 2` -- and a
    /// driver that starts it once fails the multiset pin, which the set pin
    /// before this lane let pass.
    #[test]
    fn pool_doppelt_zwei_faeden() {
        let w = Wurzel {
            c_name: "arbeiter".to_string(),
            gab_path: "arbeiter".to_string(),
        };
        let (_, sperren) = beispiel();
        let c = erzeuge("pool", &[w.clone(), w.clone()], &sperren, None);
        assert_eq!(c.matches("static void *faden_arbeiter(void *u)").count(), 1, "one adapter");
        assert_eq!(c.matches("faden_arbeiter, NULL)").count(), 2, "two thread starts");
        assert!(c.contains("#define N_WURZELN 2"));
        assert_eq!(pin_pruefe(&menge(&["arbeiter", "arbeiter"]), &c), Ok(2));
        let einmal = erzeuge("pool", &[w], &sperren, None);
        let gefallen = pin_pruefe(&menge(&["arbeiter", "arbeiter"]), &einmal)
            .expect_err("one thread for two declared starts must fail");
        assert!(gefallen.contains("arbeiter x2"), "the count is named:\n{gefallen}");
    }

    /// **C names are ASCII words.** Anything else never reaches the file --
    /// it is refused before generation, never truncated into a name.
    #[test]
    fn c_namen_sind_ascii_woerter() {
        assert!(gueltiger_c_name("hauptA"));
        assert!(gueltiger_c_name("_ruhe"));
        assert!(!gueltiger_c_name(""));
        assert!(!gueltiger_c_name("9lebt"));
        assert!(!gueltiger_c_name("grüße"));
        assert!(!gueltiger_c_name("a-b"));
    }

    /// **Deterministic: same inputs, same bytes.** A driver that differed
    /// between two runs would make every comparison worthless (the same
    /// reason the emitter is held byte-identical in `pruefe-emission.sh`).
    #[test]
    fn zweimal_erzeugt_ist_bytegleich() {
        let (wurzeln, sperren) = beispiel();
        let a = erzeuge("beispiel124", &wurzeln, &sperren, None);
        let b = erzeuge("beispiel124", &wurzeln, &sperren, None);
        assert_eq!(a, b, "two runs are two identical artefacts");
    }
}
