/-
  File:    Grammatik/Korrespondenz/Zeugnis/Zertifikate.lean -- GENERATED by `crates/gabbro-check/tests/zertifikate.rs`
           (do not edit; `GABBRO_ZERTIFIKATE=schreiben cargo test --test zertifikate`).
  Content: one import per CERTIFIED corpus program of `Zertifikat/REGISTER.txt`. Each imported
           module is the byte-exact output of `gabbro obligations --g <program>`: the exported
           unit `gE`, the checker premise decided (`gCheck`, `by decide`) and the goal theorem
           instantiated (`gP_gabbro`). Importing them here puts every one into `lake build`, so
           an exported program the Lean Bool `Akzeptiert` refuses turns the build RED.
-/
import Grammatik.Korrespondenz.Korpus.GenOblig104
import Grammatik.Korrespondenz.Korpus.GenOblig108
import Grammatik.Zertifikat.Reihe01.G187_bool_statisch
import Grammatik.Zertifikat.Reihe00.G15_own_traegt_beide_rechte
import Grammatik.Zertifikat.Reihe00.G16_by_ops_am_feld
import Grammatik.Zertifikat.Reihe00.G34_markierter_wert
import Grammatik.Zertifikat.Reihe00.G59_eintritt_nimmt_maskierte_sperre
import Grammatik.Zertifikat.Reihe00.G62_grenzwort_im_ausdruck
import Grammatik.Zertifikat.Reihe00.G69_integer_conversion
import Grammatik.Zertifikat.Reihe00.G73_sugar_widths
import Grammatik.Zertifikat.Reihe00.G93_const_scalars
import Grammatik.Zertifikat.Reihe01.G109_lockfree_entry_roots
import Grammatik.Zertifikat.Reihe01.G116_payload_free_counter
import Grammatik.Zertifikat.Reihe01.G118_sperrinvariante_erhaltung
import Grammatik.Zertifikat.Reihe01.G119_sperrinvariante_bloecke
import Grammatik.Zertifikat.Reihe01.G120_tagged_construction
import Grammatik.Zertifikat.Reihe01.G121_tagged_static_init
import Grammatik.Zertifikat.Reihe01.G124_two_threads_private
import Grammatik.Zertifikat.Reihe01.G130_derived_contract_pure
import Grammatik.Zertifikat.Reihe01.G157_worker_pool
import Grammatik.Zertifikat.Reihe01.G162_geteilte_flagge
import Grammatik.Zertifikat.Reihe01.G165_gp_eintritt
import Grammatik.Zertifikat.Reihe01.G166_eintritt_irq_maskiert
import Grammatik.Zertifikat.Reihe01.G174_tor_im_modell
import Grammatik.Zertifikat.Reihe01.G181_gate_at_top_level
import Grammatik.Zertifikat.Reihe01.G182_fallible_gate
import Grammatik.Zertifikat.Reihe02.G219_unaeres_minus
import Grammatik.Zertifikat.Reihe04.G414_tabellenspeicher_heisst_so
import Grammatik.Zertifikat.Reihe07.G700_lesen_ohne_klausel
import Grammatik.Zertifikat.Reihe07.G701_rein_ohne_klausel
import Grammatik.Zertifikat.Reihe07.G719_lock_taken_nowhere
