/-
  File:      Arm/Basic.lean
  Subject:   Shared vocabulary of the Arm model. FROZEN: agents do not edit this file;
             they propose changes in their report and the coordinator merges them.
-/
namespace Arm

abbrev Addr := BitVec 64
abbrev CoreId := Nat

/-- Shareability domain of a barrier (Arm ARM, DMB/DSB option). -/
inductive Domain where
  | nsh | ish | osh | sy
  deriving DecidableEq, Repr

/-- The access types a barrier orders. -/
inductive BarrierType where
  | all | ld | st
  deriving DecidableEq, Repr

inductive Barrier where
  | dmb (d : Domain) (t : BarrierType)
  | dsb (d : Domain) (t : BarrierType)
  | isb
  deriving DecidableEq, Repr

/-- Ordering annotation of one memory access: LDR/STR plain, LDAR acquire,
    LDAPR acquirePC (RCpc), STLR release. -/
inductive AccOrd where
  | plain | acquire | acquirePC | release
  deriving DecidableEq, Repr

structure Access where
  addr : Addr
  size : Nat      -- bytes: 1, 2, 4, 8 or 16
  ord  : AccOrd
  excl : Bool     -- part of an exclusive pair (LDXR/STXR, LDAXR/STLXR)
  deriving DecidableEq, Repr

end Arm

/-
CUTS: vocabulary only; no semantics, no theorem.
-/
