#!/usr/bin/env python3
"""Generate `crates/gabbro-check/src/abi_tabelle.rs` from the Lean ABI records.

The Lean files are the ONE source (Sonnet G, 2026-10-07):
  * `Kern/Semantik/Syscall.lean`     -- `inductive SysReg` (the x86_64 register file),
  * `Kern/Semantik/SyscallArm.lean`  -- `inductive ArmReg` (`x (n : Fin N)`), `nummerRegLinux`,
                                        `argRegs`, `ergebnisReg`, the `def nr<Name> : Nat := N` table,
  * `Kern/Semantik/SyscallArmLinux.lean` -- `klonStapelReg`.
The Rust checker's per-architecture register tables (`syscall.rs`: N066, N446, A005, A006) read the
generated module, so an x86 or an aarch64 row cannot drift from the model.

    erzeuge-abi-tabelle.py            write the module
    erzeuge-abi-tabelle.py --pruefe   fail (exit 1) when the file on disk is not what the Lean
                                      files generate -- the guardian
    erzeuge-abi-tabelle.py --selbsttest   the guardian must fall on a stale copy

`sp` is a constructor of `ArmReg` (state of the machine) but is NOT a register a `syscall`
declaration can bind: the generated AArch64 table holds `x0 .. x(N-1)` only, as the checker's rule
always did.
"""
import re
import sys
from pathlib import Path

WURZEL = Path(__file__).resolve().parent.parent
SEM = WURZEL / 'grammatik/Grammatik/Kern/Semantik'
AUS = WURZEL / 'crates/gabbro-check/src/abi_tabelle.rs'


def lies(name):
    return (SEM / name).read_text()


def konstruktoren(text, induktiv):
    m = re.search(r'inductive ' + induktiv + r' where\n(.*?)\n\s*deriving', text, re.S)
    if not m:
        raise SystemExit(f'ABBRUCH: no `inductive {induktiv}` in the Lean source')
    return m.group(1)


def x86_register():
    body = konstruktoren(lies('Syscall.lean'), 'SysReg')
    regs = re.findall(r'[A-Za-z][A-Za-z0-9_]*', body.replace('|', ' '))
    if not regs:
        raise SystemExit('ABBRUCH: SysReg has no constructor')
    return regs


def arm_breite():
    body = konstruktoren(lies('SyscallArm.lean'), 'ArmReg')
    m = re.search(r'\|\s*x\s*\(n\s*:\s*Fin\s+(\d+)\)', body)
    if not m:
        raise SystemExit('ABBRUCH: ArmReg has no `x (n : Fin N)` constructor')
    return int(m.group(1))


def xr(text):
    m = re.fullmatch(r'\s*xr\s+(\d+)\s*', text)
    if not m:
        raise SystemExit(f'ABBRUCH: not an `xr N`: {text!r}')
    return int(m.group(1))


def arm_definition(name):
    m = re.search(r'^def ' + name + r' : ArmReg := (.*)$', lies('SyscallArm.lean') + lies('SyscallArmLinux.lean'), re.M)
    if not m:
        raise SystemExit(f'ABBRUCH: no `def {name} : ArmReg`')
    return xr(m.group(1))


def arg_regs():
    m = re.search(r'^def argRegs : List ArmReg := \[(.*)\]$', lies('SyscallArm.lean'), re.M)
    if not m:
        raise SystemExit('ABBRUCH: no `def argRegs`')
    return [xr(p) for p in m.group(1).split(',')]


def nummern():
    out = []
    for m in re.finditer(r'^def nr([A-Za-z0-9]+) : Nat := (\d+)$', lies('SyscallArm.lean'), re.M):
        out.append((m.group(1), int(m.group(2))))
    if not out:
        raise SystemExit('ABBRUCH: no `def nr<Name> : Nat` in SyscallArm.lean')
    return out


def erzeuge():
    x86 = x86_register()
    breite = arm_breite()
    z = []
    z.append('//! GENERATED by `instrumente/erzeuge-abi-tabelle.py` from the Lean ABI records')
    z.append('//! (`Kern/Semantik/Syscall.lean`, `SyscallArm.lean`, `SyscallArmLinux.lean`). DO NOT EDIT:')
    z.append('//! `instrumente/erzeuge-abi-tabelle.py --pruefe` (and the test `abi_tabelle_ist_frisch`)')
    z.append('//! fail when this file is not what the Lean files generate.')
    z.append('')
    z.append('/// The x86_64 general registers: the constructors of `SysReg`.')
    z.append('pub const REGISTER_X86_64: &[&str] = &[')
    z.append('    ' + ', '.join(f'"{r}"' for r in x86) + ',')
    z.append('];')
    z.append('')
    z.append(f'/// The AArch64 general registers `x0` .. `x{breite - 1}`: `ArmReg.x (n : Fin {breite})`')
    z.append('/// (`sp` is machine state, not a bindable register).')
    z.append('pub const REGISTER_AARCH64: &[&str] = &[')
    z.append('    ' + ', '.join(f'"x{n}"' for n in range(breite)) + ',')
    z.append('];')
    z.append('')
    z.append('/// The register the Linux AArch64 call number travels in (`nummerRegLinux`).')
    z.append(f'pub const AARCH64_NUMMER_REG: &str = "x{arm_definition("nummerRegLinux")}";')
    z.append('/// The Linux AArch64 answer register (`ergebnisReg`).')
    z.append(f'pub const AARCH64_ERGEBNIS_REG: &str = "x{arm_definition("ergebnisReg")}";')
    z.append('/// The clone gate\'s handed-stack register (`klonStapelReg`).')
    z.append(f'pub const AARCH64_KLON_STAPEL_REG: &str = "x{arm_definition("klonStapelReg")}";')
    z.append('/// The Linux AArch64 argument registers in order (`argRegs`).')
    z.append('pub const AARCH64_ARG_REGS: &[&str] = &[' + ', '.join(f'"x{n}"' for n in arg_regs()) + '];')
    z.append('/// The Linux AArch64 call numbers (`def nr<Name> : Nat`), as `(Name, number)`.')
    z.append('pub const AARCH64_NUMMERN: &[(&str, u64)] = &[')
    for n, v in nummern():
        z.append(f'    ("{n}", {v}),')
    z.append('];')
    return '\n'.join(z) + '\n'


def selbsttest():
    gut = erzeuge()
    alt = gut.replace('"x8"', '"x9"', 1)
    if alt == gut:
        print('SELBSTTEST ROT: the probe changed nothing')
        return 1
    if pruefe_text(alt):
        print('SELBSTTEST ROT: a stale module is not refused')
        return 1
    if not pruefe_text(gut):
        print('SELBSTTEST ROT: a fresh module is refused')
        return 1
    print('SELBSTTEST GRUEN: a drifted module is refused, the generated one is not')
    return 0


def pruefe_text(vorhanden):
    return vorhanden == erzeuge()


if __name__ == '__main__':
    if '--selbsttest' in sys.argv:
        sys.exit(selbsttest())
    if '--pruefe' in sys.argv:
        if not AUS.exists() or AUS.read_text() != erzeuge():
            print(f'ROT: {AUS.relative_to(WURZEL)} is stale or missing; run instrumente/erzeuge-abi-tabelle.py')
            sys.exit(1)
        print('GRUEN: abi_tabelle.rs equals what the Lean ABI records generate')
        sys.exit(0)
    AUS.write_text(erzeuge())
    print(f'wrote {AUS.relative_to(WURZEL)}')
