#!/usr/bin/env python3
"""**A committed GENERATED Lean file IS what the generator writes -- byte for byte.**

    ./instrumente/pruefe-genlean.py [--binary PATH] [--allow-stale] [--probe]

WHY THIS EXISTS
---------------
`gabbro lean-g` and `gabbro obligations --g` write Lean files, and some of them are
COMMITTED and proved against: `grammatik/Grammatik/GenOblig104.lean` carries the exported
unit `gE` of `beispiele/104-referenz.gab` and the theorem `gP_gabbro`, and
`Pflicht104.lean` proves the user's duty for exactly that unit (`GenOblig108`/`Pflicht108`
the same for 108). The proof is about the COMMITTED TEXT. If the exporter changes and the
committed file does not, the proof stays true and stops being about this tree -- *a stale
paste is a different program*.

That failure has a precedent and a fix: `instrumente/pruefe-ctext.py` closes the same loop
between `emit.rs` and the pinned C text (`CTEXT-PIN`). This guardian is that idea on the
generated LEAN, and it is the only reader that closes the loop between `lean_g.rs` /
`obligations_g.rs` and the files the goal theorem is applied in.

WHAT IT READS
-------------
Nothing but the files themselves. A generated file names its own generator in its FIRST
line, because the generator writes it there:

    -- GENERATED by `gabbro lean-g beispiele/108-disjoint-start-locks.gab` -- do not edit.
    -- GENERATED by `gabbro obligations --g beispiele/104-referenz.gab` (…) -- do not edit.

So the guardian needs no register beside the tree -- *a second register over one thing is
the half that ages*. It re-runs the named subcommand on the named program and compares the
WHOLE FILE, byte for byte. The marker counts only on line 1: a file that merely quotes the
sentence in a comment is not a generated file, and a file that pastes only PART of a
generated one (`Export108.lean` drops the imports) does not carry it at all -- deliberately,
since a partial paste is not byte-comparable and claiming otherwise would be worse than not
measuring.

Only the two subcommands above are accepted. An unknown one is a FINDING, never guessed
into a command line.

THE VERDICT, AND THE THREE EXITS
--------------------------------
    0   green -- every generated file is its generator's output, byte for byte
    1   a finding -- a file differs, and the first differing byte is printed
    2   ABBRUCH -- nothing was measured: no binary, a stale binary, no generated file at
        all, or a generator that did not answer inside the deadline

The work count stands beside the verdict (`N files, M bytes`), so a green run over nothing
is not a green run (`pruefe-waechter.py` requirement 4).
"""
import argparse
import os
import pathlib
import re
import subprocess
import sys

W = pathlib.Path(__file__).resolve().parent.parent
GRAMMATIK = W / "grammatik" / "Grammatik"

# A hang looks like "still running", not like a finding: every generator runs under FRIST.
FRIST = 120

# The generator sentence, as the exporter writes it, on line 1 and nowhere else.
MARKE = re.compile(r"^-- GENERATED by `gabbro ([a-z0-9 .\-]+?) (\S+\.gab)`")

# The subcommands whose output is a WHOLE Lean file. Anything else is refused by name.
ERZEUGER = {
    "lean-g": ["lean-g"],
    "obligations --g": ["obligations", "--g"],
}


def umgebung():
    """`LC_ALL=C`: a tool that measures its own locale looks plausible doing it."""
    env = dict(os.environ)
    env["LC_ALL"] = "C"
    return env


def marke_von(text):
    """`(subcommand, program)` if the FIRST line of `text` names a generator, else `None`.
    An unknown subcommand comes back as `(name, program)` too -- the caller reports it as a
    finding rather than guessing a command line for it."""
    erste = text.split("\n", 1)[0]
    m = MARKE.match(erste)
    if not m:
        return None
    return m.group(1).strip(), m.group(2)


def erzeugte():
    """`[(lean file, subcommand, program)]` for every generated file in the tree."""
    aus = []
    for p in sorted(GRAMMATIK.rglob("*.lean")):
        t = p.read_text(encoding="utf-8", errors="replace")
        m = marke_von(t)
        if m:
            aus.append((p, m[0], m[1]))
    return aus


def sprechprobe():
    """**The speech test, in both directions, on invented text** -- a guardian that cannot
    go red measures nothing (`pruefe-waechter.py` requirement 2)."""
    gut = ("-- GENERATED by `gabbro obligations --g beispiele/104-referenz.gab` (x) "
           "-- do not edit.\nimport Foo\n")
    leang = "-- GENERATED by `gabbro lean-g beispiele/999-x.gab` -- do not edit.\nimport Foo\n"
    spaet = "-- a note\n-- GENERATED by `gabbro lean-g beispiele/999-x.gab` -- do not edit.\n"
    fremd = "-- GENERATED by `gabbro emit beispiele/999-x.gab` -- do not edit.\n"
    return [
        ("a generated header names its subcommand and program",
         marke_von(gut) == ("obligations --g", "beispiele/104-referenz.gab")),
        ("the plain `lean-g` header is read too",
         marke_von(leang) == ("lean-g", "beispiele/999-x.gab")),
        ("the sentence on a LATER line is not a generated file", marke_von(spaet) is None),
        ("a file without the sentence is not a generated file",
         marke_von("import Foo\n") is None),
        ("an unknown subcommand is read but NOT in the generator table",
         marke_von(fremd) == ("emit", "beispiele/999-x.gab") and "emit" not in ERZEUGER),
        ("identical text compares equal", gut == gut),
        ("one byte changed is a DIFFERENT text", gut != gut.replace("import", "imporT")),
    ]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--binary", default=str(W / "target" / "debug" / "gabbro"))
    ap.add_argument("--allow-stale", action="store_true")
    ap.add_argument("--probe", action="store_true", help="only the speech test")
    args = ap.parse_args()

    probe = sprechprobe()
    for was, ok in probe:
        print(f"  probe: {'ok  ' if ok else 'FAIL'} {was}")
    if not all(ok for _, ok in probe):
        print("ABBRUCH: the speech test of this guardian failed -- it measured nothing")
        return 2
    if args.probe:
        print(f"pruefe-genlean: speech test only, {len(probe)} of {len(probe)} directions ok")
        return 0

    binary = pathlib.Path(args.binary)
    if not binary.exists():
        print(f"ABBRUCH: no binary at {binary} -- build it (on ki-pc-fisch-101) "
              f"or pass --binary")
        return 2
    stand = binary.stat().st_mtime
    neuer = sorted(q for q in W.glob("crates/*/src/*.rs") if q.stat().st_mtime > stand)
    if neuer and not args.allow_stale:
        print(f"ABBRUCH: the binary is OLDER than {len(neuer)} source file(s) under crates/ "
              f"(first: {neuer[0].relative_to(W)}) -- it measures another generator")
        print("  (build it, or pass --allow-stale to measure that binary anyway)")
        return 2

    dateien = erzeugte()
    if not dateien:
        print("ABBRUCH: no generated Lean file under grammatik/Grammatik -- nothing to "
              "measure (the marker is the `-- GENERATED by \\`gabbro …\\`` first line)")
        return 2

    befunde = 0
    bytes_geprueft = 0
    for quelle, unter, prog in dateien:
        kurz = quelle.relative_to(W)
        if unter not in ERZEUGER:
            print(f"  {kurz}: BEFUND -- unknown generator `gabbro {unter}`; this guardian "
                  f"does not guess a command line")
            befunde += 1
            continue
        pfad = W / prog
        if not pfad.exists():
            print(f"  {kurz}: BEFUND -- the program {prog} does not exist")
            befunde += 1
            continue
        try:
            # The program path is passed EXACTLY as the marker spells it, from the tree
            # root. The generator echoes its argument into the first line, so an absolute
            # path here would report a finding about the caller's working directory --
            # measured 2026-09-15, and that is the same class as `W16`.
            r = subprocess.run([str(binary)] + ERZEUGER[unter] + [prog],
                               capture_output=True, text=True, cwd=W, timeout=FRIST,
                               env=umgebung())
        except (OSError, subprocess.TimeoutExpired):
            print(f"ABBRUCH: `gabbro {unter} {prog}` did not answer inside {FRIST} s")
            return 2
        if r.returncode != 0 or not r.stdout:
            print(f"  {kurz}: BEFUND -- the generator refused {prog} (exit {r.returncode})")
            if r.stderr:
                print(f"      {r.stderr.strip().splitlines()[0] if r.stderr.strip() else ''}")
            befunde += 1
            continue
        text = quelle.read_text(encoding="utf-8", errors="replace")
        bytes_geprueft += len(text)
        if r.stdout == text:
            print(f"  {kurz}: ok -- {len(text)} bytes, byte-identical to "
                  f"`gabbro {unter} {prog}`")
            continue
        befunde += 1
        stelle = next((i for i, (a, b) in enumerate(zip(text, r.stdout)) if a != b),
                      min(len(text), len(r.stdout)))
        print(f"  {kurz}: BEFUND -- the committed file is NOT what `gabbro {unter}` writes "
              f"for {prog}")
        print(f"      committed {len(text)} bytes, generated {len(r.stdout)} bytes, "
              f"first difference at byte {stelle}")
        print(f"      committed …{text[max(0, stelle - 40):stelle + 20]!r}")
        print(f"      generated …{r.stdout[max(0, stelle - 40):stelle + 20]!r}")

    print(f"pruefe-genlean: {len(dateien) - befunde} of {len(dateien)} generated files "
          f"byte-identical, {bytes_geprueft} bytes compared, binary {binary}")
    print("== GENLEAN: " + ("GRUEN" if befunde == 0 else f"{befunde} BEFUNDE") + " ==")
    return 1 if befunde else 0


if __name__ == "__main__":
    sys.exit(main())
