/* Generated by Gabbro -- https://github.com/SimonVitzethum/Gabbro
 *
 * This file was generated. Edit the .gab source, not this file.
 *
 * Gabbro is AGPL-3.0 with an additional permission: this generated file and the program it
 * belongs to are NOT a derived work of Gabbro. The permission is conditional on this notice
 * being preserved. See LIZENZ-ZUSATZ.md.
 */
#include <stdint.h>
#include <stdbool.h>
#include <stdatomic.h>
#include <math.h>

/* Word readers for the declared byte order. Generated, not assumed. */
static inline uint16_t gabbro_be16(const uint8_t *p) { return (uint16_t)((uint16_t)p[0] << 8 | p[1]); }
static inline uint32_t gabbro_be32(const uint8_t *p) { return (uint32_t)p[0] << 24 | (uint32_t)p[1] << 16 | (uint32_t)p[2] << 8 | p[3]; }
static inline uint8_t gabbro_u8(const uint8_t *p) { return p[0]; }

typedef struct { const uint8_t *bytes; uint32_t len; } IpKopf;
static inline uint8_t IpKopf_version(const IpKopf *v) { return (uint8_t)(((uint8_t)gabbro_u8(v->bytes + 0) >> 4) & 15u); }
static inline uint8_t IpKopf_ihl(const IpKopf *v) { return (uint8_t)(((uint8_t)gabbro_u8(v->bytes + 0) >> 0) & 15u); }
static inline uint8_t IpKopf_dscp(const IpKopf *v) { return (uint8_t)(((uint8_t)gabbro_u8(v->bytes + 1) >> 2) & 63u); }
static inline uint8_t IpKopf_ecn(const IpKopf *v) { return (uint8_t)(((uint8_t)gabbro_u8(v->bytes + 1) >> 0) & 3u); }
static inline uint16_t IpKopf_gesamtlaenge(const IpKopf *v) { return (uint16_t)gabbro_be16(v->bytes + 2); }
static inline uint16_t IpKopf_kennung(const IpKopf *v) { return (uint16_t)gabbro_be16(v->bytes + 4); }
static inline uint16_t IpKopf_flags(const IpKopf *v) { return (uint16_t)(((uint16_t)gabbro_be16(v->bytes + 6) >> 13) & 7u); }
static inline uint16_t IpKopf_fragment(const IpKopf *v) { return (uint16_t)(((uint16_t)gabbro_be16(v->bytes + 6) >> 0) & 8191u); }
static inline uint8_t IpKopf_ttl(const IpKopf *v) { return (uint8_t)gabbro_u8(v->bytes + 8); }
static inline uint8_t IpKopf_protokoll(const IpKopf *v) { return (uint8_t)gabbro_u8(v->bytes + 9); }
static inline uint16_t IpKopf_pruefsumme(const IpKopf *v) { return (uint16_t)gabbro_be16(v->bytes + 10); }
static inline uint32_t IpKopf_quelle(const IpKopf *v) { return (uint32_t)gabbro_be32(v->bytes + 12); }
static inline uint32_t IpKopf_ziel(const IpKopf *v) { return (uint32_t)gabbro_be32(v->bytes + 16); }
static inline bool IpKopf_gueltig(const IpKopf *v) {
    if (v->len < 20u) return false;
    return true;
}
