/* Generated by Gabbro -- https://github.com/SimonVitzethum/Gabbro
 *
 * This file was generated. Edit the .gab source, not this file.
 *
 * Gabbro is AGPL-3.0 with an additional permission: this generated file and the program it
 * belongs to are NOT a derived work of Gabbro. The permission is conditional on this notice
 * being preserved. See LIZENZ-ZUSATZ.md.
 */
#include <stdint.h>
#include <stdbool.h>
#include <stdatomic.h>
#include <math.h>

#define N 4096u

typedef struct {
    bool benutzt;
    uint32_t zaehler;
} Objekte_slot;

typedef struct {
    Objekte_slot slots[N];
} Objekte;
#define Objekte_NONE (N)

uint32_t stand(const Objekte *restrict o, uint32_t i) __attribute__((pure));

void belegen(Objekte *restrict o, uint32_t i);

uint32_t stand(const Objekte *restrict o, uint32_t i) {
    return o->slots[i].zaehler;
}

void belegen(Objekte *restrict o, uint32_t i) {
    o->slots[i].benutzt = true;
}
