//! **The C emitter -- the first line of the largest undamageable surface.**
//!
//! Until 2026-08-17 this surface did not exist. `mutiere-pruefer.py` reported it with **0
//! mutations**, and *what has 0 mutations is not covered, it is undamageable*. Three things
//! hung on it: the plumbing class *refinement*, the templates `table.absenkung` and
//! `table.ops.erhaltung`, and the licence notice that `LIZENZ-ZUSATZ.md` demands in generated
//! C while nothing wrote it.
//!
//! ## What this emitter is, and what it deliberately is not
//!
//! **It is one fragment, not ten.** It covers exactly the forms that
//! `beispiele/16-by-ops-am-feld.gab` uses: a `table` with `count`, range types, `bool`,
//! `index into T`, pointer parameters, field and index access, assignment, `return`. Anything
//! else it **refuses by name** (`C001`) instead of emitting something plausible.
//!
//! > **A generator that emits something for a form it does not know is worse than one that
//! > stops.** The whole value of this crate is that its output is trustworthy; a silent
//! > approximation in the emitter would undo every pass in front of it.
//!
//! ## W6 holds here, and this is where it bites
//!
//! *The omission of a runtime check is justified by M1 alone, never by an invariant.* This
//! emitter omits **no** check, because it emits none yet -- but the rule is why `index into T`
//! becomes a plain `uint32_t` and not a range-checked accessor: the bound comes from `count N`
//! and is an M1 fact. The moment a check is left out here, the reason has to be an M1 fact and
//! stand in this file.

use gabbro_syntax::ast::*;
use gabbro_syntax::diag::{Absage, Absagen};
use std::collections::{BTreeSet, HashMap};

/// What the emitter must resolve: table names (a path naming one IS the struct), named
/// types (they lower to their carrier), **ghost types (they lower to NOTHING)** and the
/// signatures it needs in order to erase a ghost at a call site.
#[derive(Default)]
struct Namen {
    tabellen: Vec<String>,
    typen: HashMap<String, TypExpr>,
    /// `linear ghost type BootPhase;` — a value that **does not exist at run time**.
    geister: Vec<String>,
    funktionen: HashMap<String, Signatur>,
    /// Namen, die diese Einheit **nicht deklariert** und die nur hinter einem Zeiger
    /// vorkommen. Sie werden als unvollstaendiger C-Typ vorwaerts deklariert.
    fremde: BTreeSet<String>,
}

/// Ist `t` ein Zeiger auf einen Pfad, den diese Einheit nicht aufloest? Dann traegt sie
/// seinen Namen, aber nicht sein Layout -- und C hat dafuer bereits eine Form.
fn fremdes_ziel(t: &TypExpr, u: &Namen) -> Option<String> {
    let TypExpr::Zeiger(z) = t else { return None };
    if ctyp(&z.ziel, u).is_some() {
        return None;
    }
    match &z.ziel {
        TypExpr::Pfad(p) => Some(p.teile.last()?.text.clone()),
        _ => None,
    }
}

/// What must be known about a callee in order to erase a ghost **at the call site**.
struct Signatur {
    /// Per parameter: is it a ghost? A ghost argument is dropped from the C call.
    geist_param: Vec<bool>,
    /// Does it return a ghost? Then `let x = f(…)` loses its binding, **not its call**.
    geist_rueck: bool,
}

/// **Is this type a ghost — i.e. does it vanish in the C?**
///
/// This is the one question that separates an erasure from a lowering, and getting it wrong is
/// silent in both directions: erase too much and the C computes something else; erase too
/// little and it does not compile.
fn ist_geist(t: &TypExpr, u: &Namen) -> bool {
    match t {
        TypExpr::Pfad(p) => p
            .teile
            .last()
            .is_some_and(|i| u.geister.iter().any(|g| *g == i.text)),
        _ => false,
    }
}

/// **The licence notice, and it is not decoration.**
///
/// `LIZENZ-ZUSATZ.md` grants an additional permission under AGPL §7 -- *what you write in
/// Gabbro is not a derived work* -- and ties it to one condition: generated C carries this
/// header. **The compiler writes it itself**, because a condition that depends on the user
/// remembering it is not a condition.
pub const KOPF: &str = "\
/* Generated by Gabbro -- https://github.com/SimonVitzethum/Gabbro
 *
 * This file was generated. Edit the .gab source, not this file.
 *
 * Gabbro is AGPL-3.0 with an additional permission: this generated file and the program it
 * belongs to are NOT a derived work of Gabbro. The permission is conditional on this notice
 * being preserved. See LIZENZ-ZUSATZ.md.
 */
#include <stdint.h>
#include <stdbool.h>
";

/// Emits C for a tree, or refuses by name.
pub fn emittiere(baum: &Programm, absagen: &mut Absagen) -> String {
    let mut namen = Namen::default();
    crate::fuer_jedes_item(baum, &mut |item| match &item.art {
        ItemArt::Tabelle(t) => namen.tabellen.push(t.name.text.clone()),
        ItemArt::Typ(t) => {
            // **A ghost type has no body and no C.** `linear ghost type BootPhase;` declares a
            // value the checker threads and the machine never sees.
            if t.ghost {
                namen.geister.push(t.name.text.clone());
            } else if let Some(unter) = &t.rumpf {
                namen.typen.insert(t.name.text.clone(), unter.clone());
            }
        }
        _ => {}
    });
    // **Second pass, and it needs the first**: whether a parameter is a ghost can only be
    // decided once the ghost names are known.
    crate::fuer_jedes_item(baum, &mut |item| {
        if let ItemArt::Funktion(f) = &item.art {
            let sig = Signatur {
                geist_param: f.parameter.iter().map(|p| ist_geist(&p.typ, &namen)).collect(),
                geist_rueck: f.ergebnis.as_ref().is_some_and(|t| ist_geist(t, &namen)),
            };
            namen.funktionen.insert(f.name.text.clone(), sig);
        }
    });
    // **Dritter Sammelgang: die fremden Zeigerziele.** C verlangt den Tag VOR der
    // Parameterliste -- sonst hat er nur Prototyp-Reichweite, und `-Wall` sagt das zu Recht.
    let mut fremde = BTreeSet::new();
    crate::fuer_jedes_item(baum, &mut |item| {
        if let ItemArt::Funktion(f) = &item.art {
            for p in &f.parameter {
                fremde.extend(fremdes_ziel(&p.typ, &namen));
            }
            if let Some(r) = &f.ergebnis {
                fremde.extend(fremdes_ziel(r, &namen));
            }
        }
        if let ItemArt::Tabelle(tb) = &item.art {
            if let Some(slot) = &tb.slot {
                for f in &slot.felder {
                    if let SlotTyp::Typ(ty) = &f.typ {
                        fremde.extend(fremdes_ziel(ty, &namen));
                    }
                }
            }
        }
    });
    namen.fremde = fremde;

    let mut aus = String::from(KOPF);
    if !namen.fremde.is_empty() {
        aus.push_str(
            "\n/* Types this unit names but does not declare. Incomplete on purpose: C\n\
             \x20* refuses every use that needs the layout, which is the refusal this emitter\n\
             \x20* would otherwise have to invent. */\n",
        );
        for f in &namen.fremde {
            aus.push_str(&format!("struct {f};\n"));
        }
    }
    crate::fuer_jedes_item(baum, &mut |item| match &item.art {
        ItemArt::Konst(k) => {
            if let Some(w) = konst_zahl(&k.wert) {
                aus.push_str(&format!("\n#define {} {}u\n", k.name.text, w));
            } else {
                weigere(absagen, k.name.span, "const with a non-constant value");
            }
        }
        ItemArt::Typ(_) => {} // Range types lower to their carrier; see `ctyp`.
        ItemArt::Tabelle(t) => tabelle(t, &mut aus, &namen, absagen),
        ItemArt::Funktion(f) => funktion(f, &mut aus, &namen, absagen),
        ItemArt::Modul(_) | ItemArt::Use(_) => {}
        _ => weigere(
            absagen,
            item.span,
            "this item kind has no lowering in this emitter yet",
        ),
    });
    aus
}

/// **C001 -- the emitter refuses instead of guessing.**
fn weigere(absagen: &mut Absagen, span: gabbro_syntax::span::Span, was: &str) {
    absagen.schiebe(
        Absage::fehler("C001", span, format!("no lowering: {was}")).mit_notiz(
            "the emitter refuses by name instead of emitting something plausible -- a \
             generator that guesses undoes every pass in front of it",
        ),
    );
}

fn konst_zahl(e: &Expr) -> Option<i128> {
    match &e.art {
        ExprArt::Zahl(n) => Some(*n as i128),
        _ => None,
    }
}

/// A table becomes a slot struct plus a carrier struct with a fixed-size array.
///
/// **`count N` is the whole reason the array is fixed.** Without it `index into T` has no
/// upper bound from the declaration, and this lowering would have to be a pointer plus a
/// length -- i.e. exactly the shape Gabbro exists to avoid.
fn tabelle(t: &Tabelle, aus: &mut String, u: &Namen, absagen: &mut Absagen) {
    let Some(n) = &t.kapazitaet else {
        weigere(absagen, t.span, "table without `count` -- the array would have no size");
        return;
    };
    aus.push_str(&format!("\ntypedef struct {{\n"));
    if let Some(slot) = &t.slot {
        for f in &slot.felder {
            let c = match &f.typ {
                SlotTyp::Typ(t) => ctyp(t, u),
                // `intty wrapping` -- the wraparound is DECLARED («B32»), so the C type is
                // the plain unsigned word whose wrap C already defines.
                SlotTyp::Wrapping(i) => Some(intty(i)),
            };
            match c {
                Some(c) => aus.push_str(&format!("    {c} {};\n", f.name.text)),
                None => weigere(absagen, f.name.span, "field type"),
            }
        }
    }
    aus.push_str(&format!("}} {}_slot;\n\ntypedef struct {{\n", t.name.text));
    aus.push_str(&format!(
        "    {}_slot slots[{}];\n}} {};\n",
        t.name.text,
        zahltext(n),
        t.name.text
    ));
}

fn intty(i: &IntTy) -> String {
    // The word IS the width -- `u32 wrapping` lowers to `uint32_t`, whose wraparound C
    // defines. «B32»: the wraparound is spoken at the declaration, not tolerated.
    match i.wort {
        gabbro_syntax::kw::Kw::U8 => "uint8_t",
        gabbro_syntax::kw::Kw::U16 => "uint16_t",
        gabbro_syntax::kw::Kw::U32 => "uint32_t",
        gabbro_syntax::kw::Kw::U64 => "uint64_t",
        gabbro_syntax::kw::Kw::I8 => "int8_t",
        gabbro_syntax::kw::Kw::I16 => "int16_t",
        gabbro_syntax::kw::Kw::I32 => "int32_t",
        _ => "int64_t",
    }
    .to_string()
}

fn zahltext(e: &Expr) -> String {
    match &e.art {
        ExprArt::Zahl(n) => n.to_string(),
        ExprArt::Ort(o) => o.text(),
        _ => "0 /* NOT LOWERED */".into(),
    }
}

/// The C type for a Gabbro type. **Range types lower to their carrier** -- the range itself is
/// an M1 fact and lives in the checker, not in the C.
fn ctyp(t: &TypExpr, u: &Namen) -> Option<String> {
    match t {
        TypExpr::Int(i) => Some(intty(i)),
        TypExpr::Bool(_) => Some("bool".into()),
        TypExpr::Pfad(p) => {
            let n = p.teile.last()?.text.clone();
            Some(match n.as_str() {
                "bool" => "bool".into(),
                "u8" => "uint8_t".into(),
                "u16" => "uint16_t".into(),
                "u32" => "uint32_t".into(),
                "u64" => "uint64_t".into(),
                "i8" => "int8_t".into(),
                "i16" => "int16_t".into(),
                "i32" => "int32_t".into(),
                "i64" => "int64_t".into(),
                // **A path naming a table IS the struct.** The first version lowered it to
                // `uint32_t` and called that a coarsening in the safe direction -- it was not
                // coarse, it was wrong: `ptr<normal, r> Objekte` became `const uint32_t *`,
                // and the generated C would have compiled while pointing at the wrong thing.
                // *W9 asks for the direction of a coarsening; it does not license one where
                // the exact answer is available.*
                _ if u.tabellen.iter().any(|x| *x == n) => n,
                // **A named range type lowers to its carrier.** `type Zaehler = u32 in
                // 0 .. 65535` becomes `uint32_t`; the range itself is an M1 fact and stays in
                // the checker -- W6: what is left out of the C is left out because M1 carries
                // it, and for nothing else.
                _ if u.typen.contains_key(&n) => {
                    return ctyp(u.typen.get(&n)?, u);
                }
                // A named type whose carrier is not resolved here. Refused rather than
                // guessed -- see the head of this file.
                _ => return None,
            })
        }
        // `index into T` -- the bound comes from `count N` and is an M1 fact.
        TypExpr::Index { .. } => Some("uint32_t".into()),
        TypExpr::Zeiger(z) => {
            // **A pointer to a type this unit does not declare becomes an INCOMPLETE C type.**
            // `extern fn melde_roh(text : ptr<code, r> Text)` names `Text` and nowhere declares
            // it -- the fragment is an excerpt of a larger program.
            //
            // *This is not a guess.* C already carries exactly the rule the emitter would
            // otherwise have to invent: behind a pointer an incomplete type is legal, and any
            // use that needs the layout is a compile error. **The refusal is delegated, not
            // dropped** -- and it is delegated to the one tool that can decide it.
            let ziel = match ctyp(&z.ziel, u) {
                Some(z) => z,
                None => match &z.ziel {
                    TypExpr::Pfad(p) => format!("struct {}", p.teile.last()?.text),
                    _ => return None,
                },
            };
            let konst = if z.rechte.iter().any(|r| {
                matches!(
                    r,
                    Recht::Schreiben | Recht::LesenSchreiben | Recht::Eigen(_)
                )
            }) {
                ""
            } else {
                "const "
            };
            Some(format!("{konst}{ziel} *"))
        }
        _ => None,
    }
}

/// **A `spec fn` is specification and has no C.** Everything else with a body becomes a
/// definition; everything else *without* one becomes a **prototype** — without it a call in
/// C11 is an implicit declaration, and `-Werror` stops there.
fn funktion(f: &FnDecl, aus: &mut String, u: &Namen, absagen: &mut Absagen) {
    if matches!(f.klasse, Some(FnKlasse::Spec)) {
        return;
    }
    // **The ghost return becomes `void` — not a lowering but an ERASURE.** `mmu_an` hands the
    // boot token on; the token is the checker's argument and nothing the machine can hold.
    let rueck = match &f.ergebnis {
        Some(t) if ist_geist(t, u) => "void".into(),
        Some(t) => match ctyp(t, u) {
            Some(c) => c,
            None => {
                weigere(absagen, f.name.span, "return type");
                return;
            }
        },
        None => "void".into(),
    };
    let mut params = Vec::new();
    for p in &f.parameter {
        if ist_geist(&p.typ, u) {
            continue; // erased -- see above
        }
        match ctyp(&p.typ, u) {
            Some(c) => {
                let luecke = if c.ends_with('*') { "" } else { " " };
                params.push(format!("{c}{luecke}{}", p.name.text))
            }
            None => {
                weigere(absagen, p.name.span, "parameter type");
                return;
            }
        }
    }
    let liste = if params.is_empty() {
        "void".to_string()
    } else {
        params.join(", ")
    };
    let FnRumpf::Block(b) = &f.rumpf else {
        aus.push_str(&format!("\n{rueck} {}({liste});\n", f.name.text));
        return;
    };
    aus.push_str(&format!("\n{rueck} {}({liste}) {{\n", f.name.text));
    for s in &b.anweisungen {
        anweisung(s, aus, u, absagen);
    }
    aus.push_str("}\n");
}

fn anweisung(s: &Stmt, aus: &mut String, u: &Namen, absagen: &mut Absagen) {
    match &s.art {
        StmtArt::Return(Some(e)) => aus.push_str(&format!("    return {};\n", ausdruck(e, u))),
        StmtArt::Return(None) => aus.push_str("    return;\n"),
        StmtArt::Zuweisung(z) => {
            aus.push_str(&format!("    {} = {};\n", ort(&z.ziel, u), ausdruck(&z.wert, u)))
        }
        StmtArt::Ruf(r) => aus.push_str(&format!("    {};\n", ruf(r, u))),
        // **The third place the erasure has to hold, and the one that is silent if it does
        // not.** `let p1 = mmu_an(p);` binds a ghost: the BINDING goes, the CALL stays. Making
        // it `void p1 = mmu_an();` does not compile; dropping the whole statement compiles and
        // **computes something else** -- the boot step would simply not happen.
        StmtArt::Let(l) if geist_wert(&l.wert, u) => {
            aus.push_str(&format!("    {};\n", ausdruck(&l.wert, u)))
        }
        StmtArt::Let(l) => {
            // A non-ghost `let` needs a type, and the emitter does not guess one. The first
            // version wrote `uint32_t` unconditionally -- correct for the one file it was
            // built against and wrong for every other.
            let typ = l
                .typ
                .as_ref()
                .and_then(|t| ctyp(t, u))
                .or_else(|| ruf_rueckgabe(&l.wert, u));
            match typ {
                Some(c) => aus.push_str(&format!("    {c} {} = {};\n", l.name.text, ausdruck(&l.wert, u))),
                None => weigere(absagen, s.span, "`let` without a resolvable type"),
            }
        }
        _ => weigere(absagen, s.span, "statement kind"),
    }
}

/// Does this expression yield a ghost? Today: a call to a function with a ghost return.
fn geist_wert(e: &Expr, u: &Namen) -> bool {
    match &e.art {
        ExprArt::Ruf(r) => r
            .pfad
            .teile
            .last()
            .and_then(|i| u.funktionen.get(&i.text))
            .is_some_and(|s| s.geist_rueck),
        _ => false,
    }
}

/// The declared C return type of a called function — only used to type a `let`.
fn ruf_rueckgabe(_e: &Expr, _u: &Namen) -> Option<String> {
    None
}

/// **A call, with the ghost arguments dropped.** The positions come from the callee's
/// signature; an unknown callee keeps every argument, which cannot compile silently — it
/// fails at `cc`, and that is the direction to fail in.
fn ruf(r: &Ruf, u: &Namen) -> String {
    let name = r.pfad.teile.last().map(|i| i.text.clone()).unwrap_or_default();
    let geist = u.funktionen.get(&name).map(|s| s.geist_param.clone());
    let args: Vec<String> = r
        .argumente
        .iter()
        .enumerate()
        .filter(|(i, _)| !geist.as_ref().is_some_and(|g| *g.get(*i).unwrap_or(&false)))
        .map(|(_, a)| ausdruck(a, u))
        .collect();
    format!("{name}({})", args.join(", "))
}

fn ort(o: &Ort, u: &Namen) -> String {
    let mut t = o.basis.text.clone();
    let mut zeiger = true; // The base of a place in a function is a pointer parameter.
    for suf in &o.suffixe {
        match suf {
            OrtSuffix::Feld(f) => {
                t = if zeiger {
                    zeiger = false;
                    format!("{t}->{}", f.text)
                } else {
                    format!("{t}.{}", f.text)
                };
            }
            OrtSuffix::Ueber(f) => t = format!("{t}->{}", f.text),
            OrtSuffix::Index(e) => {
                zeiger = false;
                t = format!("{t}[{}]", ausdruck(e, u));
            }
        }
    }
    t
}

fn ausdruck(e: &Expr, u: &Namen) -> String {
    match &e.art {
        ExprArt::Zahl(n) => n.to_string(),
        ExprArt::Wahr => "true".into(),
        ExprArt::Falsch => "false".into(),
        ExprArt::Ort(o) => ort(o, u),
        ExprArt::Klammer(x) => format!("({})", ausdruck(x, u)),
        ExprArt::Binaer(op, a, b) => {
            format!("{} {} {}", ausdruck(a, u), op_text(op), ausdruck(b, u))
        }
        ExprArt::Ruf(r) => ruf(r, u),
        _ => "/* NOT LOWERED */ 0".into(),
    }
}

fn op_text(op: &BinOp) -> &'static str {
    match op {
        BinOp::Plus => "+",
        BinOp::Minus => "-",
        BinOp::Mal => "*",
        BinOp::Geteilt => "/",
        BinOp::Rest => "%",
        BinOp::BitUnd => "&",
        BinOp::BitOder => "|",
        BinOp::BitXor => "^",
        BinOp::SchiebLinks => "<<",
        BinOp::SchiebRechts => ">>",
        BinOp::Und => "&&",
        BinOp::Oder => "||",
        BinOp::Gleich => "==",
        BinOp::Ungleich => "!=",
        BinOp::Kleiner => "<",
        BinOp::Groesser => ">",
        BinOp::KleinerGleich => "<=",
        BinOp::GroesserGleich => ">=",
    }
}
