//! **The C emitter -- the first line of the largest undamageable surface.**
//!
//! Until 2026-08-17 this surface did not exist. `mutiere-pruefer.py` reported it with **0
//! mutations**, and *what has 0 mutations is not covered, it is undamageable*. Three things
//! hung on it: the plumbing class *refinement*, the templates `table.absenkung` and
//! `table.ops.erhaltung`, and the licence notice that `LIZENZ-ZUSATZ.md` demands in generated
//! C while nothing wrote it.
//!
//! ## What this emitter is, and what it deliberately is not
//!
//! **It is two translation units, not ten.** It covers exactly the forms that
//! `beispiele/16-by-ops-am-feld.gab` and `FRAGMENTE.md` F7 use: a `table` with `count`, range
//! types, `bool`, `index into T`, pointer parameters, field and index access, assignment,
//! `return`, calls, prototypes for bodiless declarations, and **the erasure of a
//! `linear ghost type`**. Anything else it **refuses by name** (`C001`) instead of emitting
//! something plausible.
//!
//! ## The erasure is the one thing here that is not a lowering
//!
//! A ghost value **does not exist at run time**. It has to vanish from the signature, from the
//! call site and from the `let` binding — three places at once, and two of the three failure
//! forms are silent. *The third is the dangerous one:* drop the whole `let` statement instead
//! of only its binding and the C compiles while the boot step **does not happen**. The
//! counter-probe of 2026-08-17 produced `6` where `123456` was expected — five of six steps
//! gone without a warning.
//!
//! > **A generator that emits something for a form it does not know is worse than one that
//! > stops.** The whole value of this crate is that its output is trustworthy; a silent
//! > approximation in the emitter would undo every pass in front of it.
//!
//! ## W6 holds here, and this is where it bites
//!
//! *The omission of a runtime check is justified by M1 alone, never by an invariant.* This
//! emitter omits **no** check, because it emits none yet -- but the rule is why `index into T`
//! becomes a plain `uint32_t` and not a range-checked accessor: the bound comes from `count N`
//! and is an M1 fact. The moment a check is left out here, the reason has to be an M1 fact and
//! stand in this file.

use gabbro_syntax::ast::*;
use gabbro_syntax::diag::{Absage, Absagen};
use std::collections::{BTreeSet, HashMap};

/// What the emitter must resolve: table names (a path naming one IS the struct), named
/// types (they lower to their carrier), **ghost types (they lower to NOTHING)** and the
/// signatures it needs in order to erase a ghost at a call site.
#[derive(Default)]
struct Namen {
    tabellen: Vec<String>,
    typen: HashMap<String, TypExpr>,
    /// `linear ghost type BootPhase;` — a value that **does not exist at run time**.
    geister: Vec<String>,
    funktionen: HashMap<String, Signatur>,
    /// Namen, die diese Einheit **nicht deklariert** und die nur hinter einem Zeiger
    /// vorkommen. Sie werden als unvollstaendiger C-Typ vorwaerts deklariert.
    fremde: BTreeSet<String>,
}

/// Ist `t` ein Zeiger auf einen Pfad, den diese Einheit nicht aufloest? Dann traegt sie
/// seinen Namen, aber nicht sein Layout -- und C hat dafuer bereits eine Form.
fn fremdes_ziel(t: &TypExpr, u: &Namen) -> Option<String> {
    let TypExpr::Zeiger(z) = t else { return None };
    if ctyp(&z.ziel, u).is_some() {
        return None;
    }
    match &z.ziel {
        TypExpr::Pfad(p) => Some(p.teile.last()?.text.clone()),
        _ => None,
    }
}

/// What must be known about a callee in order to erase a ghost **at the call site**.
struct Signatur {
    /// Per parameter: is it a ghost? A ghost argument is dropped from the C call.
    geist_param: Vec<bool>,
    /// Does it return a ghost? Then `let x = f(…)` loses its binding, **not its call**.
    geist_rueck: bool,
    /// Returns `option index into T`? Then the table name, for the sentinel comparison.
    option_rueck: Option<String>,
}

/// **Is this type a ghost — i.e. does it vanish in the C?**
///
/// This is the one question that separates an erasure from a lowering, and getting it wrong is
/// silent in both directions: erase too much and the C computes something else; erase too
/// little and it does not compile.
fn ist_geist(t: &TypExpr, u: &Namen) -> bool {
    match t {
        TypExpr::Pfad(p) => p
            .teile
            .last()
            .is_some_and(|i| u.geister.iter().any(|g| *g == i.text)),
        _ => false,
    }
}

/// **The licence notice, and it is not decoration.**
///
/// `LIZENZ-ZUSATZ.md` grants an additional permission under AGPL §7 -- *what you write in
/// Gabbro is not a derived work* -- and ties it to one condition: generated C carries this
/// header. **The compiler writes it itself**, because a condition that depends on the user
/// remembering it is not a condition.
pub const KOPF: &str = "\
/* Generated by Gabbro -- https://github.com/SimonVitzethum/Gabbro
 *
 * This file was generated. Edit the .gab source, not this file.
 *
 * Gabbro is AGPL-3.0 with an additional permission: this generated file and the program it
 * belongs to are NOT a derived work of Gabbro. The permission is conditional on this notice
 * being preserved. See LIZENZ-ZUSATZ.md.
 */
#include <stdint.h>
#include <stdbool.h>
";

/// Emits C for a tree, or refuses by name.
pub fn emittiere(baum: &Programm, absagen: &mut Absagen) -> String {
    let mut namen = Namen::default();
    crate::fuer_jedes_item(baum, &mut |item| match &item.art {
        ItemArt::Tabelle(t) => namen.tabellen.push(t.name.text.clone()),
        ItemArt::Typ(t) => {
            // **A ghost type has no body and no C.** `linear ghost type BootPhase;` declares a
            // value the checker threads and the machine never sees.
            if t.ghost {
                namen.geister.push(t.name.text.clone());
            } else if let Some(unter) = &t.rumpf {
                namen.typen.insert(t.name.text.clone(), unter.clone());
            }
        }
        _ => {}
    });
    // **Second pass, and it needs the first**: whether a parameter is a ghost can only be
    // decided once the ghost names are known.
    crate::fuer_jedes_item(baum, &mut |item| {
        if let ItemArt::Funktion(f) = &item.art {
            let sig = Signatur {
                geist_param: f.parameter.iter().map(|p| ist_geist(&p.typ, &namen)).collect(),
                geist_rueck: f.ergebnis.as_ref().is_some_and(|t| ist_geist(t, &namen)),
                option_rueck: match &f.ergebnis {
                    Some(TypExpr::Index { tabelle, optional: true, .. }) => {
                        Some(tabelle.text.clone())
                    }
                    _ => None,
                },
            };
            namen.funktionen.insert(f.name.text.clone(), sig);
        }
    });
    // **Dritter Sammelgang: die fremden Zeigerziele.** C verlangt den Tag VOR der
    // Parameterliste -- sonst hat er nur Prototyp-Reichweite, und `-Wall` sagt das zu Recht.
    let mut fremde = BTreeSet::new();
    crate::fuer_jedes_item(baum, &mut |item| {
        if let ItemArt::Funktion(f) = &item.art {
            for p in &f.parameter {
                fremde.extend(fremdes_ziel(&p.typ, &namen));
            }
            if let Some(r) = &f.ergebnis {
                fremde.extend(fremdes_ziel(r, &namen));
            }
        }
        if let ItemArt::Tabelle(tb) = &item.art {
            if let Some(slot) = &tb.slot {
                for f in &slot.felder {
                    if let SlotTyp::Typ(ty) = &f.typ {
                        fremde.extend(fremdes_ziel(ty, &namen));
                    }
                }
            }
        }
    });
    namen.fremde = fremde;

    let mut aus = String::from(KOPF);
    if !namen.fremde.is_empty() {
        aus.push_str(
            "\n/* Types this unit names but does not declare. Incomplete on purpose: C\n\
             \x20* refuses every use that needs the layout, which is the refusal this emitter\n\
             \x20* would otherwise have to invent. */\n",
        );
        for f in &namen.fremde {
            aus.push_str(&format!("struct {f};\n"));
        }
    }
    crate::fuer_jedes_item(baum, &mut |item| match &item.art {
        ItemArt::Konst(k) => {
            if let Some(w) = konst_zahl(&k.wert) {
                aus.push_str(&format!("\n#define {} {}u\n", k.name.text, w));
            } else {
                weigere(absagen, k.name.span, "const with a non-constant value");
            }
        }
        ItemArt::Typ(_) => {} // Range types lower to their carrier; see `ctyp`.
        ItemArt::Tabelle(t) => tabelle(t, &mut aus, &namen, absagen),
        // **Eine Sperre erzeugt zwei Prototypen und keine Zeile Rumpf.**
        //
        // Rang und Haltezeit stehen im C NIRGENDS: `H006` rechnet die Ordnung zur
        // Uebersetzungszeit nach, `K002`/`K004` die Haltezeiten -- und **was der Pruefer
        // entschieden hat, darf die Maschine nicht noch einmal pruefen** (W6, und hier ist
        // die Begruendung eine M1-artige: die Ordnung ist eine Eigenschaft des Programms,
        // keine des Laufs).
        //
        // Was bleibt, ist das Primitiv selbst, und **das ist Vertrauensbasis, nicht
        // Erzeugnis** -- es gehoert in die Axiomschicht wie `write_cr3`. Der Erzeuger nennt
        // es und definiert es nicht.
        ItemArt::Lock(l) => {
            aus.push_str(&format!(
                "\nvoid {n}_nimm(void);\nvoid {n}_gib(void);\n",
                n = l.name.text
            ));
            if l.geteilte_haltezeit.is_some() {
                aus.push_str(&format!(
                    "void {n}_nimm_geteilt(void);\nvoid {n}_gib_geteilt(void);\n",
                    n = l.name.text
                ));
            }
        }
        ItemArt::Funktion(f) => funktion(f, &mut aus, &namen, absagen),
        ItemArt::Modul(_) | ItemArt::Use(_) => {}
        _ => weigere(
            absagen,
            item.span,
            "this item kind has no lowering in this emitter yet",
        ),
    });
    aus
}

/// **C001 -- the emitter refuses instead of guessing.**
fn weigere(absagen: &mut Absagen, span: gabbro_syntax::span::Span, was: &str) {
    absagen.schiebe(
        Absage::fehler("C001", span, format!("no lowering: {was}")).mit_notiz(
            "the emitter refuses by name instead of emitting something plausible -- a \
             generator that guesses undoes every pass in front of it",
        ),
    );
}

fn konst_zahl(e: &Expr) -> Option<i128> {
    match &e.art {
        ExprArt::Zahl(n) => Some(*n as i128),
        _ => None,
    }
}

/// A table becomes a slot struct plus a carrier struct with a fixed-size array.
///
/// **`count N` is the whole reason the array is fixed.** Without it `index into T` has no
/// upper bound from the declaration, and this lowering would have to be a pointer plus a
/// length -- i.e. exactly the shape Gabbro exists to avoid.
fn tabelle(t: &Tabelle, aus: &mut String, u: &Namen, absagen: &mut Absagen) {
    let Some(n) = &t.kapazitaet else {
        weigere(absagen, t.span, "table without `count` -- the array would have no size");
        return;
    };
    aus.push_str(&format!("\ntypedef struct {{\n"));
    if let Some(slot) = &t.slot {
        for f in &slot.felder {
            let c = match &f.typ {
                SlotTyp::Typ(t) => ctyp(t, u),
                // `intty wrapping` -- the wraparound is DECLARED («B32»), so the C type is
                // the plain unsigned word whose wrap C already defines.
                SlotTyp::Wrapping(i) => Some(intty(i)),
            };
            match c {
                Some(c) => aus.push_str(&format!("    {c} {};\n", f.name.text)),
                None => weigere(absagen, f.name.span, "field type"),
            }
        }
    }
    aus.push_str(&format!("}} {}_slot;\n\ntypedef struct {{\n", t.name.text));
    let laenge = zahltext(n, absagen);
    aus.push_str(&format!(
        "    {}_slot slots[{}];\n}} {};\n",
        t.name.text, laenge, t.name.text
    ));
    // **Der Sonderwert fuer `option index into T`.** Er ist die Laenge selbst -- der eine
    // Wert, den ein gueltiger Index nach `count N` und M1 nie annimmt.
    aus.push_str(&format!(
        "#define {}_NONE ({})\n",
        t.name.text, laenge
    ));
}

fn intty(i: &IntTy) -> String {
    // The word IS the width -- `u32 wrapping` lowers to `uint32_t`, whose wraparound C
    // defines. «B32»: the wraparound is spoken at the declaration, not tolerated.
    match i.wort {
        gabbro_syntax::kw::Kw::U8 => "uint8_t",
        gabbro_syntax::kw::Kw::U16 => "uint16_t",
        gabbro_syntax::kw::Kw::U32 => "uint32_t",
        gabbro_syntax::kw::Kw::U64 => "uint64_t",
        gabbro_syntax::kw::Kw::I8 => "int8_t",
        gabbro_syntax::kw::Kw::I16 => "int16_t",
        gabbro_syntax::kw::Kw::I32 => "int32_t",
        _ => "int64_t",
    }
    .to_string()
}

/// The array length of a `table`. **A length this emitter cannot read is refused** — the same
/// reason as above, and here it decides how much memory the struct has.
fn zahltext(e: &Expr, absagen: &mut Absagen) -> String {
    match &e.art {
        ExprArt::Zahl(n) => n.to_string(),
        ExprArt::Ort(o) => o.text(),
        _ => {
            weigere(absagen, e.span, "table length");
            String::new()
        }
    }
}

/// The C type for a Gabbro type. **Range types lower to their carrier** -- the range itself is
/// an M1 fact and lives in the checker, not in the C.
fn ctyp(t: &TypExpr, u: &Namen) -> Option<String> {
    match t {
        TypExpr::Int(i) => Some(intty(i)),
        TypExpr::Bool(_) => Some("bool".into()),
        TypExpr::Pfad(p) => {
            let n = p.teile.last()?.text.clone();
            Some(match n.as_str() {
                "bool" => "bool".into(),
                "u8" => "uint8_t".into(),
                "u16" => "uint16_t".into(),
                "u32" => "uint32_t".into(),
                "u64" => "uint64_t".into(),
                "i8" => "int8_t".into(),
                "i16" => "int16_t".into(),
                "i32" => "int32_t".into(),
                "i64" => "int64_t".into(),
                // **A path naming a table IS the struct.** The first version lowered it to
                // `uint32_t` and called that a coarsening in the safe direction -- it was not
                // coarse, it was wrong: `ptr<normal, r> Objekte` became `const uint32_t *`,
                // and the generated C would have compiled while pointing at the wrong thing.
                // *W9 asks for the direction of a coarsening; it does not license one where
                // the exact answer is available.*
                _ if u.tabellen.iter().any(|x| *x == n) => n,
                // **A named range type lowers to its carrier.** `type Zaehler = u32 in
                // 0 .. 65535` becomes `uint32_t`; the range itself is an M1 fact and stays in
                // the checker -- W6: what is left out of the C is left out because M1 carries
                // it, and for nothing else.
                _ if u.typen.contains_key(&n) => {
                    return ctyp(u.typen.get(&n)?, u);
                }
                // A named type whose carrier is not resolved here. Refused rather than
                // guessed -- see the head of this file.
                _ => return None,
            })
        }
        // `index into T` -- the bound comes from `count N` and is an M1 fact.
        //
        // **`option index into T` carries a SENTINEL, and the sentinel is `N` itself.**
        //
        // The representation was open until 2026-08-17 and the emitter refused rather than
        // coarsen — lowering the option to a bare `uint32_t` would have erased the `None`
        // silently. The decision now taken is the cheap one, and it is *cheap because of
        // `count N`*: the index type is `0 ..< N`, so **`N` is the one value M1 guarantees no
        // real index ever takes.** No extra word, no tag.
        //
        // > *And it is what the measured code already does by hand:* Caprock walks its queues
        // > as `while i != NIL { i = t.qnext }` (`MESSUNGEN.md`, B3). The construct does not
        // > invent the sentinel — it makes it checked and names it once.
        //
        // **The obligation this buys is entered in the register** as `option.sentinel`: the
        // sentinel is outside the index domain, and no arithmetic reaches it.
        TypExpr::Index { .. } => Some("uint32_t".into()),
        TypExpr::Zeiger(z) => {
            // **A pointer to a type this unit does not declare becomes an INCOMPLETE C type.**
            // `extern fn melde_roh(text : ptr<code, r> Text)` names `Text` and nowhere declares
            // it -- the fragment is an excerpt of a larger program.
            //
            // *This is not a guess.* C already carries exactly the rule the emitter would
            // otherwise have to invent: behind a pointer an incomplete type is legal, and any
            // use that needs the layout is a compile error. **The refusal is delegated, not
            // dropped** -- and it is delegated to the one tool that can decide it.
            let ziel = match ctyp(&z.ziel, u) {
                Some(z) => z,
                None => match &z.ziel {
                    TypExpr::Pfad(p) => format!("struct {}", p.teile.last()?.text),
                    _ => return None,
                },
            };
            let konst = if z.rechte.iter().any(|r| {
                matches!(
                    r,
                    Recht::Schreiben | Recht::LesenSchreiben | Recht::Eigen(_)
                )
            }) {
                ""
            } else {
                "const "
            };
            Some(format!("{konst}{ziel} *"))
        }
        _ => None,
    }
}

/// **A `spec fn` is specification and has no C.** Everything else with a body becomes a
/// definition; everything else *without* one becomes a **prototype** — without it a call in
/// C11 is an implicit declaration, and `-Werror` stops there.
fn funktion(f: &FnDecl, aus: &mut String, u: &Namen, absagen: &mut Absagen) {
    if matches!(f.klasse, Some(FnKlasse::Spec)) {
        return;
    }
    // **The ghost return becomes `void` — not a lowering but an ERASURE.** `mmu_an` hands the
    // boot token on; the token is the checker's argument and nothing the machine can hold.
    let rueck = match &f.ergebnis {
        Some(t) if ist_geist(t, u) => "void".into(),
        // **`-> never` heisst `_Noreturn void`.** Ohne das Wort sieht der C-Uebersetzer die
        // Fehlerzweige als durchfallend an -- genau der Grund, aus dem `S002` im Gabbro sechs
        // Mal ansprang, bevor `exit()` sein `-> never` bekam (`FRAGMENTE.md` F5).
        Some(TypExpr::Never(_)) => "_Noreturn void".into(),
        Some(t) => match ctyp(t, u) {
            Some(c) => c,
            None => {
                weigere(absagen, f.name.span, "return type");
                return;
            }
        },
        None => "void".into(),
    };
    let mut params = Vec::new();
    for p in &f.parameter {
        if ist_geist(&p.typ, u) {
            continue; // erased -- see above
        }
        match ctyp(&p.typ, u) {
            Some(c) => {
                let luecke = if c.ends_with('*') { "" } else { " " };
                params.push(format!("{c}{luecke}{}", p.name.text))
            }
            None => {
                weigere(absagen, p.name.span, "parameter type");
                return;
            }
        }
    }
    let liste = if params.is_empty() {
        "void".to_string()
    } else {
        params.join(", ")
    };
    let FnRumpf::Block(b) = &f.rumpf else {
        aus.push_str(&format!("\n{rueck} {}({liste});\n", f.name.text));
        return;
    };
    aus.push_str(&format!("\n{rueck} {}({liste}) {{\n", f.name.text));
    // **`(void)k;` fuer jeden Parameter, den der Rumpf nicht liest -- und das ist ein Befund,
    // kein Kunstgriff.**
    //
    // `FRAGMENTE.md` F8 nimmt `toeten(l, t, k)` und liest `k` nie: die Funktion loest `t`
    // stattdessen neu auf. **`cc -Wextra` sagt das, und KEIN Pass dieses Uebersetzers sagt
    // es** -- der C-Uebersetzer hat hier etwas gefunden, wofuer Gabbro keine Diagnose hat.
    //
    // > *Der Befund gehoert auf die Gabbro-Ebene, nicht ins Erzeugnis.* Der Anwender hat die
    // > erzeugte Zeile nicht geschrieben; eine Warnung darin sagt nichts ueber ihn. Deshalb
    // > wird sie hier stillgelegt **und in `TODO.md` als fehlender Pass gebucht** -- nicht
    // > verschwiegen, sondern an die richtige Stelle gelegt.
    let mut gelesen = std::collections::BTreeSet::new();
    benutzte_namen(b, &mut gelesen);
    for p in &f.parameter {
        if !ist_geist(&p.typ, u) && !gelesen.contains(&p.name.text) {
            aus.push_str(&format!("    (void){};\n", p.name.text));
        }
    }
    for s in &b.anweisungen {
        anweisung(s, aus, u, absagen, 1, &Vec::new());
    }
    aus.push_str("}\n");
}

/// Welche Namen liest dieser Rumpf? Nur die Formen, die der Erzeuger ueberhaupt absenkt --
/// jede andere wird ohnehin abgelehnt.
fn benutzte_namen(b: &Block, aus: &mut std::collections::BTreeSet<String>) {
    fn e(x: &Expr, aus: &mut std::collections::BTreeSet<String>) {
        match &x.art {
            ExprArt::Ort(o) => o_(o, aus),
            ExprArt::Klammer(y) | ExprArt::Unaer(_, y) => e(y, aus),
            ExprArt::Binaer(_, a, c) => {
                e(a, aus);
                e(c, aus);
            }
            ExprArt::Ruf(r) => {
                for a in &r.argumente {
                    e(a, aus);
                }
            }
            _ => {}
        }
    }
    fn o_(o: &Ort, aus: &mut std::collections::BTreeSet<String>) {
        aus.insert(o.basis.text.clone());
        for s in &o.suffixe {
            if let OrtSuffix::Index(x) = s {
                e(x, aus);
            }
        }
    }
    for s in &b.anweisungen {
        match &s.art {
            StmtArt::Return(Some(x)) => e(x, aus),
            StmtArt::Zuweisung(z) => {
                o_(&z.ziel, aus);
                e(&z.wert, aus);
            }
            StmtArt::Ruf(r) => {
                for a in &r.argumente {
                    e(a, aus);
                }
            }
            StmtArt::Let(l) => e(&l.wert, aus),
            StmtArt::Sperrt(x) => benutzte_namen(&x.rumpf, aus),
            StmtArt::Match(m) => {
                e(&m.gegenstand, aus);
                for z in &m.zweige {
                    benutzte_namen(&z.rumpf, aus);
                }
            }
            _ => {}
        }
    }
}

/// **Die Austrittsliste -- der Grund, warum `locks` nicht nur zwei Zeilen ist.**
///
/// In einem `locks`-Block darf kein `return` die Sperre stehen lassen. Die Liste traegt die
/// Freigaben der offenen Bloecke, innerste zuletzt; vor jedem `return` werden sie **in
/// umgekehrter Reihenfolge** ausgegeben.
///
/// > *Das ist woertlich die Klasse, die C8 bezahlt hat:* ein neuer Abweispfad erbt die
/// > Aufraeumpflicht des alten nicht. Hier erbt er sie, weil nicht der Schreiber sie ausgibt.
type Austritt = Vec<String>;

fn einzug(n: usize) -> String {
    "    ".repeat(n)
}

fn anweisung(
    s: &Stmt,
    aus: &mut String,
    u: &Namen,
    absagen: &mut Absagen,
    tiefe: usize,
    austritt: &Austritt,
) {
    let e = einzug(tiefe);
    match &s.art {
        StmtArt::Return(w) => {
            // **Erst freigeben, dann zurueckkehren** -- und zwar fuer JEDEN offenen Block.
            for freigabe in austritt.iter().rev() {
                aus.push_str(&format!("{e}{freigabe};\n"));
            }
            match w {
                Some(x) => aus.push_str(&format!("{e}return {};\n", ausdruck(x, u, absagen))),
                None => aus.push_str(&format!("{e}return;\n")),
            }
        }
        // **Der Operator wurde bis zum 2026-08-17 IGNORIERT:** `x += 1` wurde `x = 1`. Er
        // ist in keiner der drei Waechtereinheiten vorgekommen -- und genau darum hat er
        // ueberlebt. *Dieselbe Sorte stiller Ausfall wie die Null im Ausdruckszweig.*
        StmtArt::Zuweisung(z) => aus.push_str(&format!(
            "{e}{} {} {};\n",
            ort(&z.ziel, u, absagen),
            zuw_op(&z.op),
            ausdruck(&z.wert, u, absagen)
        )),
        // **`narrow x to a .. b else { … }` ist die einzige Laufzeitpruefung, die dieser
        // Erzeuger ausgibt** -- und sie steht hier, weil die Sprache sie als Pruefung
        // DEFINIERT, nicht weil M1 versagt haette. *W6 gilt in die andere Richtung: was M1
        // traegt, wird weggelassen; was `narrow` heisst, bleibt stehen.*
        StmtArt::Narrow(n) => {
            let o = ort(&n.ort, u, absagen);
            let von = ausdruck(&n.bereich.von, u, absagen);
            let bis = ausdruck(&n.bereich.bis, u, absagen);
            let oben = if n.bereich.exklusiv { "<" } else { "<=" };
            aus.push_str(&format!("{e}if (!({o} >= {von} && {o} {oben} {bis})) {{\n"));
            for k in &n.sonst.anweisungen {
                anweisung(k, aus, u, absagen, tiefe + 1, austritt);
            }
            aus.push_str(&format!("{e}}}\n"));
        }
        StmtArt::Ruf(r) => aus.push_str(&format!("{e}{};\n", ruf(r, u, absagen))),
        // **The third place the ghost erasure has to hold, and the one that is silent if it
        // does not.** `let p1 = mmu_an(p);` binds a ghost: the BINDING goes, the CALL stays.
        // Making it `void p1 = mmu_an();` does not compile; dropping the whole statement
        // compiles and **computes something else** -- the boot step would simply not happen.
        StmtArt::Let(l) if geist_wert(&l.wert, u) => {
            aus.push_str(&format!("{e}{};\n", ausdruck(&l.wert, u, absagen)))
        }
        StmtArt::Let(l) => {
            // A non-ghost `let` needs a type, and the emitter does not guess one. The first
            // version wrote `uint32_t` unconditionally -- correct for the one file it was
            // built against and wrong for every other.
            match l.typ.as_ref().and_then(|t| ctyp(t, u)) {
                Some(c) => aus.push_str(&format!(
                    "{e}{c} {} = {};\n",
                    l.name.text,
                    ausdruck(&l.wert, u, absagen)
                )),
                None => weigere(absagen, s.span, "`let` without a resolvable type"),
            }
        }
        // **`locks X { … }` -- die Sperre selbst ist eine Vertrauensbasis, die DISZIPLIN
        // nicht.** Rang und Haltezeit stehen im C nirgends: `H006` und `K002` rechnen sie zur
        // Uebersetzungszeit nach, und was der Pruefer entschieden hat, muss die Maschine nicht
        // noch einmal pruefen (W6). Was bleibt, ist Nehmen und Geben -- und dass GEGEBEN wird,
        // auf jedem Pfad.
        StmtArt::Sperrt(x) => {
            let name = x.sperre.text();
            let (nimm, gib) = if x.geteilt {
                (format!("{name}_nimm_geteilt()"), format!("{name}_gib_geteilt()"))
            } else {
                (format!("{name}_nimm()"), format!("{name}_gib()"))
            };
            aus.push_str(&format!("{e}{nimm};\n{e}{{\n"));
            let mut innen = austritt.clone();
            innen.push(gib.clone());
            for k in &x.rumpf.anweisungen {
                anweisung(k, aus, u, absagen, tiefe + 1, &innen);
            }
            aus.push_str(&format!("{e}}}\n{e}{gib};\n"));
        }
        // **`match` ueber einem `option index into T`.** Der Sonderwert macht daraus einen
        // Vergleich; die Bindung des `Some`-Zweigs ist der Wert selbst.
        StmtArt::Match(m) => match_option(m, s, aus, u, absagen, tiefe, austritt),
        _ => weigere(absagen, s.span, "statement kind"),
    }
}

/// Nur `match` ueber einer Option wird abgesenkt. **Ein `match` ueber einem `tagged type` ist
/// eine eigene Entwurfsfrage** (markierter Verbund, Variantennummern, Nutzlast) und wird
/// abgelehnt statt geraten.
fn match_option(
    m: &MatchStmt,
    s: &Stmt,
    aus: &mut String,
    u: &Namen,
    absagen: &mut Absagen,
    tiefe: usize,
    austritt: &Austritt,
) {
    let e = einzug(tiefe);
    let Some(tabelle) = option_quelle(&m.gegenstand, u) else {
        weigere(absagen, s.span, "`match` over something other than an `option index into T`");
        return;
    };
    let namen: Vec<&str> = m.zweige.iter().map(|z| z.variante.text.as_str()).collect();
    if namen.len() != 2 || !namen.contains(&"Some") || !namen.contains(&"None") {
        weigere(absagen, s.span, "`match` over an option needs exactly `Some` and `None`");
        return;
    }
    let ja = m.zweige.iter().find(|z| z.variante.text == "Some").unwrap();
    let nein = m.zweige.iter().find(|z| z.variante.text == "None").unwrap();
    let hilf = format!("_o{}", tiefe);

    aus.push_str(&format!(
        "{e}{{\n{e}    uint32_t {hilf} = {};\n{e}    if ({hilf} != {tabelle}_NONE) {{\n",
        ausdruck(&m.gegenstand, u, absagen)
    ));
    if let Some(b) = &ja.binder {
        aus.push_str(&format!("{e}        uint32_t {} = {hilf};\n", b.text));
    }
    for k in &ja.rumpf.anweisungen {
        anweisung(k, aus, u, absagen, tiefe + 2, austritt);
    }
    aus.push_str(&format!("{e}    }} else {{\n"));
    for k in &nein.rumpf.anweisungen {
        anweisung(k, aus, u, absagen, tiefe + 2, austritt);
    }
    aus.push_str(&format!("{e}    }}\n{e}}}\n"));
}

/// Liefert den Tabellennamen, wenn dieser Ausdruck ein `option index into T` ist.
fn option_quelle(e: &Expr, u: &Namen) -> Option<String> {
    match &e.art {
        ExprArt::Ruf(r) => u
            .funktionen
            .get(&r.pfad.teile.last()?.text)?
            .option_rueck
            .clone(),
        _ => None,
    }
}

/// Does this expression yield a ghost? Today: a call to a function with a ghost return.
fn geist_wert(e: &Expr, u: &Namen) -> bool {
    match &e.art {
        ExprArt::Ruf(r) => r
            .pfad
            .teile
            .last()
            .and_then(|i| u.funktionen.get(&i.text))
            .is_some_and(|s| s.geist_rueck),
        _ => false,
    }
}

/// **A call, with the ghost arguments dropped.** The positions come from the callee's
/// signature; an unknown callee keeps every argument, which cannot compile silently — it
/// fails at `cc`, and that is the direction to fail in.
fn ruf(r: &Ruf, u: &Namen, absagen: &mut Absagen) -> String {
    let name = r.pfad.teile.last().map(|i| i.text.clone()).unwrap_or_default();
    // **«B35»: `Some`/`None` are CONSTRUCTORS, not calls.** The old path emitted `None()` —
    // an implicit declaration that `-Werror` happens to catch. *Happening to fail is not
    // refusing.* Their lowering waits on the same decision as `option index into T`.
    if name == "Some" || name == "None" {
        weigere(absagen, r.span, "`option` constructor -- `option` has no representation yet");
        return String::new();
    }
    let geist = u.funktionen.get(&name).map(|s| s.geist_param.clone());
    let args: Vec<String> = r
        .argumente
        .iter()
        .enumerate()
        .filter(|(i, _)| !geist.as_ref().is_some_and(|g| *g.get(*i).unwrap_or(&false)))
        .map(|(_, a)| ausdruck(a, u, absagen))
        .collect();
    format!("{name}({})", args.join(", "))
}

fn ort(o: &Ort, u: &Namen, absagen: &mut Absagen) -> String {
    let mut t = o.basis.text.clone();
    let mut zeiger = true; // The base of a place in a function is a pointer parameter.
    for suf in &o.suffixe {
        match suf {
            OrtSuffix::Feld(f) => {
                t = if zeiger {
                    zeiger = false;
                    format!("{t}->{}", f.text)
                } else {
                    format!("{t}.{}", f.text)
                };
            }
            OrtSuffix::Ueber(f) => t = format!("{t}->{}", f.text),
            OrtSuffix::Index(e) => {
                zeiger = false;
                t = format!("{t}[{}]", ausdruck(e, u, absagen));
            }
        }
    }
    t
}

/// **Every expression form this emitter does not know is REFUSED.**
///
/// Until 2026-08-17 the fallback here read `"/* NOT LOWERED */ 0"` — *it compiled, and it
/// computed zero.* A fail-open path in the one component whose whole design is "refuse rather
/// than guess", and a comment nobody reads is not a refusal.
fn ausdruck(e: &Expr, u: &Namen, absagen: &mut Absagen) -> String {
    match &e.art {
        ExprArt::Zahl(n) => n.to_string(),
        ExprArt::Wahr => "true".into(),
        ExprArt::Falsch => "false".into(),
        ExprArt::Ort(o) => ort(o, u, absagen),
        ExprArt::Klammer(x) => format!("({})", ausdruck(x, u, absagen)),
        ExprArt::Binaer(op, a, b) => {
            format!("{} {} {}", ausdruck(a, u, absagen), op_text(op), ausdruck(b, u, absagen))
        }
        ExprArt::Ruf(r) => ruf(r, u, absagen),
        _ => {
            weigere(absagen, e.span, "expression form");
            String::new()
        }
    }
}

fn zuw_op(op: &ZuwOp) -> &'static str {
    match op {
        ZuwOp::Setzt => "=",
        ZuwOp::Plus => "+=",
        ZuwOp::Minus => "-=",
        ZuwOp::Und => "&=",
        ZuwOp::Oder => "|=",
    }
}

fn op_text(op: &BinOp) -> &'static str {
    match op {
        BinOp::Plus => "+",
        BinOp::Minus => "-",
        BinOp::Mal => "*",
        BinOp::Geteilt => "/",
        BinOp::Rest => "%",
        BinOp::BitUnd => "&",
        BinOp::BitOder => "|",
        BinOp::BitXor => "^",
        BinOp::SchiebLinks => "<<",
        BinOp::SchiebRechts => ">>",
        BinOp::Und => "&&",
        BinOp::Oder => "||",
        BinOp::Gleich => "==",
        BinOp::Ungleich => "!=",
        BinOp::Kleiner => "<",
        BinOp::Groesser => ">",
        BinOp::KleinerGleich => "<=",
        BinOp::GroesserGleich => ">=",
    }
}
