//! **The user's obligation over a G program term (the goal's duties, stated).**
//!
//! `gabbro lean-g` writes the program as ONE declaration (`gD`, `gP`, the
//! member lists `gFs`/`gLs`/`gCs`, the lock-invariant family `gS`, the
//! declared starts and initial memory as `gE : Einheit gD`, the two
//! decidable checks). This module runs that export and appends what the
//! goal theorem `gabbro_ziel` (`Zielsatz/BeweisAtomar.lean`) asks the USER
//! for -- stated, never discharged: `NutzerPflichtA gE` (the bodies'
//! `LogikPflichtA`, with the atomic rely since lane O25c, and the
//! `StartPflicht`), with the closing theorems `gP_gabbro`/`gP_gabbro_f`
//! deriving the conclusion of `GabbroZiel` for `gE` from `gabbro_ziel` --
//! the checker premise (`akzeptiertX_pruefer` on the member lists)
//! discharged here `by decide`, the user obligation an open hypothesis.
//!
//! The obligation is stated through the IMPORTED definition
//! `NutzerPflichtA`, never by copying its body: a change to what the goal
//! asks cannot silently age the stated duty. The namespace is the lean-g
//! one with `_oblig` appended, so this export and the plain `lean-g`
//! export of the same file never declare the same names. Every form
//! `lean-g` refuses is refused here with the same `LG` code -- this module
//! adds no refusal, code or otherwise, of its own.

use gabbro_syntax::ast::*;

use crate::lean_g::{export_ns, namespace_of, Refusal};

/// The extra imports the obligation section needs (the goal theorem, the
/// concrete checker and the obligation definitions). They must precede
/// every command, so they are inserted beside the lean-g imports rather
/// than appended.
const MEHR_IMPORT: &str =
    "import Grammatik.Zielsatz.Akzeptiert\nimport Grammatik.Zielsatz.Beweis\nimport Grammatik.Zielsatz.BeweisAtomar\n";

/// Export the checked unit as a Lean file with the user's obligations
/// stated, or refuse it by name exactly where `lean-g` refuses it.
pub fn export(source_name: &str, tree: &Programm) -> Result<String, Refusal> {
    let ns = format!("{}_oblig", namespace_of(source_name));
    let text = export_ns(source_name, tree, &ns)?;
    // Name the real command: the body below is the lean-g export, the rest
    // is this subcommand's.
    let lean_zeile =
        format!("-- GENERATED by `gabbro lean-g {source_name}` -- do not edit.\n");
    let oblig_zeile = format!(
        "-- GENERATED by `gabbro obligations --g {source_name}` \
         (lean-g export plus the stated obligation) -- do not edit.\n"
    );
    let text = text.replacen(lean_zeile.as_str(), oblig_zeile.as_str(), 1);
    // The anchor is written unconditionally by the lean-g export above.
    let anchor = "import Grammatik.SperreSem\n";
    let mut text = text.replacen(anchor, &format!("{anchor}{MEHR_IMPORT}"), 1);
    let schluss = format!("end {ns}\n\nend Gabbro.Grammatik\n");
    let rumpf = text
        .strip_suffix(schluss.as_str())
        .expect("lean-g export ends its namespaces")
        .to_string();
    text = rumpf;
    text.push_str(&abschnitt());
    text.push_str(&crate::freigabe::freigabe_abschnitt(tree, ""));
    text.push_str(&schluss);
    Ok(text)
}

/// The appended obligation section, inside the program's namespace.
///
/// Since Opus lane O25c (2026-09-26) the goal theorem carries the ATOMIC RELY: its checker is
/// `akzeptiertX_pruefer` (the Bool `AkzeptiertX`), the user's duty `NutzerPflichtA` (the bodies
/// against every value a read of a shared atomic of the unit may return; on a unit without one
/// it is `NutzerPflicht`), and the conclusion is `ZielX`/`ZielFX` over machine GX, whose reads
/// of the unit's admitted shared atomics (`GeteiltV gE.P gE.ws`) the weak memory answers.
fn abschnitt() -> String {
    let mut out = String::new();
    out.push_str("-- THE USER'S OBLIGATION (stated, not discharged).\n");
    out.push_str("--\n");
    out.push_str("-- `NutzerPflichtA gE`: the bodies' logic WITH THE ATOMIC RELY (`LogikPflichtA`\n");
    out.push_str("-- -- per function and at EVERY `forever` budget the body triple against\n");
    out.push_str("-- every value a read of a shared atomic of the unit may return, with caller\n");
    out.push_str("-- duty and no `logik` outcome, owed invariants at value AND reason exits)\n");
    out.push_str("-- and the start obligation (`StartPflicht` -- every lock invariant at\n");
    out.push_str("-- `gE.sp0`, every declared start's `requires` there with its declared\n");
    out.push_str("-- arguments). On a unit without a shared atomic it is `NutzerPflicht gE`.\n");
    out.push_str("-- A `def` with no proof: the proof is the user's job. Stated through the\n");
    out.push_str("-- IMPORTED definition `NutzerPflichtA`; its body is never copied here.\n");
    out.push_str("def nutzerPflicht : Prop := Zielsatz.NutzerPflichtA gE\n\n");
    out.push_str("-- The member lists are complete (the `Aufzaehlung`s the goal theorem\n");
    out.push_str("-- quantifies over), decided here so the closing theorem below needs no\n");
    out.push_str("-- program fact beyond the user's obligation.\n");
    out.push_str("theorem gFs_voll : ∀ g : gD.Fn, g ∈ gFs := by\n  intro g\n  cases g <;> decide\n\n");
    out.push_str("theorem gLs_voll : ∀ L : gD.Lock, L ∈ gLs := by\n  intro L\n  cases L <;> decide\n\n");
    out.push_str("-- Carriers are tables or globals (lane 198 exports `static mut`\n");
    out.push_str("-- globals; a unit without one has `Glob := Empty`), and each arm\n");
    out.push_str("-- closes by cases over its constructors. `simp [gCs]`\n");
    out.push_str("-- and not `decide`: `DecidableEq (gD.Tab ⊕ gD.Glob)` does not unfold\n");
    out.push_str("-- the `gD` declaration during instance search (measured on 104/108:\n");
    out.push_str("-- `failed to synthesize Decidable (Sum.inl … ∈ gCs)`), while `simp`\n");
    out.push_str("-- rewrites membership over the literal list to constructor equalities.\n");
    out.push_str("theorem gCs_voll : ∀ c : gD.Tab ⊕ gD.Glob, c ∈ gCs := by\n  intro c\n");
    out.push_str("  cases c with\n  | inl t => cases t <;> simp [gCs]\n  | inr g => cases g <;> simp [gCs]\n\n");
    out.push_str("-- The checker premise, discharged here: the concrete checker of the\n");
    out.push_str("-- goal theorem (`akzeptiertX_pruefer`, the Bool `AkzeptiertX`) accepts\n");
    out.push_str("-- this program on these lists. Where it does not, this `decide` fails --\n");
    out.push_str("-- loudly, not wrongly.\n");
    out.push_str("theorem gCheck : Zielsatz.akzeptiertX_pruefer.akzeptiert gE gFs gLs gCs = true := by decide\n\n");
    out.push_str("-- THE CLOSING THEOREM: the conclusion of `GabbroZiel` for this program on\n");
    out.push_str("-- every run of machine GX with every thread live (`gabbro_ziel_gx`). The\n");
    out.push_str("-- checker premise travels discharged (`gCheck`); the user's obligation\n");
    out.push_str("-- stays open as a hypothesis -- that is the point. Apply it once\n");
    out.push_str("-- `nutzerPflicht` is proved.\n");
    out.push_str("theorem gP_gabbro (hN : Zielsatz.NutzerPflichtA gE) (O : Orakel gD)\n");
    out.push_str("    (hH : Zielsatz.HardwareAnnahmen O gE.Q) (passes : Nat)\n");
    out.push_str("    (sp : Speicher gD.mitRuhe)\n");
    out.push_str("    (init : Faden → Σ f : gD.mitRuhe.Fn, Env gD.mitRuhe (gD.mitRuhe.params f))\n");
    out.push_str("    (hL : Zielsatz.Laufzeit gE sp init) (M : RufMaschineG gD.mitRuhe)\n");
    out.push_str("    (hr : RufErreichbarGX gE.P.mitRuhe O.mitRuhe passes (Zielsatz.GeteiltV (D := gD) gE.P gE.ws)\n");
    out.push_str("      (RufStartG gE.P.mitRuhe sp init) M) :\n");
    out.push_str("    Zielsatz.ZielX gE.P.mitRuhe gE.S.mitRuhe O.mitRuhe passes (Zielsatz.GeteiltV (D := gD) gE.P gE.ws)\n");
    out.push_str("      (RufStartG gE.P.mitRuhe sp init) M :=\n");
    out.push_str("  Zielsatz.gabbro_ziel_gx Zielsatz.akzeptiertX_pruefer gD gE ⟨gFs, gFs_voll⟩ ⟨gLs, gLs_voll⟩ ⟨gCs, gCs_voll⟩\n");
    out.push_str("    gCheck hN O hH passes sp init hL M hr\n\n");
    // Opus agent C (2026-09-26): the certificate carries the WHOLE conclusion of
    // `GabbroZiel`, not only its all-live corollary: `ZielFX` on every reachable
    // THREAD machine over GX, from any set of initially live threads (spawns by
    // `start`/`child` and their joins included). `gP_gabbro` above stays, as the
    // all-live reading.
    out.push_str("-- THE CLOSING THEOREM ON THE THREAD MACHINE: `GabbroZiel` itself for this\n");
    out.push_str("-- program -- `ZielFX` on every reachable thread machine over GX (run-time\n");
    out.push_str("-- spawns and joins included), from any set of initially live threads.\n");
    out.push_str("theorem gP_gabbro_f (hN : Zielsatz.NutzerPflichtA gE) (O : Orakel gD)\n");
    out.push_str("    (hH : Zielsatz.HardwareAnnahmen O gE.Q) (passes : Nat)\n");
    out.push_str("    (sp : Speicher gD.mitRuhe)\n");
    out.push_str("    (init : Faden → Σ f : gD.mitRuhe.Fn, Env gD.mitRuhe (gD.mitRuhe.params f))\n");
    out.push_str("    (hL : Zielsatz.Laufzeit gE sp init) (lebt0 : Faden → Bool)\n");
    out.push_str("    (K : FadenMaschine gD.mitRuhe)\n");
    out.push_str("    (hK : FadenErreichbarX gE.P.mitRuhe O.mitRuhe passes (Zielsatz.GeteiltV (D := gD) gE.P gE.ws)\n");
    out.push_str("      (FadenStart gE.P.mitRuhe sp init lebt0) K) :\n");
    out.push_str("    Zielsatz.ZielFX gE.P.mitRuhe gE.S.mitRuhe O.mitRuhe passes (Zielsatz.GeteiltV (D := gD) gE.P gE.ws)\n");
    out.push_str("      (RufStartG gE.P.mitRuhe sp init) K :=\n");
    out.push_str("  Zielsatz.gabbro_ziel Zielsatz.akzeptiertX_pruefer gD gE ⟨gFs, gFs_voll⟩ ⟨gLs, gLs_voll⟩ ⟨gCs, gCs_voll⟩\n");
    out.push_str("    gCheck hN O hH passes sp init hL lebt0 K hK\n");
    out
}

// ---------------------------------------------------------------------------------------
// O12: the release obligation, STATED in the obligation channel -- the analysis is
// `crate::freigabe` (shared with `gabbro counterexample` since fix lane F7).
