//! **The user's obligation over a G program term (the goal's duties, stated).**
//!
//! `gabbro lean-g` writes the program as ONE declaration (`gD`, `gP`, the
//! member lists `gFs`/`gLs`/`gCs`, the lock-invariant family `gS`, the
//! declared starts and initial memory as `gE : Einheit gD`, the two
//! decidable checks). This module runs that export and appends what the
//! goal theorem `gabbro_ziel` (`Zielsatz/Beweis.lean`) asks the USER for --
//! stated, never discharged: `NutzerPflicht gE` (the bodies' `LogikPflicht`
//! and the `StartPflicht`), with the closing theorem `gP_gabbro` deriving
//! the conclusion of `GabbroZiel` for `gE` from `gabbro_ziel` -- the
//! checker premise (`akzeptiert_pruefer` on the member lists) discharged
//! here `by decide`, the user obligation an open hypothesis.
//!
//! The obligation is stated through the IMPORTED definition
//! `NutzerPflicht`, never by copying its body: a change to what the goal
//! asks cannot silently age the stated duty. The namespace is the lean-g
//! one with `_oblig` appended, so this export and the plain `lean-g`
//! export of the same file never declare the same names. Every form
//! `lean-g` refuses is refused here with the same `LG` code -- this module
//! adds no refusal, code or otherwise, of its own.

use gabbro_syntax::ast::*;

use crate::lean_g::{export_ns, namespace_of, Refusal};

/// The extra imports the obligation section needs (the goal theorem, the
/// concrete checker and the obligation definitions). They must precede
/// every command, so they are inserted beside the lean-g imports rather
/// than appended.
const MEHR_IMPORT: &str = "import Grammatik.Zielsatz.Akzeptiert\nimport Grammatik.Zielsatz.Beweis\n";

/// Export the checked unit as a Lean file with the user's obligations
/// stated, or refuse it by name exactly where `lean-g` refuses it.
pub fn export(source_name: &str, tree: &Programm) -> Result<String, Refusal> {
    let ns = format!("{}_oblig", namespace_of(source_name));
    let text = export_ns(source_name, tree, &ns)?;
    // Name the real command: the body below is the lean-g export, the rest
    // is this subcommand's.
    let lean_zeile =
        format!("-- GENERATED by `gabbro lean-g {source_name}` -- do not edit.\n");
    let oblig_zeile = format!(
        "-- GENERATED by `gabbro obligations --g {source_name}` \
         (lean-g export plus the stated obligation) -- do not edit.\n"
    );
    let text = text.replacen(lean_zeile.as_str(), oblig_zeile.as_str(), 1);
    // The anchor is written unconditionally by the lean-g export above.
    let anchor = "import Grammatik.SperreSem\n";
    let mut text = text.replacen(anchor, &format!("{anchor}{MEHR_IMPORT}"), 1);
    let schluss = format!("end {ns}\n\nend Gabbro.Grammatik\n");
    let rumpf = text
        .strip_suffix(schluss.as_str())
        .expect("lean-g export ends its namespaces")
        .to_string();
    text = rumpf;
    text.push_str(&abschnitt());
    text.push_str(&schluss);
    Ok(text)
}

/// The appended obligation section, inside the program's namespace.
fn abschnitt() -> String {
    let mut out = String::new();
    out.push_str("-- THE USER'S OBLIGATION (stated, not discharged).\n");
    out.push_str("--\n");
    out.push_str("-- `NutzerPflicht gE`: the bodies' logic (`LogikPflicht` -- per function\n");
    out.push_str("-- and at EVERY `forever` budget the body triple with caller duty and no\n");
    out.push_str("-- `logik` outcome, owed invariants at value AND reason exits) and the\n");
    out.push_str("-- start obligation (`StartPflicht` -- every lock invariant at `gE.sp0`,\n");
    out.push_str("-- every declared start's `requires` there with its declared arguments).\n");
    out.push_str("-- A `def` with no proof: the proof is the user's job. Stated through the\n");
    out.push_str("-- IMPORTED definition `NutzerPflicht`; its body is never copied here.\n");
    out.push_str("def nutzerPflicht : Prop := Zielsatz.NutzerPflicht gE\n\n");
    out.push_str("-- The member lists are complete (the `Aufzaehlung`s the goal theorem\n");
    out.push_str("-- quantifies over), decided here so the closing theorem below needs no\n");
    out.push_str("-- program fact beyond the user's obligation.\n");
    out.push_str("theorem gFs_voll : ∀ g : gD.Fn, g ∈ gFs := by\n  intro g\n  cases g <;> decide\n\n");
    out.push_str("theorem gLs_voll : ∀ L : gD.Lock, L ∈ gLs := by\n  intro L\n  cases L <;> decide\n\n");
    out.push_str("-- Carriers are tables or globals; the export declares no global\n");
    out.push_str("-- (`Glob := Empty`), so the right arm closes by cases. `simp [gCs]`\n");
    out.push_str("-- and not `decide`: `DecidableEq (gD.Tab ⊕ gD.Glob)` does not unfold\n");
    out.push_str("-- the `gD` declaration during instance search (measured on 104/108:\n");
    out.push_str("-- `failed to synthesize Decidable (Sum.inl … ∈ gCs)`), while `simp`\n");
    out.push_str("-- rewrites membership over the literal list to constructor equalities.\n");
    out.push_str("theorem gCs_voll : ∀ c : gD.Tab ⊕ gD.Glob, c ∈ gCs := by\n  intro c\n");
    out.push_str("  cases c with\n  | inl t => cases t <;> simp [gCs]\n  | inr g => cases g <;> simp [gCs]\n\n");
    out.push_str("-- The checker premise, discharged here: the concrete checker of the\n");
    out.push_str("-- goal theorem (`akzeptiert_pruefer`) accepts this program on these\n");
    out.push_str("-- lists. Where it does not, this `decide` fails -- loudly, not wrongly.\n");
    out.push_str("theorem gCheck : akzeptiert_pruefer.akzeptiert gE gFs gLs gCs = true := by decide\n\n");
    out.push_str("-- THE CLOSING THEOREM: the conclusion of `GabbroZiel` for this program,\n");
    out.push_str("-- derived from `gabbro_ziel`. The checker premise travels discharged\n");
    out.push_str("-- (`gCheck`); the user's obligation stays open as a hypothesis -- that\n");
    out.push_str("-- is the point. Apply it once `nutzerPflicht` is proved.\n");
    out.push_str("theorem gP_gabbro (hN : Zielsatz.NutzerPflicht gE) (O : Orakel gD)\n");
    out.push_str("    (hH : Zielsatz.HardwareAnnahmen O gE.Q) (passes : Nat)\n");
    out.push_str("    (sp : Speicher gD.mitRuhe)\n");
    out.push_str("    (init : Faden → Σ f : gD.mitRuhe.Fn, Env gD.mitRuhe (gD.mitRuhe.params f))\n");
    out.push_str("    (hL : Zielsatz.Laufzeit gE sp init) (M : RufMaschineG gD.mitRuhe)\n");
    out.push_str("    (hr : RufErreichbarG gE.P.mitRuhe O.mitRuhe passes (RufStartG gE.P.mitRuhe sp init) M) :\n");
    out.push_str("    Zielsatz.Ziel gE.P.mitRuhe gE.S.mitRuhe O.mitRuhe passes (RufStartG gE.P.mitRuhe sp init) M :=\n");
    out.push_str("  Zielsatz.gabbro_ziel akzeptiert_pruefer gD gE ⟨gFs, gFs_voll⟩ ⟨gLs, gLs_voll⟩ ⟨gCs, gCs_voll⟩\n");
    out.push_str("    gCheck hN O hH passes sp init hL M hr\n");
    out
}
