//! **The stated obligation over a G program term (`gabbro obligations --g`).**
//!
//! The export runs `lean_g::export` and appends the goal theorem's user
//! duties plus the closing theorem. What stands here pins that: the 104
//! program states `NutzerPflicht gE` (never discharged here), the three
//! decided member-list premises, the decided checker premise and a
//! sorry-free closing theorem derived from `gabbro_ziel` under a derived
//! namespace -- and every form `lean-g` refuses is refused here with the
//! same `LG` code, since the refusal travels untouched.

use gabbro_check::lean_g::Refusal;
use gabbro_check::obligations_g::export;

fn tree(quelle: &str) -> gabbro_syntax::ast::Programm {
    let (baum, _) = gabbro_syntax::lies("obligations_g", quelle);
    baum
}

fn beispiele(name: &str) -> String {
    let pfad = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../beispiele").join(name);
    std::fs::read_to_string(&pfad).expect("example readable")
}

fn export_file(name: &str) -> String {
    let q = beispiele(name);
    let (baum, _) = gabbro_syntax::lies(name, &q);
    export(name, &baum).expect("example must export")
}

/// **104 states the goal's user duty, not per-function copies**: the one
/// `NutzerPflicht gE` definition (stated through the import, body never
/// copied), the three decided member lists, the decided checker premise
/// and the closing theorem from `gabbro_ziel` -- under `<base>_oblig`,
/// sorry-free.
#[test]
fn obligations_104_states_the_user_duty() {
    let text = export_file("104-referenz.gab");
    for teil in [
        "GENERATED by `gabbro obligations --g 104-referenz.gab`",
        "namespace G104_referenz_oblig",
        "import Grammatik.Zielsatz.Akzeptiert",
        "import Grammatik.Zielsatz.Beweis",
        "def gE : Zielsatz.Einheit gD where",
        "def nutzerPflicht : Prop := Zielsatz.NutzerPflicht gE",
        "theorem gFs_voll : ∀ g : gD.Fn, g ∈ gFs := by",
        "theorem gLs_voll : ∀ L : gD.Lock, L ∈ gLs := by",
        "theorem gCs_voll : ∀ c : gD.Tab ⊕ gD.Glob, c ∈ gCs := by",
        "theorem gCheck : akzeptiert_pruefer.akzeptiert gE gFs gLs gCs = true := by decide",
        "theorem gP_gabbro",
        "Zielsatz.gabbro_ziel akzeptiert_pruefer gD gE",
        "Ziel gE.P.mitRuhe gE.S.mitRuhe O.mitRuhe passes",
        "(hN : Zielsatz.NutzerPflicht gE)",
    ] {
        assert!(text.contains(teil), "104 obligations must contain {teil:?}");
    }
    assert!(
        !text.contains("sorry"),
        "the stated obligation carries no proof, not even a hole"
    );
    assert!(
        !text.contains("_pflicht : Prop"),
        "no per-function duty may be stated: the duty is NutzerPflicht gE"
    );
}

/// **108 carries its starts into the duty**: the declared starts travel in
/// `gE.starts`, so the closing theorem is about the two-thread program.
#[test]
fn obligations_108_starts_travel() {
    let text = export_file("108-disjoint-start-locks.gab");
    for teil in [
        "namespace G108_disjoint_start_locks_oblig",
        "starts := [⟨g_read_a, .nil⟩, ⟨g_read_c, .nil⟩]",
        "def nutzerPflicht : Prop := Zielsatz.NutzerPflicht gE",
        "theorem gP_gabbro",
    ] {
        assert!(text.contains(teil), "108 obligations must contain {teil:?}");
    }
}

/// **The lean-g body travels underneath**: the declaration, the program,
/// the member lists and the lock-invariant family are the export's, not a
/// copy.
#[test]
fn obligations_104_keeps_the_export() {
    let text = export_file("104-referenz.gab");
    for teil in [
        "def gP : Programm gD where",
        "def gFs : List gD.Fn",
        "def gLs : List gD.Lock",
        "def gCs : List (gD.Tab ⊕ gD.Glob)",
        "def gS : SperrInv gD where",
        "def gSp0 : Speicher gD",
        "example : programmImFragmentG gP gFs = true := by decide",
    ] {
        assert!(text.contains(teil), "104 obligations must contain {teil:?}");
    }
}

const KOPF: &str = "module test::obligg {\n\
    table T count 4 { slot { v : u32, } }\n\
    lock L protects { T } rank 0 held <= 100 ops;\n";

fn einheit(extra: &str) -> String {
    format!("{KOPF}{extra}}}\n")
}

/// **One function, one duty over the unit**: the obligation is stated over
/// `gE` and the closing theorem bridges it -- no per-function arms.
#[test]
fn obligations_single_function() {
    let text = export("obligg", &tree(&einheit(
        "impl fn f() -> u32 effects { pure } costs <= 1 ops { return 1; }\n",
    )))
    .expect("must export");
    for teil in [
        "namespace obligg_oblig",
        "def gE : Zielsatz.Einheit gD where",
        "def nutzerPflicht : Prop := Zielsatz.NutzerPflicht gE",
        "theorem gFs_voll",
        "theorem gCheck : akzeptiert_pruefer.akzeptiert gE gFs gLs gCs = true := by decide",
        "theorem gP_gabbro",
        "Zielsatz.gabbro_ziel akzeptiert_pruefer gD gE",
    ] {
        assert!(text.contains(teil), "single-function obligations must contain {teil:?}");
    }
}

/// **LG001 travels**: an `extern fn` has no G form, so there is no program
/// to state duties over.
#[test]
fn refuses_extern_fn_like_lean_g() {
    let w: Refusal = export(
        "obligg",
        &tree(&einheit(
            "extern fn e(x : u32) -> u32 effects { pure } costs <= 1 ops;\n",
        )),
    )
    .expect_err("must refuse");
    assert_eq!(w.code, "LG001", "{w}");
}

/// **LG004 travels**: `if` has no `Stmt` form here.
#[test]
fn refuses_wenn_like_lean_g() {
    let w: Refusal = export(
        "obligg",
        &tree(&einheit(
            "impl fn f(x : u32) -> u32 effects { pure } costs <= 4 ops\n\
            {\n    if x == 1 { return 1; } else { return 0; }\n}\n",
        )),
    )
    .expect_err("must refuse");
    assert_eq!(w.code, "LG004", "{w}");
}

/// **LG005 travels**: a call nobody declares names nothing.
#[test]
fn refuses_unknown_call_like_lean_g() {
    let w: Refusal = export(
        "obligg",
        &tree(&einheit(
            "impl fn f() effects { pure } costs <= 4 ops\n{\n    nope();\n}\n",
        )),
    )
    .expect_err("must refuse");
    assert_eq!(w.code, "LG005", "{w}");
}

// ---------------------------------------------------------------------------------------
// O12: the release obligation in the obligation channel.
// ---------------------------------------------------------------------------------------

/// The O12 corpus shape (the `beispiele/124` lock and callee, minimal):
/// a lock with an invariant over two slot cells, a callee, and a locked
/// section calling it. The callee's promise is the parameter.
const O12_KOPF: &str = "module test::o12 {\n\
    type Stand = u32 in 0 .. 100;\n\
    table konto count 2 { slot { stand : Stand, } }\n\
    lock L protects { konto } rank 0 held <= 100 ops\n\
        invariant konto.slots[0].stand == konto.slots[1].stand;\n";

fn o12_einheit(ensures_setze: &str) -> String {
    format!(
        "{O12_KOPF}\
        impl fn setze(x : Stand)\n\
        \x20   requires Held(L), konto.slots[0].stand == konto.slots[1].stand\n\
        \x20   ensures  {ensures_setze}\n\
        \x20   effects  {{ reads konto.slots, writes konto.slots, locks L }}\n\
        \x20   costs    <= 64 ops\n\
        {{\n\
        \x20   konto.slots[0].stand = x;\n\
        \x20   konto.slots[1].stand = x;\n\
        }}\n\
        impl fn haupt()\n\
        \x20   effects  {{ reads konto.slots, writes konto.slots, locks L }}\n\
        \x20   costs    <= 512 ops\n\
        {{\n\
        \x20   locks L {{\n\
        \x20       setze(30);\n\
        \x20   }}\n\
        }}\n\
        concurrent {{ haupt }};\n\
        }}\n"
    )
}

fn o12_export(ensures_setze: &str) -> String {
    let quelle = o12_einheit(ensures_setze);
    let (baum, mut absagen) = gabbro_syntax::lies("o12", &quelle);
    gabbro_check::pruefe(&baum, &mut absagen);
    assert!(
        absagen.fehler_zahl() == 0,
        "the O12 snippet stays checker-clean: {}",
        absagen.zeige(&quelle)
    );
    export("o12", &baum).expect("the O12 snippet must export")
}

/// **O12, the failing half: a callee promising only `konto[0] == x` leaves
/// the release obligation UNPROVED** -- naming the locked section (`haupt`
/// locking `L`), the callee promise (`setze`), and the unproved release
/// goal (`konto.slots[1].stand`). No new refusal: the export succeeds, so
/// the failure is stated in the obligation channel, never diagnosed.
#[test]
fn o12_schwaches_ensures_meldet_unbewiesene_freigabe() {
    let text = o12_export("konto.slots[0].stand == x");
    for teil in [
        "RELEASE OBLIGATIONS",
        "haupt",
        "`L`",
        "setze promises {konto.slots[0].stand}",
        "RELEASE UNPROVED",
        "no callee promises konto.slots[1].stand",
    ] {
        assert!(text.contains(teil), "the failing release row must contain {teil:?}");
    }
}

/// **O12, the fixed half: a callee promising both slots HOLDS** -- the
/// shape `beispiele/124` carries since the O12 corpus fix.
#[test]
fn o12_starkes_ensures_haelt_die_freigabe() {
    let text = o12_export(
        "konto.slots[0].stand == konto.slots[1].stand && konto.slots[0].stand == x",
    );
    assert!(
        text.contains("RELEASE HOLDS (syntactic)"),
        "the fixed release row must hold"
    );
    assert!(
        !text.contains("RELEASE UNPROVED:"),
        "no release row may fail once both slots are promised"
    );
}

/// **O12 on the corpus file itself: `124` holds at every release** -- the
/// strengthened `setze` contract re-establishes the lock invariant from the
/// callee's promise, at both locked sections.
#[test]
fn o12_beispiel_124_haelt_an_jeder_freigabe() {
    let text = export_file("124-two-threads-private.gab");
    assert!(
        text.contains("RELEASE HOLDS (syntactic)"),
        "124 must hold at its releases since the O12 fix"
    );
    assert!(
        !text.contains("RELEASE UNPROVED:"),
        "124 must have no failing release row since the O12 fix"
    );
    for teil in ["hauptA", "hauptB", "`L`", "setze promises"] {
        assert!(text.contains(teil), "124 release rows must name {teil:?}");
    }
}
