//! **The stated obligation over a G program term (`gabbro obligations --g`).**
//!
//! The export runs `lean_g::export` and appends the goal theorem's user
//! duties plus the closing theorem. What stands here pins that: the 104
//! program states `NutzerPflicht gE` (never discharged here), the three
//! decided member-list premises, the decided checker premise and a
//! sorry-free closing theorem derived from `gabbro_ziel` under a derived
//! namespace -- and every form `lean-g` refuses is refused here with the
//! same `LG` code, since the refusal travels untouched.

use gabbro_check::lean_g::Refusal;
use gabbro_check::obligations_g::export;

fn tree(quelle: &str) -> gabbro_syntax::ast::Programm {
    let (baum, _) = gabbro_syntax::lies("obligations_g", quelle);
    baum
}

fn beispiele(name: &str) -> String {
    let pfad = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../beispiele").join(name);
    std::fs::read_to_string(&pfad).expect("example readable")
}

fn export_file(name: &str) -> String {
    let q = beispiele(name);
    let (baum, _) = gabbro_syntax::lies(name, &q);
    export(name, &baum).expect("example must export")
}

/// **104 states the goal's user duty, not per-function copies**: the one
/// `NutzerPflicht gE` definition (stated through the import, body never
/// copied), the three decided member lists, the decided checker premise
/// and the closing theorem from `gabbro_ziel` -- under `<base>_oblig`,
/// sorry-free.
#[test]
fn obligations_104_states_the_user_duty() {
    let text = export_file("104-referenz.gab");
    for teil in [
        "GENERATED by `gabbro obligations --g 104-referenz.gab`",
        "namespace G104_referenz_oblig",
        "import Grammatik.Zielsatz.Akzeptiert",
        "import Grammatik.Zielsatz.Beweis",
        "def gE : Zielsatz.Einheit gD where",
        "def nutzerPflicht : Prop := Zielsatz.NutzerPflicht gE",
        "theorem gFs_voll : ∀ g : gD.Fn, g ∈ gFs := by",
        "theorem gLs_voll : ∀ L : gD.Lock, L ∈ gLs := by",
        "theorem gCs_voll : ∀ c : gD.Tab ⊕ gD.Glob, c ∈ gCs := by",
        "theorem gCheck : akzeptiert_pruefer.akzeptiert gE gFs gLs gCs = true := by decide",
        "theorem gP_gabbro",
        "Zielsatz.gabbro_ziel akzeptiert_pruefer gD gE",
        "Ziel gE.P.mitRuhe gE.S.mitRuhe O.mitRuhe passes",
        "(hN : Zielsatz.NutzerPflicht gE)",
    ] {
        assert!(text.contains(teil), "104 obligations must contain {teil:?}");
    }
    assert!(
        !text.contains("sorry"),
        "the stated obligation carries no proof, not even a hole"
    );
    assert!(
        !text.contains("_pflicht : Prop"),
        "no per-function duty may be stated: the duty is NutzerPflicht gE"
    );
}

/// **108 carries its starts into the duty**: the declared starts travel in
/// `gE.starts`, so the closing theorem is about the two-thread program.
#[test]
fn obligations_108_starts_travel() {
    let text = export_file("108-disjoint-start-locks.gab");
    for teil in [
        "namespace G108_disjoint_start_locks_oblig",
        "starts := [⟨g_read_a, .nil⟩, ⟨g_read_c, .nil⟩]",
        "def nutzerPflicht : Prop := Zielsatz.NutzerPflicht gE",
        "theorem gP_gabbro",
    ] {
        assert!(text.contains(teil), "108 obligations must contain {teil:?}");
    }
}

/// **The lean-g body travels underneath**: the declaration, the program,
/// the member lists and the lock-invariant family are the export's, not a
/// copy.
#[test]
fn obligations_104_keeps_the_export() {
    let text = export_file("104-referenz.gab");
    for teil in [
        "def gP : Programm gD where",
        "def gFs : List gD.Fn",
        "def gLs : List gD.Lock",
        "def gCs : List (gD.Tab ⊕ gD.Glob)",
        "def gS : SperrInv gD where",
        "def gSp0 : Speicher gD",
        "example : programmImFragmentG gP gFs = true := by decide",
    ] {
        assert!(text.contains(teil), "104 obligations must contain {teil:?}");
    }
}

const KOPF: &str = "module test::obligg {\n\
    table T count 4 { slot { v : u32, } }\n\
    lock L protects { T } rank 0 held <= 100 ops;\n";

fn einheit(extra: &str) -> String {
    format!("{KOPF}{extra}}}\n")
}

/// **One function, one duty over the unit**: the obligation is stated over
/// `gE` and the closing theorem bridges it -- no per-function arms.
#[test]
fn obligations_single_function() {
    let text = export("obligg", &tree(&einheit(
        "impl fn f() -> u32 effects { pure } costs <= 1 ops { return 1; }\n",
    )))
    .expect("must export");
    for teil in [
        "namespace obligg_oblig",
        "def gE : Zielsatz.Einheit gD where",
        "def nutzerPflicht : Prop := Zielsatz.NutzerPflicht gE",
        "theorem gFs_voll",
        "theorem gCheck : akzeptiert_pruefer.akzeptiert gE gFs gLs gCs = true := by decide",
        "theorem gP_gabbro",
        "Zielsatz.gabbro_ziel akzeptiert_pruefer gD gE",
    ] {
        assert!(text.contains(teil), "single-function obligations must contain {teil:?}");
    }
}

/// **LG001 travels**: an `extern fn` has no G form, so there is no program
/// to state duties over.
#[test]
fn refuses_extern_fn_like_lean_g() {
    let w: Refusal = export(
        "obligg",
        &tree(&einheit(
            "extern fn e(x : u32) -> u32 effects { pure } costs <= 1 ops;\n",
        )),
    )
    .expect_err("must refuse");
    assert_eq!(w.code, "LG001", "{w}");
}

/// **LG004 travels**: `if` has no `Stmt` form here.
#[test]
fn refuses_wenn_like_lean_g() {
    let w: Refusal = export(
        "obligg",
        &tree(&einheit(
            "impl fn f(x : u32) -> u32 effects { pure } costs <= 4 ops\n\
            {\n    if x == 1 { return 1; } else { return 0; }\n}\n",
        )),
    )
    .expect_err("must refuse");
    assert_eq!(w.code, "LG004", "{w}");
}

/// **LG005 travels**: a call nobody declares names nothing.
#[test]
fn refuses_unknown_call_like_lean_g() {
    let w: Refusal = export(
        "obligg",
        &tree(&einheit(
            "impl fn f() effects { pure } costs <= 4 ops\n{\n    nope();\n}\n",
        )),
    )
    .expect_err("must refuse");
    assert_eq!(w.code, "LG005", "{w}");
}
