//! **The stated obligation over a G program term (`gabbro obligations --g`).**
//!
//! The export runs `lean_g::export` and appends the flagship's per-function
//! duties plus the closing theorem. What stands here pins that: the 104
//! program carries both duties per function, the families, the boot duty,
//! the decided premises and a sorry-free closing theorem under a derived
//! namespace -- and every form `lean-g` refuses is refused here with the
//! same `LG` code, since the refusal travels untouched.

use gabbro_check::lean_g::Refusal;
use gabbro_check::obligations_g::export;

fn tree(quelle: &str) -> gabbro_syntax::ast::Programm {
    let (baum, _) = gabbro_syntax::lies("obligations_g", quelle);
    baum
}

fn beispiele(name: &str) -> String {
    let pfad = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../beispiele").join(name);
    std::fs::read_to_string(&pfad).expect("example readable")
}

fn export_file(name: &str) -> String {
    let q = beispiele(name);
    let (baum, _) = gabbro_syntax::lies(name, &q);
    export(name, &baum).expect("example must export")
}

/// **104 states both duties per function**: the `KoerperGutS` duty and the
/// `InvGutS` duty, the two families, the boot duty, the decided premises
/// and the closing theorem -- under `<base>_oblig`, sorry-free.
#[test]
fn obligations_104_states_both_duties() {
    let text = export_file("104-referenz.gab");
    for teil in [
        "GENERATED by `gabbro obligations --g 104-referenz.gab`",
        "namespace G104_referenz_oblig",
        "import Grammatik.ZielOrtStart",
        "def einzahlen_pflicht : Prop :=",
        "KoerperGutS gP 0 (axWahr gD) gS g_einzahlen",
        "def lies_pflicht : Prop :=",
        "KoerperGutS gP 0 (axWahr gD) gS g_lies",
        "def einzahlen_invPflicht : Prop :=",
        "InvGutS gP 0 (axWahr gD) gS g_einzahlen",
        "def lies_invPflicht : Prop :=",
        "InvGutS gP 0 (axWahr gD) gS g_lies",
        "def pflicht : GFn",
        "| .einzahlen => einzahlen_pflicht",
        "def pflichtInv : GFn",
        "| .lies => lies_invPflicht",
        "def startPflicht (sp : Speicher gD) : Prop :=",
        "theorem gP_voll : ∀ g : gD.Fn, g ∈ gFs := by",
        "theorem gP_fragment : programmImFragmentG gP gFs = true := by decide",
        "theorem gP_fussS : fussSperreB gP gS gFs = true := by decide",
        "theorem gP_ziel",
        "ziel_ort_sperre_ende",
        "· exact hK .einzahlen",
        "· exact hI .lies",
    ] {
        assert!(text.contains(teil), "104 obligations must contain {teil:?}");
    }
    assert!(
        !text.contains("sorry"),
        "the stated obligation carries no proof, not even a hole"
    );
}

/// **The lean-g body travels underneath**: the declaration, the program and
/// the lock-invariant family are the export's, not a copy.
#[test]
fn obligations_104_keeps_the_export() {
    let text = export_file("104-referenz.gab");
    for teil in [
        "def gP : Programm gD where",
        "def gFs : List gD.Fn",
        "def gS : SperrInv gD where",
        "example : programmImFragmentG gP gFs = true := by decide",
    ] {
        assert!(text.contains(teil), "104 obligations must contain {teil:?}");
    }
}

const KOPF: &str = "module test::obligg {\n\
    table T count 4 { slot { v : u32, } }\n\
    lock L protects { T } rank 0 held <= 100 ops;\n";

fn einheit(extra: &str) -> String {
    format!("{KOPF}{extra}}}\n")
}

/// **One function, one duty**: the families have one arm and the closing
/// theorem bridges it with one bullet.
#[test]
fn obligations_single_function() {
    let text = export("obligg", &tree(&einheit(
        "impl fn f() -> u32 effects { pure } costs <= 1 ops { return 1; }\n",
    )))
    .expect("must export");
    for teil in [
        "namespace obligg_oblig",
        "def f_pflicht : Prop :=",
        "def f_invPflicht : Prop :=",
        "def pflicht : GFn",
        "| .f => f_pflicht",
        "theorem gP_ziel",
        "· exact hK .f",
    ] {
        assert!(text.contains(teil), "single-function obligations must contain {teil:?}");
    }
}

/// **LG001 travels**: an `extern fn` has no G form, so there is no program
/// to state duties over.
#[test]
fn refuses_extern_fn_like_lean_g() {
    let w: Refusal = export(
        "obligg",
        &tree(&einheit(
            "extern fn e(x : u32) -> u32 effects { pure } costs <= 1 ops;\n",
        )),
    )
    .expect_err("must refuse");
    assert_eq!(w.code, "LG001", "{w}");
}

/// **LG004 travels**: `if` has no `Stmt` form here.
#[test]
fn refuses_wenn_like_lean_g() {
    let w: Refusal = export(
        "obligg",
        &tree(&einheit(
            "impl fn f(x : u32) -> u32 effects { pure } costs <= 4 ops\n\
            {\n    if x == 1 { return 1; } else { return 0; }\n}\n",
        )),
    )
    .expect_err("must refuse");
    assert_eq!(w.code, "LG004", "{w}");
}

/// **LG005 travels**: a call nobody declares names nothing.
#[test]
fn refuses_unknown_call_like_lean_g() {
    let w: Refusal = export(
        "obligg",
        &tree(&einheit(
            "impl fn f() effects { pure } costs <= 4 ops\n{\n    nope();\n}\n",
        )),
    )
    .expect_err("must refuse");
    assert_eq!(w.code, "LG005", "{w}");
}
