//! **Every accepted corpus program is CERTIFIED in Lean or NAMED -- nothing falls between.**
//!
//! Opus agent C, 2026-09-26 (`messung/OPUS-C-TRAGWEITE.md`). Simon's sentence: *"When Lean is
//! green, Gabbro carries everything except the things named in the Spec."* Before this test a
//! program the checker accepted and the exporter refused (`LG001`-`LG007`) was judged by
//! nothing in Lean, and nothing turned red: the refusal was a printed line.
//!
//! What this test holds, for every `.gab` file under `beispiele/` (top level and `gift/`) that
//! the checker accepts -- the same path `gabbro lean-g` takes (`lies`, `pruefe`, no error):
//!
//! * the exporter carries it (`obligations_g::export` answers `Ok`) => a committed file whose
//!   line 1 is the generator's own marker exists under `grammatik/Grammatik/` and IS that
//!   output, byte for byte. The file decides the checker premise (`gCheck … := by decide`) and
//!   instantiates the goal theorem (`gP_gabbro`), so `lake build` turns red if the Lean Bool
//!   refuses the exported unit. New certificates live in `grammatik/Grammatik/Zertifikat/`;
//!   `GenOblig104/108.lean` are the two older ones and count as they are.
//! * the exporter refuses it => it stands in `Zertifikat/REGISTER.txt` as `UNCERTIFIED` with
//!   the code and message of the refusal.
//!
//! and in the other direction: no certificate file in `Zertifikat/` without an accepted,
//! exported program; the umbrella `Grammatik/Zertifikate.lean` imports every certificate, and
//! `Grammatik.lean` imports the umbrella. `REGISTER.txt` is THE ONE LIST `Spec.lean` cites.
//!
//! `GABBRO_ZERTIFIKATE=schreiben cargo test --test zertifikate` rewrites the generated files
//! (certificates in `Zertifikat/`, the umbrella, the register) instead of comparing them.

use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};

fn wurzel() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("..").join("..")
}

/// Every `.gab` under `beispiele/` and `beispiele/gift/`, as the relative path the generator
/// is called with (`beispiele/…`), sorted.
fn programme(w: &Path) -> Vec<String> {
    let mut out = Vec::new();
    for dir in ["beispiele", "beispiele/gift"] {
        let Ok(rd) = std::fs::read_dir(w.join(dir)) else { continue };
        for e in rd.flatten() {
            let name = e.file_name().to_string_lossy().to_string();
            if name.ends_with(".gab") && e.path().is_file() {
                out.push(format!("{dir}/{name}"));
            }
        }
    }
    out.sort();
    out
}

fn marker(rel: &str) -> String {
    format!(
        "-- GENERATED by `gabbro obligations --g {rel}` (lean-g export plus the stated \
         obligation) -- do not edit."
    )
}

/// Every committed Lean file under `grammatik/Grammatik/`, recursively.
fn lean_dateien(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(rd) = std::fs::read_dir(dir) else { return };
    for e in rd.flatten() {
        let p = e.path();
        if p.is_dir() {
            lean_dateien(&p, out);
        } else if p.extension().is_some_and(|x| x == "lean") {
            out.push(p);
        }
    }
}

/// The Lean module name of a file under `grammatik/`.
fn modul(grammatik: &Path, p: &Path) -> String {
    let rel = p.strip_prefix(grammatik).expect("file under grammatik/");
    let s = rel.with_extension("").to_string_lossy().to_string();
    s.replace('/', ".")
}

fn eine_zeile(s: &str) -> String {
    s.split_whitespace().collect::<Vec<_>>().join(" ")
}

/// The chain instances of the tree: `CHAIN-INSTANCE <program> <name>` markers (the notation
/// `zaehle-kette.py` reads), program -> instance names.
fn ketten(dateien: &[PathBuf]) -> BTreeMap<String, BTreeSet<String>> {
    let mut m: BTreeMap<String, BTreeSet<String>> = BTreeMap::new();
    for p in dateien {
        let Ok(t) = std::fs::read_to_string(p) else { continue };
        for z in t.lines() {
            let z = z.trim();
            if let Some(rest) = z.strip_prefix("CHAIN-INSTANCE ") {
                let mut it = rest.split_whitespace();
                if let (Some(prog), Some(name)) = (it.next(), it.next()) {
                    m.entry(prog.to_string()).or_default().insert(name.to_string());
                }
            }
        }
    }
    m
}

const REGISTER_KOPF: &str = "\
# THE ONE LIST of the corpus programs the checker accepts, and what a green `lake build`
# says about each (generated by `crates/gabbro-check/tests/zertifikate.rs`; rewrite it with
# `GABBRO_ZERTIFIKATE=schreiben cargo test --test zertifikate` -- do not edit by hand).
# Cited by `grammatik/Grammatik/Zielsatz/Spec.lean` (\"WHAT A GREEN BUILD COVERS\").
#
# Population: every `.gab` under `beispiele/` and `beispiele/gift/` with no checker error.
#
# CERTIFIED <program> <module> <chain>
#   The exporter carries the program to an `Einheit` (`gE`), and <module> -- the byte-exact
#   output of `gabbro obligations --g <program>`, in the build -- decides the checker premise
#   of the goal theorem on it (`gCheck`, `by decide`) and instantiates the goal theorem
#   (`gP_gabbro`: `Ziel` on every run of machine G, the user's duty `NutzerPflicht gE` as the
#   hypothesis). What the export drops is named in the module's own header (\"NO FORM in G\").
#   <chain> is `chain-instance=<name>` when a Lean instance of the generic closing theorem
#   `schlusssatz` exists for the program (source -> model -> emitted C; `zaehle-kette.py
#   --lean` measures whether it is CLOSED), `chain=none` otherwise: then \"machine G is the
#   meaning of the emitted C\" is an assumption of the reading for this program.
# UNCERTIFIED <program> <code> <message>
#   The exporter refuses the program (its FIRST refusal, code and message): no `Einheit`, so
#   no Lean judgement at all. A green build says NOTHING about this program; the goal theorem
#   reaches it only by a hand-written term (`Korpus07.lean`, `Korpus125.lean`).
";

const UMBRELLA_KOPF: &str = "\
/-
  File:    Grammatik/Zertifikate.lean -- GENERATED by `crates/gabbro-check/tests/zertifikate.rs`
           (do not edit; `GABBRO_ZERTIFIKATE=schreiben cargo test --test zertifikate`).
  Content: one import per CERTIFIED corpus program of `Zertifikat/REGISTER.txt`. Each imported
           module is the byte-exact output of `gabbro obligations --g <program>`: the exported
           unit `gE`, the checker premise decided (`gCheck`, `by decide`) and the goal theorem
           instantiated (`gP_gabbro`). Importing them here puts every one into `lake build`, so
           an exported program the Lean Bool `Akzeptiert` refuses turns the build RED.
-/
";

#[test]
fn jedes_angenommene_programm_ist_zertifiziert_oder_benannt() {
    let w = wurzel();
    let grammatik = w.join("grammatik");
    let gdir = grammatik.join("Grammatik");
    let zdir = gdir.join("Zertifikat");
    let schreiben = std::env::var("GABBRO_ZERTIFIKATE").is_ok_and(|v| v == "schreiben");

    let mut dateien = Vec::new();
    lean_dateien(&gdir, &mut dateien);
    dateien.sort();
    // program -> committed certificate file (by the generator's own line-1 marker).
    let mut vorhanden: BTreeMap<String, PathBuf> = BTreeMap::new();
    let prefix = "-- GENERATED by `gabbro obligations --g ";
    for p in &dateien {
        let Ok(t) = std::fs::read_to_string(p) else { continue };
        let z1 = t.lines().next().unwrap_or("");
        if let Some(rest) = z1.strip_prefix(prefix) {
            let prog = rest.split('`').next().unwrap_or("").to_string();
            assert!(
                vorhanden.insert(prog.clone(), p.clone()).is_none(),
                "two committed certificates for {prog}"
            );
        }
    }
    let ketten = ketten(&dateien);

    let mut befunde: Vec<String> = Vec::new();
    let mut register = String::from(REGISTER_KOPF);
    let mut module: Vec<String> = Vec::new();
    let mut namensraeume: BTreeMap<String, String> = BTreeMap::new();
    let mut erwartet_in_zdir: BTreeSet<PathBuf> = BTreeSet::new();
    let (mut n_ang, mut n_zert, mut n_nicht) = (0usize, 0usize, 0usize);

    for rel in programme(&w) {
        let quelle = std::fs::read_to_string(w.join(&rel)).expect("readable");
        let (baum, mut absagen) = gabbro_syntax::lies(&rel, &quelle);
        gabbro_check::pruefe(&baum, &mut absagen);
        if absagen.fehler_zahl() > 0 {
            continue; // not accepted: no claim, nothing to certify
        }
        n_ang += 1;
        match gabbro_check::obligations_g::export(&rel, &baum) {
            Ok(text) => {
                n_zert += 1;
                let ns = gabbro_check::lean_g::namespace_of(&rel);
                if let Some(anderes) = namensraeume.insert(ns.clone(), rel.clone()) {
                    befunde.push(format!("{rel} and {anderes} share the namespace {ns}"));
                }
                let ziel = vorhanden
                    .get(&rel)
                    .cloned()
                    .unwrap_or_else(|| zdir.join(format!("{ns}.lean")));
                if ziel.starts_with(&zdir) {
                    erwartet_in_zdir.insert(ziel.clone());
                }
                let ist = std::fs::read_to_string(&ziel).ok();
                if ist.as_deref() != Some(text.as_str()) {
                    if schreiben && ziel.starts_with(&zdir) {
                        std::fs::create_dir_all(&zdir).expect("mkdir");
                        std::fs::write(&ziel, &text).expect("write certificate");
                    } else {
                        befunde.push(format!(
                            "{rel}: the certificate {} is {} -- the exporter's output differs",
                            ziel.display(),
                            if ist.is_some() { "STALE" } else { "MISSING" }
                        ));
                    }
                }
                assert!(text.starts_with(&marker(&rel)), "generator marker moved");
                let m = modul(&grammatik, &ziel);
                let kette = match ketten.get(&rel) {
                    Some(n) => format!(
                        "chain-instance={}",
                        n.iter().cloned().collect::<Vec<_>>().join(",")
                    ),
                    None => "chain=none".to_string(),
                };
                register.push_str(&format!("CERTIFIED\t{rel}\t{m}\t{kette}\n"));
                module.push(m);
            }
            Err(r) => {
                n_nicht += 1;
                register.push_str(&format!(
                    "UNCERTIFIED\t{rel}\t{}\t{}\n",
                    r.code,
                    eine_zeile(&r.message)
                ));
            }
        }
    }
    register.push_str(&format!(
        "# TOTAL: {n_ang} accepted, {n_zert} CERTIFIED, {n_nicht} UNCERTIFIED\n"
    ));
    assert_eq!(n_ang, n_zert + n_nicht);
    assert!(n_ang > 100, "the population is not the corpus ({n_ang} accepted)");

    // No certificate in `Zertifikat/` without its accepted, exported program.
    if let Ok(rd) = std::fs::read_dir(&zdir) {
        for e in rd.flatten() {
            let p = e.path();
            if p.extension().is_some_and(|x| x == "lean") && !erwartet_in_zdir.contains(&p) {
                if schreiben {
                    std::fs::remove_file(&p).expect("remove stale certificate");
                } else {
                    befunde.push(format!(
                        "{}: a certificate of no accepted, exported program",
                        p.display()
                    ));
                }
            }
        }
    }

    // The umbrella imports every certificate.
    module.sort();
    let mut umbrella = String::from(UMBRELLA_KOPF);
    for m in &module {
        umbrella.push_str(&format!("import {m}\n"));
    }
    let upfad = gdir.join("Zertifikate.lean");
    let rpfad = zdir.join("REGISTER.txt");
    for (pfad, soll) in [(&upfad, &umbrella), (&rpfad, &register)] {
        if std::fs::read_to_string(pfad).ok().as_deref() != Some(soll.as_str()) {
            if schreiben {
                std::fs::create_dir_all(&zdir).expect("mkdir");
                std::fs::write(pfad, soll).expect("write");
            } else {
                befunde.push(format!("{} is not what the tree says -- regenerate it", pfad.display()));
            }
        }
    }
    let wurzeldatei = std::fs::read_to_string(grammatik.join("Grammatik.lean")).expect("root");
    if !wurzeldatei.lines().any(|z| z.trim() == "import Grammatik.Zertifikate") {
        befunde.push("Grammatik.lean does not import Grammatik.Zertifikate".to_string());
    }

    assert!(
        befunde.is_empty(),
        "{} finding(s) -- an accepted program outside both the certificates and the register, \
         or a generated file out of date (rewrite: GABBRO_ZERTIFIKATE=schreiben cargo test \
         --test zertifikate):\n  {}",
        befunde.len(),
        befunde.join("\n  ")
    );
}
