-- GENERATED by `gabbro obligations --g beispiele/187-bool-statisch.gab` (lean-g export plus the stated obligation) -- do not edit.
-- A mechanical export of the checked unit as a G program term
-- (`Programm gD`, the syntax `RufMaschineG.lean` runs).
--
-- NO FORM in G (accepted and dropped, each named): the module
-- wrapper; named constants (inlined at every use); bare carrier
-- widths (a bare word travels as its full range); pointer address
-- spaces; lock hold budgets;
-- the `reads` effects; `costs`; the `by unvisited`/`by consuming`
-- run form, the `decreases` witness and the `touches` clause of a
-- `traverse` (static annotations, like `costs`); `by ops` on a field
-- (a writer discipline the checker holds); `mut` on a `let`;
-- `pub` and `opaque` (both are unit-boundary rules, and
-- `Deklaration` has no boundary -- `pub` added 2026-09-15 after
-- being dropped here and named nowhere, which is the one thing
-- this ledger exists to prevent; `opaque` the same day, when its
-- alias started to travel as its range);
-- `concurrent` (its members travel as the declared starts
-- `gE.starts`; every start is parameterless, its argument list
-- `.nil`); `entry`/`boot` (the vector, the registers, the steps:
-- NO FORM; only the dispatch root travels, as a declared start
-- where exportable, and a thrown `entry` -- one carrying a `via` path -- as
-- `gP.unterbricht`).
--
-- static 0: ANHALTEN : bool = false
-- fn halte (holds; writes ANHALTEN)
-- fn gehalten (holds; writes)
import Grammatik.Zielsatz.ZielOrt.Geraet.ZielOrtGeraetSem
import Grammatik.Nebenlaeufigkeit.Sperren.SperreSem
import Grammatik.Zielsatz.Kern.Akzeptiert
import Grammatik.Zielsatz.Kern.Beweis
import Grammatik.Zielsatz.Atomar.BeweisAtomar
import Grammatik.Zielsatz.Kern.Spec

namespace Gabbro.Grammatik

namespace G187_bool_statisch_oblig

abbrev GTab := Empty

abbrev GLock := Empty

inductive GGlob where
  | ANHALTEN
  deriving DecidableEq

inductive GFn where
  | halte
  | gehalten
  deriving DecidableEq

def gSig_halte : Signatur GTab GGlob GLock Empty where
  params := []
  erg := none
  gruende := 0
  haelt := []
  boden := none
  schreibt := fun _ => false
  gschreibt := fun _ => true
  konsumiert := []
  produziert := []

def gSig_gehalten : Signatur GTab GGlob GLock Empty where
  params := []
  erg := some (.bool)
  gruende := 0
  haelt := []
  boden := none
  schreibt := fun _ => false
  gschreibt := fun _ => false
  konsumiert := []
  produziert := []

abbrev gD : Deklaration where
  Tab := GTab
  decTab := inferInstance
  count := fun t => nomatch t
  Feld := fun t => nomatch t
  decFeld := fun t => nomatch t
  typ := fun t => nomatch t
  erlaubt := fun _ _ _ _ => false
  tabNr := fun _ => none
  Glob := GGlob
  decGlob := inferInstance
  gtyp := fun | .ANHALTEN => .bool
  nutzlast := fun _ => []
  atomar := fun | .ANHALTEN => false
  geteilt := fun t => nomatch t
  ggeteilt := fun | .ANHALTEN => false
  Lock := GLock
  decLock := inferInstance
  rang := fun L => nomatch L
  maskiert := fun _ => false
  Marke := Empty
  decMarke := inferInstance
  stufen := fun e => nomatch e
  braucht := fun t => nomatch t
  gbraucht := fun | .ANHALTEN => []
  eigner := fun _ => []
  Fn := GFn
  sig := fun | .halte => 0 | .gehalten => 1
  sigNr := fun | 0 => gSig_halte | 1 => gSig_gehalten | _ => gSig_gehalten
  eigner_nie_erzeugt := fun _ _ _ _ h => by simp at h
  Inv := Empty
  traeger := fun e => nomatch e
  invs := []
  Ax := Empty
  aparams := fun e => nomatch e
  aerg := fun e => nomatch e
  aschreibt := fun e => nomatch e
  agschreibt := fun e => nomatch e
  Reg := Empty
  rtyp := fun e => nomatch e
  rklasse := fun e => nomatch e
  spiegel := fun e => nomatch e
  rzusage := fun e => nomatch e
  Annahme := Unit
  a10 := ()
  geteilt_bewacht := fun t => by cases t <;> decide
  invarianten_gehalten := fun _ i => nomatch i
  ggeteilt_bewacht := fun g => by cases g <;> decide

abbrev gCtx_halte : Ctx := []
def g_halte : gD.Fn := GFn.halte
abbrev gCtx_gehalten : Ctx := []
def g_gehalten : gD.Fn := GFn.gehalten

abbrev gL_halte : List (Res gD) := []
abbrev gL_gehalten : List (Res gD) := []

theorem gGDarf_gehalten_ANHALTEN : gdarf gD GGlob.ANHALTEN gL_gehalten := by unfold gdarf; decide
theorem gGDarf_halte_ANHALTEN : gdarf gD GGlob.ANHALTEN gL_halte := by unfold gdarf; decide

def gBody_halte : Endblock gD (vertragVon gD g_halte) false gCtx_halte gL_halte :=
  (.cons (.assignGlob GGlob.ANHALTEN .wahr (by decide) gGDarf_halte_ANHALTEN) (.ret .keine (List.Perm.refl _)))

def gBody_gehalten : Endblock gD (vertragVon gD g_gehalten) false gCtx_gehalten gL_gehalten :=
  (.ret (.wert (Expr.glob (D := gD) GGlob.ANHALTEN gGDarf_gehalten_ANHALTEN)) (List.Perm.refl _))

def gP : Programm gD where
  invariante := fun i => nomatch i
  requires
    | .halte => .wahr
    | .gehalten => .wahr
  ensures
    | .halte => .wahr
    | .gehalten => .wahr
  rumpf
    | .halte => gBody_halte
    | .gehalten => gBody_gehalten

def gFs : List gD.Fn := [g_halte, g_gehalten]

def gLs : List gD.Lock := []

def gCs : List (gD.Tab ⊕ gD.Glob) := [(.inr GGlob.ANHALTEN)]

example : programmImFragmentG gP gFs = true := by decide

-- No `fussOrtGB` check: some accessed carrier is taken in a
-- `locks` block (or written elsewhere unguarded), so the old
-- signature-held footprint does not apply. The applicable check
-- is the flagship's `FussS`/`fussSperreB`, which has no Rust rule.

-- The lock invariant family `gS` (`SperrInv`, `SperreSem.lean`):
def gS : SperrInv gD where
  orte := fun _ => []
  inv := fun _ _ => true


-- The declared initial memory (`Speicher gD`): every slot at zero,
-- every global at its DECLARED initialiser (a `static` names one).
def gSp0 : Speicher gD :=
  ⟨(fun t => nomatch t), (fun | .ANHALTEN => false)⟩

def gE : Zielsatz.Einheit gD where
  P := gP
  S := gS
  Q := fun _ _ _ => true
  starts := []
  sp0 := gSp0

-- THE USER'S OBLIGATION (stated, not discharged).
--
-- `NutzerPflichtA gE`: the bodies' logic WITH THE ATOMIC RELY (`LogikPflichtA`
-- -- per function and at EVERY `forever` budget the body triple against
-- every value a read of a shared atomic of the unit may return, with caller
-- duty and no `logik` outcome, owed invariants at value AND reason exits)
-- and the start obligation (`StartPflicht` -- every lock invariant at
-- `gE.sp0`, every declared start's `requires` there with its declared
-- arguments). On a unit without a shared atomic it is `NutzerPflicht gE`.
-- A `def` with no proof: the proof is the user's job. Stated through the
-- IMPORTED definition `NutzerPflichtA`; its body is never copied here.
def nutzerPflicht : Prop := Zielsatz.NutzerPflichtA gE

-- The member lists are complete (the `Aufzaehlung`s the goal theorem
-- quantifies over), decided here so the closing theorem below needs no
-- program fact beyond the user's obligation.
theorem gFs_voll : ∀ g : gD.Fn, g ∈ gFs := by
  intro g
  cases g <;> decide

theorem gLs_voll : ∀ L : gD.Lock, L ∈ gLs := by
  intro L
  cases L <;> decide

-- Carriers are tables or globals (lane 198 exports `static mut`
-- globals; a unit without one has `Glob := Empty`), and each arm
-- closes by cases over its constructors. `simp [gCs]`
-- and not `decide`: `DecidableEq (gD.Tab ⊕ gD.Glob)` does not unfold
-- the `gD` declaration during instance search (measured on 104/108:
-- `failed to synthesize Decidable (Sum.inl … ∈ gCs)`), while `simp`
-- rewrites membership over the literal list to constructor equalities.
theorem gCs_voll : ∀ c : gD.Tab ⊕ gD.Glob, c ∈ gCs := by
  intro c
  cases c with
  | inl t => cases t <;> simp [gCs]
  | inr g => cases g <;> simp [gCs]

-- The checker premise, discharged here: the concrete checker of the
-- goal theorem (`akzeptiertX_pruefer`, the Bool `AkzeptiertX`) accepts
-- this program on these lists. Where it does not, this `decide` fails --
-- loudly, not wrongly.
theorem gCheck : Zielsatz.akzeptiertX_pruefer.akzeptiert gE gFs gLs gCs = true := by decide

-- THE CLOSING THEOREM: the conclusion of `GabbroZiel` for this program on
-- every run of machine GX with every thread live (`gabbro_ziel_gx`). The
-- checker premise travels discharged (`gCheck`); the user's obligation
-- stays open as a hypothesis -- that is the point. Apply it once
-- `nutzerPflicht` is proved.
theorem gP_gabbro (hN : Zielsatz.NutzerPflichtA gE) (O : Orakel gD)
    (hH : Zielsatz.HardwareAnnahmen O gE.Q) (passes : Nat)
    (sp : Speicher gD.mitRuhe)
    (init : Faden → Σ f : gD.mitRuhe.Fn, Env gD.mitRuhe (gD.mitRuhe.params f))
    (hL : Zielsatz.Laufzeit gE sp init) (M : RufMaschineG gD.mitRuhe)
    (hr : RufErreichbarGX gE.P.mitRuhe O.mitRuhe passes (Zielsatz.GeteiltV (D := gD) gE.P gE.ws)
      (RufStartG gE.P.mitRuhe sp init) M) :
    Zielsatz.ZielX gE.P.mitRuhe gE.S.mitRuhe O.mitRuhe passes (Zielsatz.GeteiltV (D := gD) gE.P gE.ws)
      (RufStartG gE.P.mitRuhe sp init) M :=
  Zielsatz.gabbro_ziel_gx Zielsatz.akzeptiertX_pruefer gD gE ⟨gFs, gFs_voll⟩ ⟨gLs, gLs_voll⟩ ⟨gCs, gCs_voll⟩
    gCheck hN O hH passes sp init hL M hr

-- THE CLOSING THEOREM ON THE THREAD MACHINE: `GabbroZiel` itself for this
-- program -- `ZielFX` on every reachable thread machine over GX (run-time
-- spawns and joins included), from any set of initially live threads.
theorem gP_gabbro_f (hN : Zielsatz.NutzerPflichtA gE) (O : Orakel gD)
    (hH : Zielsatz.HardwareAnnahmen O gE.Q) (passes : Nat)
    (sp : Speicher gD.mitRuhe)
    (init : Faden → Σ f : gD.mitRuhe.Fn, Env gD.mitRuhe (gD.mitRuhe.params f))
    (hL : Zielsatz.Laufzeit gE sp init) (lebt0 : Faden → Bool)
    (K : FadenMaschine gD.mitRuhe)
    (hK : FadenErreichbarX gE.P.mitRuhe O.mitRuhe passes (Zielsatz.GeteiltV (D := gD) gE.P gE.ws)
      (FadenStart gE.P.mitRuhe sp init lebt0) K) :
    Zielsatz.ZielFX gE.P.mitRuhe gE.S.mitRuhe O.mitRuhe passes (Zielsatz.GeteiltV (D := gD) gE.P gE.ws)
      (RufStartG gE.P.mitRuhe sp init) K :=
  Zielsatz.gabbro_ziel Zielsatz.akzeptiertX_pruefer gD gE ⟨gFs, gFs_voll⟩ ⟨gLs, gLs_voll⟩ ⟨gCs, gCs_voll⟩
    gCheck hN O hH passes sp init hL lebt0 K hK

-- RELEASE OBLIGATIONS (stated, not discharged -- O12).
--
-- At every `locks L { ... }` exit the lock invariant of `L` must hold
-- again, and it must follow from what the section's callees PROMISE
-- (their `ensures`), not from what their bodies happen to do. What does
-- not follow is refused with `N511` (`freigabe_pruef.rs`); the rows below
-- state the same verdict per section (`beurteile`).
-- Each row below is syntactic, one-sided and order-aware (see
-- `crates/gabbro-check/src/freigabe.rs`): the invariant must follow from
-- the acquire frame, the section's own writes and what the section's
-- callees PROMISE (their `ensures`), never their bodies. `RELEASE HOLDS
-- (syntactic)` is not a proof, while `RELEASE UNPROVED` names the exact gap.
-- No lock carries an invariant -- nothing is owed at any release.
end G187_bool_statisch_oblig

end Gabbro.Grammatik
