-- GENERATED by `gabbro obligations --g beispiele/190-erster-treffer.gab` (lean-g export plus the stated obligation) -- do not edit.
-- A mechanical export of the checked unit as a G program term
-- (`Programm gD`, the syntax `RufMaschineG.lean` runs).
--
-- NO FORM in G (accepted and dropped, each named): the module
-- wrapper; named constants (inlined at every use); bare carrier
-- widths (a bare word travels as its full range); pointer address
-- spaces; lock hold budgets;
-- the `reads` effects; `costs`; the `by unvisited`/`by consuming`
-- run form, the `decreases` witness and the `touches` clause of a
-- `traverse` (static annotations, like `costs`); `by ops` on a field
-- (a writer discipline the checker holds); `mut` on a `let`;
-- `pub` and `opaque` (both are unit-boundary rules, and
-- `Deklaration` has no boundary -- `pub` added 2026-09-15 after
-- being dropped here and named nowhere, which is the one thing
-- this ledger exists to prevent; `opaque` the same day, when its
-- alias started to travel as its range);
-- `concurrent` (its members travel as the declared starts
-- `gE.starts`; every start is parameterless, its argument list
-- `.nil`); `entry`/`boot` (the vector, the registers, the steps:
-- NO FORM; only the dispatch root travels, as a declared start
-- where exportable, and a thrown `entry` -- one carrying a `via` path -- as
-- `gP.unterbricht`).
--
-- table 0: Plaetze (count 8), frei : bool
-- lock 0: K (rank 0) guards Plaetze
-- fn erster_frei_belegen (holds K; writes Plaetze)
import Grammatik.Zielsatz.ZielOrt.Geraet.ZielOrtGeraetSem
import Grammatik.Nebenlaeufigkeit.Sperren.SperreSem
import Grammatik.Zielsatz.Kern.Akzeptiert
import Grammatik.Zielsatz.Kern.Beweis
import Grammatik.Zielsatz.Atomar.BeweisAtomar
import Grammatik.Zielsatz.Kern.Spec

namespace Gabbro.Grammatik

namespace G190_erster_treffer_oblig

inductive GTab where
  | Plaetze
  deriving DecidableEq

inductive GLock where
  | K
  deriving DecidableEq

inductive GPlaetzeFeld where
  | frei
  deriving DecidableEq

inductive GFn where
  | erster_frei_belegen
  deriving DecidableEq

def gSig_erster_frei_belegen : Signatur GTab Empty GLock Empty where
  params := [.ptr 0 true]
  erg := none
  gruende := 0
  haelt := [GLock.K]
  boden := some 1
  schreibt := fun _ => true
  gschreibt := fun e => nomatch e
  konsumiert := []
  produziert := []

abbrev gD : Deklaration where
  Tab := GTab
  decTab := inferInstance
  count := fun | .Plaetze => 8
  Feld := fun | .Plaetze => GPlaetzeFeld
  decFeld := fun | .Plaetze => inferInstance
  typ := fun | .Plaetze, .frei => (.bool)
  erlaubt := fun _ _ _ _ => false
  tabNr := fun | 0 => some GTab.Plaetze | _ => none
  Glob := Empty
  decGlob := inferInstance
  gtyp := fun e => nomatch e
  nutzlast := fun e => nomatch e
  atomar := fun e => nomatch e
  geteilt := fun | .Plaetze => true
  ggeteilt := fun e => nomatch e
  Lock := GLock
  decLock := inferInstance
  rang := fun | .K => 0
  maskiert := fun _ => false
  Marke := Empty
  decMarke := inferInstance
  stufen := fun e => nomatch e
  braucht := fun | .Plaetze => [.inl GLock.K]
  gbraucht := fun e => nomatch e
  eigner := fun _ => []
  Fn := GFn
  sig := fun | .erster_frei_belegen => 0
  sigNr := fun | 0 => gSig_erster_frei_belegen | _ => gSig_erster_frei_belegen
  eigner_nie_erzeugt := fun _ _ _ _ h => by simp at h
  Inv := Empty
  traeger := fun e => nomatch e
  invs := []
  Ax := Empty
  aparams := fun e => nomatch e
  aerg := fun e => nomatch e
  aschreibt := fun e => nomatch e
  agschreibt := fun e => nomatch e
  Reg := Empty
  rtyp := fun e => nomatch e
  rklasse := fun e => nomatch e
  spiegel := fun e => nomatch e
  rzusage := fun e => nomatch e
  Annahme := Unit
  a10 := ()
  geteilt_bewacht := fun t => by cases t <;> decide
  invarianten_gehalten := fun _ i => nomatch i
  ggeteilt_bewacht := fun e => nomatch e

abbrev gCtx_erster_frei_belegen : Ctx := [.ptr 0 true]
def g_erster_frei_belegen : gD.Fn := GFn.erster_frei_belegen

abbrev gL_erster_frei_belegen : List (Res gD) := [Res.held (D := gD) GLock.K]

theorem gDarf_erster_frei_belegen_Plaetze : darf gD GTab.Plaetze gL_erster_frei_belegen := by unfold darf; decide

def gBody_erster_frei_belegen : Endblock gD (vertragVon gD g_erster_frei_belegen) false gCtx_erster_frei_belegen gL_erster_frei_belegen :=
  (.cons (.traverse GTab.Plaetze .wahr (.cons (.ite (Expr.durch (D := gD) (.var (.dort .hier)) GTab.Plaetze rfl GPlaetzeFeld.frei ((.var .hier)) gDarf_erster_frei_belegen_Plaetze) (.cons (.assignDurch (.var (.dort .hier)) GTab.Plaetze rfl GPlaetzeFeld.frei ((.var .hier)) .falsch (by decide) gDarf_erster_frei_belegen_Plaetze) (.cons (.leave rfl) .nil)) .nil) .nil)) (.ret .keine (List.Perm.refl _)))

def gP : Programm gD where
  invariante := fun i => nomatch i
  requires
    | .erster_frei_belegen => .wahr
  ensures
    | .erster_frei_belegen => .wahr
  rumpf
    | .erster_frei_belegen => gBody_erster_frei_belegen

def gFs : List gD.Fn := [g_erster_frei_belegen]

def gLs : List gD.Lock := [GLock.K]

def gCs : List (gD.Tab ⊕ gD.Glob) := [(.inl GTab.Plaetze)]

example : programmImFragmentG gP gFs = true := by decide

example : fussOrtGB gP gFs = true := by decide

-- The lock invariant family `gS` (`SperrInv`, `SperreSem.lean`):
-- lock K: no invariant (arm `fun _ => true`)
def gS : SperrInv gD where
  orte := fun | .K => [.inl GTab.Plaetze]
  inv := fun | .K => fun _ => true

example : ((gS.orte GLock.K).elem (.inl GTab.Plaetze) = true) := by decide
example : ((gD.braucht GTab.Plaetze).elem (Sum.inl GLock.K) = true) := by decide

-- The declared initial memory (`Speicher gD`): every slot at zero,
-- every global at its DECLARED initialiser (a `static` names one).
def gSp0 : Speicher gD :=
  ⟨(fun t _ f => match t, f with | .Plaetze, .frei => false), (fun g => nomatch g)⟩

def gE : Zielsatz.Einheit gD where
  P := gP
  S := gS
  Q := fun _ _ _ => true
  starts := []
  sp0 := gSp0

-- THE USER'S OBLIGATION (stated, not discharged).
--
-- `NutzerPflichtA gE`: the bodies' logic WITH THE ATOMIC RELY (`LogikPflichtA`
-- -- per function and at EVERY `forever` budget the body triple against
-- every value a read of a shared atomic of the unit may return, with caller
-- duty and no `logik` outcome, owed invariants at value AND reason exits)
-- and the start obligation (`StartPflicht` -- every lock invariant at
-- `gE.sp0`, every declared start's `requires` there with its declared
-- arguments). On a unit without a shared atomic it is `NutzerPflicht gE`.
-- A `def` with no proof: the proof is the user's job. Stated through the
-- IMPORTED definition `NutzerPflichtA`; its body is never copied here.
def nutzerPflicht : Prop := Zielsatz.NutzerPflichtA gE

-- The member lists are complete (the `Aufzaehlung`s the goal theorem
-- quantifies over), decided here so the closing theorem below needs no
-- program fact beyond the user's obligation.
theorem gFs_voll : ∀ g : gD.Fn, g ∈ gFs := by
  intro g
  cases g <;> decide

theorem gLs_voll : ∀ L : gD.Lock, L ∈ gLs := by
  intro L
  cases L <;> decide

-- Carriers are tables or globals (lane 198 exports `static mut`
-- globals; a unit without one has `Glob := Empty`), and each arm
-- closes by cases over its constructors. `simp [gCs]`
-- and not `decide`: `DecidableEq (gD.Tab ⊕ gD.Glob)` does not unfold
-- the `gD` declaration during instance search (measured on 104/108:
-- `failed to synthesize Decidable (Sum.inl … ∈ gCs)`), while `simp`
-- rewrites membership over the literal list to constructor equalities.
theorem gCs_voll : ∀ c : gD.Tab ⊕ gD.Glob, c ∈ gCs := by
  intro c
  cases c with
  | inl t => cases t <;> simp [gCs]
  | inr g => cases g <;> simp [gCs]

-- The checker premise, discharged here: the concrete checker of the
-- goal theorem (`akzeptiertX_pruefer`, the Bool `AkzeptiertX`) accepts
-- this program on these lists. Where it does not, this `decide` fails --
-- loudly, not wrongly.
theorem gCheck : Zielsatz.akzeptiertX_pruefer.akzeptiert gE gFs gLs gCs = true := by decide

-- THE CLOSING THEOREM: the conclusion of `GabbroZiel` for this program on
-- every run of machine GX with every thread live (`gabbro_ziel_gx`). The
-- checker premise travels discharged (`gCheck`); the user's obligation
-- stays open as a hypothesis -- that is the point. Apply it once
-- `nutzerPflicht` is proved.
theorem gP_gabbro (hN : Zielsatz.NutzerPflichtA gE) (O : Orakel gD)
    (hH : Zielsatz.HardwareAnnahmen O gE.Q) (passes : Nat)
    (sp : Speicher gD.mitRuhe)
    (init : Faden → Σ f : gD.mitRuhe.Fn, Env gD.mitRuhe (gD.mitRuhe.params f))
    (hL : Zielsatz.Laufzeit gE sp init) (M : RufMaschineG gD.mitRuhe)
    (hr : RufErreichbarGX gE.P.mitRuhe O.mitRuhe passes (Zielsatz.GeteiltV (D := gD) gE.P gE.ws)
      (RufStartG gE.P.mitRuhe sp init) M) :
    Zielsatz.ZielX gE.P.mitRuhe gE.S.mitRuhe O.mitRuhe passes (Zielsatz.GeteiltV (D := gD) gE.P gE.ws)
      (RufStartG gE.P.mitRuhe sp init) M :=
  Zielsatz.gabbro_ziel_gx Zielsatz.akzeptiertX_pruefer gD gE ⟨gFs, gFs_voll⟩ ⟨gLs, gLs_voll⟩ ⟨gCs, gCs_voll⟩
    gCheck hN O hH passes sp init hL M hr

-- THE CLOSING THEOREM ON THE THREAD MACHINE: `GabbroZiel` itself for this
-- program -- `ZielFX` on every reachable thread machine over GX (run-time
-- spawns and joins included), from any set of initially live threads.
theorem gP_gabbro_f (hN : Zielsatz.NutzerPflichtA gE) (O : Orakel gD)
    (hH : Zielsatz.HardwareAnnahmen O gE.Q) (passes : Nat)
    (sp : Speicher gD.mitRuhe)
    (init : Faden → Σ f : gD.mitRuhe.Fn, Env gD.mitRuhe (gD.mitRuhe.params f))
    (hL : Zielsatz.Laufzeit gE sp init) (lebt0 : Faden → Bool)
    (K : FadenMaschine gD.mitRuhe)
    (hK : FadenErreichbarX gE.P.mitRuhe O.mitRuhe passes (Zielsatz.GeteiltV (D := gD) gE.P gE.ws)
      (FadenStart gE.P.mitRuhe sp init lebt0) K) :
    Zielsatz.ZielFX gE.P.mitRuhe gE.S.mitRuhe O.mitRuhe passes (Zielsatz.GeteiltV (D := gD) gE.P gE.ws)
      (RufStartG gE.P.mitRuhe sp init) K :=
  Zielsatz.gabbro_ziel Zielsatz.akzeptiertX_pruefer gD gE ⟨gFs, gFs_voll⟩ ⟨gLs, gLs_voll⟩ ⟨gCs, gCs_voll⟩
    gCheck hN O hH passes sp init hL lebt0 K hK

-- RELEASE OBLIGATIONS (stated, not discharged -- O12).
--
-- At every `locks L { ... }` exit the lock invariant of `L` must hold
-- again, and it must follow from what the section's callees PROMISE
-- (their `ensures`), not from what their bodies happen to do. What does
-- not follow is refused with `N511` (`freigabe_pruef.rs`); the rows below
-- state the same verdict per section (`beurteile`).
-- Each row below is syntactic, one-sided and order-aware (see
-- `crates/gabbro-check/src/freigabe.rs`): the invariant must follow from
-- the acquire frame, the section's own writes and what the section's
-- callees PROMISE (their `ensures`), never their bodies. `RELEASE HOLDS
-- (syntactic)` is not a proof, while `RELEASE UNPROVED` names the exact gap.
-- No lock carries an invariant -- nothing is owed at any release.
end G190_erster_treffer_oblig

end Gabbro.Grammatik
